-- 004_seed_sentences_part1.sql
-- Category 1: Günlük Konuşma  (30 sentences, is_free: true)
-- Category 2: İş İngilizcesi   (30 sentences, is_free: true)
-- Category 3: Phrasal Verbs    (30 sentences, is_free: false)
--
-- Her cümle bir tabir/ifade öğretir. Tabir **çift yıldız** ile işaretlenir.

DELETE FROM sentences WHERE category_id IN (1, 2, 3);

-- ─── CATEGORY 1 — Günlük Konuşma ────────────────────────────────────────────

INSERT INTO sentences (category_id, text_tr, text_en, text_sv, text_de, keywords_tr, keywords_en, keywords_sv, keywords_de, difficulty, is_free, sort_order) VALUES

-- Beginner
(1, '**Bu arada**, yarın serbest misin?', '**By the way**, are you free tomorrow?', '**Förresten**, är du ledig imorgon?', '**Übrigens**, bist du morgen frei?', '["bu arada"]', '["by the way"]', '["förresten"]', '["übrigens"]', 'beginner', true, 1),
(1, '**Yani**, bunu gerçekten söylüyor musun?', '**I mean**, are you really saying that?', '**Alltså**, menar du verkligen det?', '**Ich meine**, sagst du das wirklich?', '["yani"]', '["I mean"]', '["alltså"]', '["ich meine"]', 'beginner', true, 2),
(1, '**Biliyor musun**, bu tam aradığım şey.', '**You know what**, this is exactly what I needed.', '**Vet du vad**, det här är precis vad jag behövde.', '**Weißt du was**, das ist genau das, was ich gebraucht habe.', '["biliyor musun"]', '["you know what"]', '["vet du vad"]', '["weißt du was"]', 'beginner', true, 3),
(1, '**Dürüst olmak gerekirse**, bu film pek hoşuma gitmedi.', '**To be honest**, I didn''t really enjoy this film.', '**För att vara ärlig**, tyckte jag inte så mycket om den här filmen.', '**Ehrlich gesagt** hat mir dieser Film nicht wirklich gefallen.', '["dürüst olmak gerekirse"]', '["to be honest"]', '["för att vara ärlig"]', '["ehrlich gesagt"]', 'beginner', true, 4),
(1, '**Her şeyden önce**, teşekkür etmek istiyorum.', '**First of all**, I want to say thank you.', '**Först och främst** vill jag säga tack.', '**Zunächst einmal** möchte ich Danke sagen.', '["her şeyden önce"]', '["first of all"]', '["först och främst"]', '["zunächst einmal"]', 'beginner', true, 5),
(1, 'Gelmeseydin bile **en azından** bir mesaj atabilirdin.', 'Even if you couldn''t come, you could have **at least** sent a message.', 'Även om du inte kunde komma kunde du **åtminstone** ha skickat ett meddelande.', 'Auch wenn du nicht kommen konntest, hättest du **zumindest** eine Nachricht schicken können.', '["en azından"]', '["at least"]', '["åtminstone"]', '["zumindest"]', 'beginner', true, 6),
(1, 'Bunu **hemen** halledelim.', 'Let''s take care of this **right away**.', 'Låt oss ta hand om det här **genast**.', 'Lass uns das **sofort** erledigen.', '["hemen"]', '["right away"]', '["genast"]', '["sofort"]', 'beginner', true, 7),
(1, '**Kesinlikle** yardım edebilirim.', 'I can **for sure** help you with that.', 'Jag kan **definitivt** hjälpa dig med det.', 'Ich kann dir dabei **auf jeden Fall** helfen.', '["kesinlikle"]', '["for sure"]', '["definitivt"]', '["auf jeden Fall"]', 'beginner', true, 8),
(1, 'Rahatsız ediyor muyum? — **Hiç de değil**!', 'Am I bothering you? — **Not at all**!', 'Stör jag dig? — **Inte alls**!', 'Störe ich dich? — **Überhaupt nicht**!', '["hiç de değil"]', '["not at all"]', '["inte alls"]', '["überhaupt nicht"]', 'beginner', true, 9),
(1, '**Tabii ki** sana yardım ederim, sor istediğini.', '**Of course** I''ll help you, just ask.', '**Självklart** hjälper jag dig, fråga bara.', '**Natürlich** helfe ich dir, frag einfach.', '["tabii ki"]', '["of course"]', '["självklart"]', '["natürlich"]', 'beginner', true, 10),

-- Intermediate
(1, '**Sonuçta**, herkes hata yapar.', '**After all**, everyone makes mistakes.', '**Trots allt** gör alla misstag.', '**Schließlich** macht jeder Fehler.', '["sonuçta"]', '["after all"]', '["trots allt"]', '["schließlich"]', 'intermediate', true, 11),
(1, '**Nasıl oluyor** da bu kadar hızlı öğrenebiliyorsun?', '**How come** you can learn so fast?', '**Hur kommer det sig** att du kan lära dig så snabbt?', '**Wie kommt es**, dass du so schnell lernen kannst?', '["nasıl oluyor"]', '["how come"]', '["hur kommer det sig"]', '["wie kommt es"]', 'intermediate', true, 12),
(1, '**Peki ya** sen, ne düşünüyorsun?', '**What about** you, what do you think?', '**Vad sägs om** dig, vad tycker du?', '**Was ist mit** dir, was denkst du?', '["peki ya"]', '["what about"]', '["vad sägs om"]', '["was ist mit"]', 'intermediate', true, 13),
(1, '**Bana gelince**, evde kalmayı tercih ederim.', '**As for me**, I prefer to stay home.', '**Vad gäller mig** föredrar jag att stanna hemma.', '**Was mich betrifft**, bleibe ich lieber zu Hause.', '["bana gelince"]', '["as for me"]', '["vad gäller mig"]', '["was mich betrifft"]', 'intermediate', true, 14),
(1, 'Bir şey sorabilir miyim? — **Buyurun**!', 'May I ask something? — **Go ahead**!', 'Får jag fråga något? — **Varsågod**!', 'Darf ich etwas fragen? — **Bitte sehr**!', '["buyurun"]', '["go ahead"]', '["varsågod"]', '["bitte sehr"]', 'intermediate', true, 15),
(1, 'Geç kaldım, özür dilerim. — **Boşver**, önemli değil.', 'I''m late, I''m sorry. — **Never mind**, it''s okay.', 'Jag är sen, förlåt. — **Strunta i det**, det är okej.', 'Ich bin spät, tut mir leid. — **Macht nichts**, ist okay.', '["boşver"]', '["never mind"]', '["strunta i det"]', '["macht nichts"]', 'intermediate', true, 16),
(1, '**Bir dakika**, telefonum nerede acaba?', '**Hold on**, where is my phone?', '**Vänta lite**, var är min telefon?', '**Einen Moment**, wo ist mein Handy?', '["bir dakika"]', '["hold on"]', '["vänta lite"]', '["einen Moment"]', 'intermediate', true, 17),
(1, '**Acele etme**, hep birlikte bekliyoruz.', '**Take your time**, we''re all waiting.', '**Ta dig tid**, vi väntar alla.', '**Lass dir Zeit**, wir warten alle.', '["acele etme"]', '["take your time"]', '["ta dig tid"]', '["lass dir Zeit"]', 'intermediate', true, 18),
(1, '**Aslında**, sana bir şey söylemek istiyordum.', '**Actually**, I''ve been meaning to tell you something.', '**Faktiskt** har jag velat berätta något för dig.', '**Eigentlich** wollte ich dir schon länger etwas sagen.', '["aslında"]', '["actually"]', '["faktiskt"]', '["eigentlich"]', 'intermediate', true, 19),
(1, 'Çok zor görünüyor, **gerçekte** ise oldukça kolay.', 'It looks difficult, but **in fact** it''s quite easy.', 'Det ser svårt ut, men **i själva verket** är det ganska enkelt.', 'Es sieht schwierig aus, aber **tatsächlich** ist es ziemlich einfach.', '["gerçekte"]', '["in fact"]', '["i själva verket"]', '["tatsächlich"]', 'intermediate', true, 20),

-- Advanced
(1, 'Bu durum **bir nevi** garip, değil mi?', 'This situation is **kind of** weird, isn''t it?', 'Den här situationen är **lite** konstig, eller hur?', 'Diese Situation ist **irgendwie** seltsam, oder?', '["bir nevi"]', '["kind of"]', '["lite"]', '["irgendwie"]', 'advanced', true, 21),
(1, '**Şaşılacak bir şey yok** ki yoruldun, tüm gün çalıştın.', '**No wonder** you''re tired, you worked all day.', '**Inte konstigt** att du är trött, du jobbade hela dagen.', '**Kein Wunder**, dass du müde bist, du hast den ganzen Tag gearbeitet.', '["şaşılacak bir şey yok"]', '["no wonder"]', '["inte konstigt"]', '["kein Wunder"]', 'advanced', true, 22),
(1, 'Nereye gidiyoruz? — **Sana kalmış**, sen seç.', 'Where are we going? — **It''s up to you**, you choose.', 'Vart ska vi? — **Det är upp till dig**, du väljer.', 'Wohin fahren wir? — **Das liegt bei dir**, du entscheidest.', '["sana kalmış"]', '["it''s up to you"]', '["det är upp till dig"]', '["das liegt bei dir"]', 'advanced', true, 23),
(1, '**Uzun zamandır görüşmüyorduk**! Nasılsın?', '**Long time no see**! How have you been?', '**Länge sedan sist**! Hur har du haft det?', '**Lange nicht gesehen**! Wie geht es dir?', '["uzun zamandır görüşmüyorduk"]', '["long time no see"]', '["länge sedan sist"]', '["lange nicht gesehen"]', 'advanced', true, 24),
(1, 'Özür dilerim, zaman aldı. — **Büyük bir şey değil**, merak etme.', 'Sorry it took so long. — **No big deal**, don''t worry.', 'Förlåt att det tog tid. — **Ingen stor sak**, oroa dig inte.', 'Es tut mir leid, dass es so lange dauerte. — **Keine große Sache**, keine Sorge.', '["büyük bir şey değil"]', '["no big deal"]', '["ingen stor sak"]', '["keine große Sache"]', 'advanced', true, 25),
(1, 'Bir şemsiye al, **her ihtimale karşı**.', 'Take an umbrella, **just in case**.', 'Ta ett paraply, **för säkerhets skull**.', 'Nimm einen Regenschirm mit, **für alle Fälle**.', '["her ihtimale karşı"]', '["just in case"]', '["för säkerhets skull"]', '["für alle Fälle"]', 'advanced', true, 26),
(1, 'Pahalı, **bunun yanı sıra** çok uzakta da.', 'It''s expensive, **besides** it''s very far away.', 'Det är dyrt, **dessutom** är det väldigt långt bort.', 'Es ist teuer, **außerdem** ist es sehr weit entfernt.', '["bunun yanı sıra"]', '["besides"]', '["dessutom"]', '["außerdem"]', 'advanced', true, 27),
(1, '**Her neyse**, konuya dönelim.', '**Anyway**, let''s get back to the topic.', '**Hur som helst**, låt oss komma tillbaka till ämnet.', '**Jedenfalls**, lass uns zum Thema zurückkehren.', '["her neyse"]', '["anyway"]', '["hur som helst"]', '["jedenfalls"]', 'advanced', true, 28),
(1, '**Sanırım** haklısın, düşünmem gerekiyor.', '**I suppose** you''re right, I need to think about it.', '**Jag antar** att du har rätt, jag behöver tänka på det.', '**Ich nehme an**, du hast recht, ich muss darüber nachdenken.', '["sanırım"]', '["I suppose"]', '["jag antar"]', '["ich nehme an"]', 'advanced', true, 29),
(1, '**Ne demek istiyorsun** tam olarak, anlamadım.', '**What do you mean** exactly? I didn''t get it.', '**Vad menar du** exakt? Jag förstod inte.', '**Was meinst du** genau? Ich habe das nicht verstanden.', '["ne demek istiyorsun"]', '["what do you mean"]', '["vad menar du"]', '["was meinst du"]', 'advanced', true, 30);

-- ─── CATEGORY 2 — İş İngilizcesi ────────────────────────────────────────────

INSERT INTO sentences (category_id, text_tr, text_en, text_sv, text_de, keywords_tr, keywords_en, keywords_sv, keywords_de, difficulty, is_free, sort_order) VALUES

-- Beginner
(2, 'Araştırıp **size geri döneceğim**.', 'I''ll look into it and **get back to you**.', 'Jag ska undersöka det och **återkomma till dig**.', 'Ich werde das prüfen und mich **bei Ihnen melden**.', '["size geri döneceğim"]', '["get back to you"]', '["återkomma till dig"]', '["bei Ihnen melden"]', 'beginner', true, 31),
(2, 'Bu konuyu **takip etmem** gerekiyor.', 'I need to **follow up** on this matter.', 'Jag behöver **följa upp** den här frågan.', 'Ich muss dieses Thema **nachverfolgen**.', '["takip etmem"]', '["follow up"]', '["följa upp"]', '["nachverfolgen"]', 'beginner', true, 32),
(2, 'Haftaya **kısaca görüşelim**.', 'Let''s **touch base** next week.', 'Låt oss **höras av** nästa vecka.', 'Lass uns nächste Woche **kurz in Kontakt treten**.', '["kısaca görüşelim"]', '["touch base"]', '["höras av"]', '["kurz in Kontakt treten"]', 'beginner', true, 33),
(2, 'Bunu yaparken **aklında tut**.', 'Please **keep in mind** while you do this.', 'Ha det i **åtanke** när du gör det.', 'Bitte **behalte das im Hinterkopf**, wenn du das tust.', '["aklında tut"]', '["keep in mind"]', '["åtanke"]', '["behalte das im Hinterkopf"]', 'beginner', true, 34),
(2, 'Raporu **en kısa sürede** gönderebilir misin?', 'Can you send the report **as soon as possible**?', 'Kan du skicka rapporten **så snart som möjligt**?', 'Kannst du den Bericht **so schnell wie möglich** schicken?', '["en kısa sürede"]', '["as soon as possible"]', '["så snart som möjligt"]', '["so schnell wie möglich"]', 'beginner', true, 35),
(2, 'Projeyle **ilerleyelim**.', 'Let''s **move forward** with the project.', 'Låt oss **gå vidare** med projektet.', 'Lass uns mit dem Projekt **vorankommen**.', '["ilerleyelim"]', '["move forward"]', '["gå vidare"]', '["vorankommen"]', 'beginner', true, 36),
(2, 'Müşteriyle **iletişime geçmem** gerekiyor.', 'I need to **reach out** to the client.', 'Jag behöver **kontakta** kunden.', 'Ich muss mich mit dem Kunden **in Verbindung setzen**.', '["iletişime geçmem"]', '["reach out"]', '["kontakta"]', '["in Verbindung setzen"]', 'beginner', true, 37),
(2, 'Bu sorunu **araştıracağım**.', 'I''ll **look into** this problem.', 'Jag ska **undersöka** det här problemet.', 'Ich werde dieses Problem **untersuchen**.', '["araştıracağım"]', '["look into"]', '["undersöka"]', '["untersuchen"]', 'beginner', true, 38),
(2, 'Toplantıyı **bitirelim** artık.', 'Let''s **wrap up** the meeting now.', 'Låt oss **avsluta** mötet nu.', 'Lass uns die Besprechung jetzt **abschließen**.', '["bitirelim"]', '["wrap up"]', '["avsluta"]', '["abschließen"]', 'beginner', true, 39),
(2, 'Yeni bir çözüm **bulmamız** lazım.', 'We need to **come up with** a new solution.', 'Vi behöver **hitta på** en ny lösning.', 'Wir müssen eine neue Lösung **finden**.', '["bulmamız"]', '["come up with"]', '["hitta på"]', '["finden"]', 'beginner', true, 40),

-- Intermediate
(2, 'Bu meseleyi ben **halledeceğim**.', 'I''ll **take care of** this issue.', 'Jag ska **ta hand om** det här problemet.', 'Ich werde mich um diese Angelegenheit **kümmern**.', '["halledeceğim"]', '["take care of"]', '["ta hand om"]', '["kümmern"]', 'intermediate', true, 41),
(2, 'Raporun durumunu **kontrol edeyim**.', 'Let me **check in** on the report status.', 'Låt mig **kolla av** rapportens status.', 'Lass mich den Status des Berichts **überprüfen**.', '["kontrol edeyim"]', '["check in"]', '["kolla av"]', '["überprüfen"]', 'intermediate', true, 42),
(2, 'Sunumu birlikte **gözden geçirelim**.', 'Let''s **go over** the presentation together.', 'Låt oss **gå igenom** presentationen tillsammans.', 'Lass uns die Präsentation gemeinsam **durchgehen**.', '["gözden geçirelim"]', '["go over"]', '["gå igenom"]', '["durchgehen"]', 'intermediate', true, 43),
(2, 'Bu problemi nasıl **çözeceğiz**?', 'How are we going to **deal with** this problem?', 'Hur ska vi **hantera** det här problemet?', 'Wie werden wir mit diesem Problem **umgehen**?', '["çözeceğiz"]', '["deal with"]', '["hantera"]', '["umgehen"]', 'intermediate', true, 44),
(2, 'Bütçe konusunu toplantıda **gündeme getirmeliyiz**.', 'We should **bring up** the budget topic in the meeting.', 'Vi bör **ta upp** budgetfrågan på mötet.', 'Wir sollten das Budgetthema im Meeting **ansprechen**.', '["gündeme getirmeliyiz"]', '["bring up"]', '["ta upp"]', '["ansprechen"]', 'intermediate', true, 45),
(2, 'Araştırmayı bu hafta **tamamlayacağız**.', 'We''ll **carry out** the research this week.', 'Vi ska **genomföra** forskningen den här veckan.', 'Wir werden die Forschung diese Woche **durchführen**.', '["tamamlayacağız"]', '["carry out"]', '["genomföra"]', '["durchführen"]', 'intermediate', true, 46),
(2, 'Seni **gelişmelerden haberdar** edeceğim.', 'I''ll keep you **in the loop**.', 'Jag håller dig **informerad**.', 'Ich werde dich **auf dem Laufenden** halten.', '["gelişmelerden haberdar"]', '["in the loop"]', '["informerad"]', '["auf dem Laufenden"]', 'intermediate', true, 47),
(2, 'Bu konuda hepimiz **aynı fikirde miyiz**?', 'Are we all **on the same page** about this?', 'Är vi alla **överens** om det här?', 'Sind wir alle in dieser Sache **einer Meinung**?', '["aynı fikirde"]', '["on the same page"]', '["överens"]', '["einer Meinung"]', 'intermediate', true, 48),
(2, '**Önceden uyarmak** istedim: sistem bakımda olacak.', 'Just a **heads up**: the system will be down for maintenance.', 'Bara en **förhandsvarning**: systemet kommer att vara nere för underhåll.', 'Nur zur **Vorab-Information**: Das System wird für Wartungsarbeiten ausfallen.', '["önceden uyarmak"]', '["heads up"]', '["förhandsvarning"]', '["Vorab-Information"]', 'intermediate', true, 49),
(2, 'Bu projede sen **öncülük et**.', 'You should **take the lead** on this project.', 'Du bör **leda** det här projektet.', 'Du solltest bei diesem Projekt **die Führung übernehmen**.', '["öncülük et"]', '["take the lead"]', '["leda"]', '["die Führung übernehmen"]', 'intermediate', true, 50),

-- Advanced
(2, 'Yeni dönemi resmi olarak **başlatalım**.', 'Let''s officially **kick off** the new quarter.', 'Låt oss officiellt **kicka igång** det nya kvartalet.', 'Lass uns das neue Quartal offiziell **einleiten**.', '["başlatalım"]', '["kick off"]', '["kicka igång"]', '["einleiten"]', 'advanced', true, 51),
(2, 'Anlaşmayı **onaylayabilir misin**?', 'Can you **sign off** on the agreement?', 'Kan du **godkänna** avtalet?', 'Kannst du die Vereinbarung **genehmigen**?', '["onaylayabilir misin"]', '["sign off"]', '["godkänna"]', '["genehmigen"]', 'advanced', true, 52),
(2, 'Beni **bilgilendirebilir misin**?', 'Can you **fill me in**?', 'Kan du **informera** mig?', 'Kannst du mich **informieren**?', '["bilgilendirebilir misin"]', '["fill me in"]', '["informera"]', '["informieren"]', 'advanced', true, 53),
(2, '**Bundan sonra** haftalık raporlar paylaşılacak.', '**Going forward**, weekly reports will be shared.', '**Framöver** kommer veckorapporter att delas.', '**Zukünftig** werden wöchentliche Berichte geteilt.', '["bundan sonra"]', '["going forward"]', '["framöver"]', '["zukünftig"]', 'advanced', true, 54),
(2, '**Müsait olduğunuzda** bir görüşme ayarlayalım.', 'Let''s arrange a call **at your earliest convenience**.', 'Låt oss boka ett samtal **när det passar dig**.', 'Lass uns ein Gespräch **nach Ihrer Verfügbarkeit** vereinbaren.', '["müsait olduğunuzda"]', '["at your earliest convenience"]', '["när det passar dig"]', '["nach Ihrer Verfügbarkeit"]', 'advanced', true, 55),
(2, 'Yeni sistemi **kurmamız** gerekiyor.', 'We need to **set up** the new system.', 'Vi behöver **installera** det nya systemet.', 'Wir müssen das neue System **einrichten**.', '["kurmamız"]', '["set up"]', '["installera"]', '["einrichten"]', 'advanced', true, 56),
(2, 'Projeyi iki günde **teslim etmem** gerekiyor.', 'I need to **turn this around** in two days.', 'Jag behöver **slutföra** det här på två dagar.', 'Ich muss das in zwei Tagen **abwickeln**.', '["teslim etmem"]', '["turn this around"]', '["slutföra"]', '["abwickeln"]', 'advanced', true, 57),
(2, 'Neden bu kadar zaman aldığını **anlamamız** lazım.', 'We need to **figure out** why this is taking so long.', 'Vi måste **lista ut** varför det här tar så lång tid.', 'Wir müssen **herausfinden**, warum das so lange dauert.', '["anlamamız"]', '["figure out"]', '["lista ut"]', '["herausfinden"]', 'advanced', true, 58),
(2, 'Bunu müdüre **onaylatmam** gerekiyor.', 'I need to **run this by** the manager first.', 'Jag behöver **stämma av** detta med chefen först.', 'Ich muss das zuerst mit dem Manager **absprechen**.', '["onaylatmam"]', '["run this by"]', '["stämma av"]', '["absprechen"]', 'advanced', true, 59),
(2, 'Sunumu birlikte **hazırlayalım**.', 'Let''s **put together** the presentation.', 'Låt oss **sätta ihop** presentationen.', 'Lass uns die Präsentation **zusammenstellen**.', '["hazırlayalım"]', '["put together"]', '["sätta ihop"]', '["zusammenstellen"]', 'advanced', true, 60);

-- ─── CATEGORY 3 — Phrasal Verbs ─────────────────────────────────────────────

INSERT INTO sentences (category_id, text_tr, text_en, text_sv, text_de, keywords_tr, keywords_en, keywords_sv, keywords_de, difficulty, is_free, sort_order) VALUES

-- Beginner
(3, 'Hiç **vazgeçme**, yapabilirsin!', 'Never **give up**, you can do it!', 'Ge aldrig **upp**, du kan göra det!', 'Gib niemals **auf**, du schaffst das!', '["vazgeçme"]', '["give up"]', '["ge upp"]', '["aufgeben"]', 'beginner', false, 61),
(3, 'Param **bitti**, ATM''ye gitmem lazım.', 'I **ran out of** money, I need to find an ATM.', 'Jag **fick slut på** pengar, jag behöver hitta en bankomat.', 'Mir ist das Geld **ausgegangen**, ich muss einen Geldautomaten finden.', '["bitti"]', '["ran out of"]', '["fick slut på"]', '["ausgegangen"]', 'beginner', false, 62),
(3, 'Seni havalimanından **alacağım**.', 'I''ll **pick you up** from the airport.', 'Jag ska **hämta** dig på flygplatsen.', 'Ich hole dich vom Flughafen **ab**.', '["alacağım"]', '["pick up"]', '["hämta"]', '["abholen"]', 'beginner', false, 63),
(3, 'Bu tatili dört gözle **bekliyorum**.', 'I''m really **looking forward to** this holiday.', 'Jag ser verkligen **fram emot** den här semestern.', 'Ich **freue mich wirklich** auf diesen Urlaub.', '["bekliyorum"]', '["looking forward to"]', '["fram emot"]', '["freue mich"]', 'beginner', false, 64),
(3, 'İnternette ilginç bir makaleye **rastladım**.', 'I **came across** an interesting article online.', 'Jag **stötte på** en intressant artikel på nätet.', 'Ich bin online auf einen interessanten Artikel **gestoßen**.', '["rastladım"]', '["came across"]', '["stötte på"]', '["gestoßen"]', 'beginner', false, 65),
(3, 'Arabam yolda **bozuldu**.', 'My car **broke down** on the road.', 'Min bil **gick sönder** på vägen.', 'Mein Auto ist unterwegs **liegen geblieben**.', '["bozuldu"]', '["broke down"]', '["gick sönder"]', '["liegen geblieben"]', 'beginner', false, 66),
(3, 'Haberlerle **güncel kalmak** zor.', 'It''s hard to **catch up** with all the news.', 'Det är svårt att **hålla sig uppdaterad** med alla nyheter.', 'Es ist schwer, mit all den Nachrichten **Schritt zu halten**.', '["güncel kalmak"]', '["catch up"]', '["hålla sig uppdaterad"]', '["Schritt zu halten"]', 'beginner', false, 67),
(3, 'Sözlükte bu kelimenin anlamını **baktım**.', 'I **looked up** the meaning of this word in the dictionary.', 'Jag **slog upp** betydelsen av det här ordet i ordboken.', 'Ich habe die Bedeutung dieses Wortes im Wörterbuch **nachgeschlagen**.', '["baktım"]', '["looked up"]', '["slog upp"]', '["nachgeschlagen"]', 'beginner', false, 68),
(3, 'Tatili bir hafta **erteledik**.', 'We **put off** the holiday by one week.', 'Vi **sköt upp** semestern med en vecka.', 'Wir haben den Urlaub um eine Woche **verschoben**.', '["erteledik"]', '["put off"]', '["sköt upp"]', '["verschoben"]', 'beginner', false, 69),
(3, 'İş teklifini **reddetti**.', 'She **turned down** the job offer.', 'Hon **tackade nej till** jobberbjudandet.', 'Sie hat das Stellenangebot **abgelehnt**.', '["reddetti"]', '["turned down"]', '["tackade nej till"]', '["abgelehnt"]', 'beginner', false, 70),

-- Intermediate
(3, 'Hayatında çok zor şeyler **yaşadı**.', 'She has **gone through** many difficult things in life.', 'Hon har **gått igenom** många svåra saker i livet.', 'Sie hat im Leben viele schwierige Dinge **durchgemacht**.', '["yaşadı"]', '["gone through"]', '["gått igenom"]', '["durchgemacht"]', 'intermediate', false, 71),
(3, 'Eve gitmeyi planlıyordum ama parkta **kaldım**.', 'I planned to go home but I **ended up** staying in the park.', 'Jag planerade att åka hem men **hamnade** i parken.', 'Ich wollte nach Hause gehen, bin aber im Park **geblieben**.', '["kaldım"]', '["ended up"]', '["hamnade"]', '["geblieben"]', 'intermediate', false, 72),
(3, 'Trendlerle **ayak uydurmak** zor.', 'It''s hard to **keep up with** the latest trends.', 'Det är svårt att **hålla jämna steg med** de senaste trenderna.', 'Es ist schwer, mit den neuesten Trends **Schritt zu halten**.', '["ayak uydurmak"]', '["keep up with"]', '["hålla jämna steg med"]', '["Schritt zu halten"]', 'intermediate', false, 73),
(3, 'Kardeşime **bakıyorum** bu hafta.', 'I''m **looking after** my little sibling this week.', 'Jag **passar** mitt syskon den här veckan.', 'Ich **passe** diese Woche auf mein Geschwister **auf**.', '["bakıyorum"]', '["looking after"]', '["passar"]', '["passe auf"]', 'intermediate', false, 74),
(3, 'Bu sorunu bir şekilde **halletmemiz** lazım.', 'We need to **sort out** this problem somehow.', 'Vi behöver **lösa** det här problemet på något sätt.', 'Wir müssen dieses Problem irgendwie **lösen**.', '["halletmemiz"]', '["sort out"]', '["lösa"]', '["lösen"]', 'intermediate', false, 75),
(3, 'Markette eski bir arkadaşıma **rastladım**.', 'I **ran into** an old friend at the supermarket.', 'Jag **råkade stöta på** en gammal vän i mataffären.', 'Ich bin im Supermarkt einem alten Freund **begegnet**.', '["rastladım"]', '["ran into"]', '["råkade stöta på"]', '["begegnet"]', 'intermediate', false, 76),
(3, 'Her şey **yoluna girdi** sonunda.', 'Everything **worked out** in the end.', 'Allt **löste sig** till slut.', 'Am Ende hat sich alles **ergeben**.', '["yoluna girdi"]', '["worked out"]', '["löste sig"]', '["ergeben"]', 'intermediate', false, 77),
(3, 'Şekeri **azaltmaya** çalışıyorum.', 'I''m trying to **cut down on** sugar.', 'Jag försöker **minska** mitt sockerintag.', 'Ich versuche, Zucker zu **reduzieren**.', '["azaltmaya"]', '["cut down on"]', '["minska"]', '["reduzieren"]', 'intermediate', false, 78),
(3, 'Yeni iş arkadaşlarımla **iyi geçiniyorum**.', 'I **get along with** my new colleagues well.', 'Jag **kommer bra överens med** mina nya kollegor.', 'Ich **komme gut aus** mit meinen neuen Kollegen.', '["iyi geçiniyorum"]', '["get along with"]', '["kommer bra överens med"]', '["komme gut aus"]', 'intermediate', false, 79),
(3, 'Onun bu kadar geç gelmesi beni **hayal kırıklığına uğrattı**.', 'Him arriving so late really **let me down**.', 'Att han kom så sent besvikna mig verkligen **svek mig**.', 'Dass er so spät kam, hat mich wirklich **enttäuscht**.', '["hayal kırıklığına uğrattı"]', '["let me down"]', '["svek mig"]', '["enttäuscht"]', 'intermediate', false, 80),

-- Advanced
(3, 'Bu şehrin havasına **alışmak** zaman aldı.', 'It took time to **get used to** this city''s weather.', 'Det tog tid att **vänja sig** vid den här stadens väder.', 'Es brauchte Zeit, sich an das Klima dieser Stadt zu **gewöhnen**.', '["alışmak"]', '["get used to"]', '["vänja sig"]', '["gewöhnen"]', 'advanced', false, 81),
(3, 'Bu kadar gürültüye daha fazla **katlanamam**.', 'I can''t **put up with** this much noise anymore.', 'Jag kan inte längre **stå ut med** det här bullret.', 'Ich kann diesen Lärm nicht mehr **ertragen**.', '["katlanamam"]', '["put up with"]', '["stå ut med"]', '["ertragen"]', 'advanced', false, 82),
(3, 'Bu uygulama bir gecede **büyük ilgi gördü**.', 'This app **took off** overnight.', 'Den här appen **sköt i höjden** över en natt.', 'Diese App ist über Nacht **durchgestartet**.', '["büyük ilgi gördü"]', '["took off"]', '["sköt i höjden"]', '["durchgestartet"]', 'advanced', false, 83),
(3, 'Yolculukta **dikkat et**, yollar kaygan.', '**Look out for** icy roads on the way.', '**Håll utkik efter** isiga vägar på vägen.', 'Achte auf dem Weg auf **glatte Straßen**.', '["dikkat et"]', '["look out for"]', '["håll utkik efter"]', '["achte auf"]', 'advanced', false, 84),
(3, 'Bu hikayeyi **uydurduğunu** düşünüyorum.', 'I think you **made up** this story.', 'Jag tror att du **hittade på** den här historien.', 'Ich glaube, du hast diese Geschichte **erfunden**.', '["uydurduğunu"]', '["made up"]', '["hittade på"]', '["erfunden"]', 'advanced', false, 85),
(3, 'Sunum sırasında yorgunluktan **bayıldı**.', 'He **passed out** from exhaustion during the presentation.', 'Han **svimmade** av utmattning under presentationen.', 'Er ist während der Präsentation vor Erschöpfung **ohnmächtig geworden**.', '["bayıldı"]', '["passed out"]', '["svimmade"]', '["ohnmächtig geworden"]', 'advanced', false, 86),
(3, 'Beklenmedik bir misafir **çıkageldi**.', 'An unexpected guest **turned up**.', 'En oväntad gäst **dök upp**.', 'Ein unerwarteter Gast **tauchte auf**.', '["çıkageldi"]', '["turned up"]', '["dök upp"]', '["tauchte auf"]', 'advanced', false, 87),
(3, 'Duygularını **içine attı**, hiçbir şey söylemedi.', 'He **held back** his emotions and said nothing.', 'Han **höll tillbaka** sina känslor och sa ingenting.', 'Er **unterdrückte** seine Gefühle und sagte nichts.', '["içine attı"]', '["held back"]', '["höll tillbaka"]', '["unterdrückte"]', 'advanced', false, 88),
(3, 'Zorluklara rağmen devam etmeliyiz, **sürdürmeliyiz**.', 'Despite the difficulties, we must **carry on**.', 'Trots svårigheterna måste vi **fortsätta**.', 'Trotz der Schwierigkeiten müssen wir **weitermachen**.', '["sürdürmeliyiz"]', '["carry on"]', '["fortsätta"]', '["weitermachen"]', 'advanced', false, 89),
(3, 'Stres altında her şey **dağılmaya** başladı.', 'Under pressure everything started to **fall apart**.', 'Under press började allt **falla isär**.', 'Unter Druck begann alles **auseinanderzufallen**.', '["dağılmaya"]', '["fall apart"]', '["falla isär"]', '["auseinanderzufallen"]', 'advanced', false, 90);
