-- Seed sentences for categories 1-3 (90 sentences total)
-- Category 1: Günlük Konuşma (30 sentences, is_free: true)
-- Category 2: İş İngilizcesi (30 sentences, is_free: true)
-- Category 3: Phrasal Verbs (30 sentences, is_free: false)

-- Category 1: Beginner (10 sentences)
INSERT INTO sentences (category_id, text_tr, text_en, text_sv, text_de, keywords_tr, keywords_en, keywords_sv, keywords_de, difficulty, is_free, sort_order) VALUES
(1, 'Bugün hava #güzel#.', 'The weather is #nice# today.', 'Vädret är #fint# idag.', 'Das Wetter ist #schön# heute.', '["güzel", "nice", "fint", "schön"]', '["nice", "nice", "fint", "schön"]', '["fint", "nice", "fint", "schön"]', '["schön", "nice", "fint", "schön"]', 'beginner', true, 1),
(1, 'Ne yemek istersin?', 'What do you want to eat?', 'Vad vill du äta?', 'Was möchtest du essen?', '[]', '[]', '[]', '[]', 'beginner', true, 2),
(1, 'Saat kaç?', 'What time is it?', 'Vad är klockan?', 'Wie spät ist es?', '[]', '[]', '[]', '[]', 'beginner', true, 3),
(1, 'İyi geceler.', 'Good night.', 'Godnatt.', 'Gute Nacht.', '[]', '[]', '[]', '[]', 'beginner', true, 4),
(1, 'Teşekkür ederim.', 'Thank you.', 'Tack.', 'Danke.', '[]', '[]', '[]', '[]', 'beginner', true, 5),
(1, 'Özür dilerim.', 'I''m sorry.', 'Förlåt.', 'Entschuldigung.', '[]', '[]', '[]', '[]', 'beginner', true, 6),
(1, 'Nerede yaşıyorsun?', 'Where do you live?', 'Var bor du?', 'Wo wohnst du?', '[]', '[]', '[]', '[]', 'beginner', true, 7),
(1, 'Kaç yaşındasın?', 'How old are you?', 'Hur gammal är du?', 'Wie alt bist du?', '[]', '[]', '[]', '[]', 'beginner', true, 8),
(1, 'Ne yapıyorsun?', 'What are you doing?', 'Vad gör du?', 'Was machst du?', '[]', '[]', '[]', '[]', 'beginner', true, 9),
(1, 'Hoşça kal.', 'Goodbye.', 'Hejdå.', 'Auf Wiedersehen.', '[]', '[]', '[]', '[]', 'beginner', true, 10);

-- Category 1: Intermediate (10 sentences)
INSERT INTO sentences (category_id, text_tr, text_en, text_sv, text_de, keywords_tr, keywords_en, keywords_sv, keywords_de, difficulty, is_free, sort_order) VALUES
(1, 'Hava yağmurlu olduğu için dışarı çıkmadım.', 'I didn''t go out because it was raining.', 'Jag gick inte ut eftersom det regnade.', 'Ich bin nicht rausgegangen, weil es regnete.', '["çıkmadım", "go out", "gick inte ut", "rausgegangen"]', '["go out", "go out", "gick inte ut", "rausgegangen"]', '["gick inte ut", "go out", "gick inte ut", "rausgegangen"]', '["rausgegangen", "go out", "gick inte ut", "rausgegangen"]', 'intermediate', true, 11),
(1, 'Yemek yedikten sonra film izleyeceğim.', 'After eating, I''ll watch a movie.', 'Efter att ha ätit kommer jag att se en film.', 'Nach dem Essen werde ich einen Film schauen.', '["yemek yedikten sonra", "after eating", "efter att ha ätit", "nach dem essen"]', '["after eating", "after eating", "efter att ha ätit", "nach dem essen"]', '["efter att ha ätit", "after eating", "efter att ha ätit", "nach dem essen"]', '["nach dem essen", "after eating", "efter att ha ätit", "nach dem essen"]', 'intermediate', true, 12),
(1, 'Arkadaşımı gördüğümde çok mutlu oldum.', 'I was very happy when I saw my friend.', 'Jag blev mycket glad när jag såg min vän.', 'Ich war sehr glücklich, als ich meinen Freund sah.', '["çok mutlu oldum", "very happy", "mycket glad", "sehr glücklich"]', '["very happy", "very happy", "mycket glad", "sehr glücklich"]', '["mycket glad", "very happy", "mycket glad", "sehr glücklich"]', '["sehr glücklich", "very happy", "mycket glad", "sehr glücklich"]', 'intermediate', true, 13),
(1, 'Kitap okumayı seviyorum çünkü rahatlatıcı.', 'I like reading books because it''s relaxing.', 'Jag gillar att läsa böcker eftersom det är avslappnande.', 'Ich mag Bücher lesen, weil es entspannend ist.', '["rahatlatıcı", "relaxing", "avslappnande", "entspannend"]', '["relaxing", "relaxing", "avslappnande", "entspannend"]', '["avslappnande", "relaxing", "avslappnande", "entspannend"]', '["entspannend", "relaxing", "avslappnande", "entspannend"]', 'intermediate', true, 14),
(1, 'Pazara gidip sebze alacağım.', 'I''ll go to the market and buy vegetables.', 'Jag ska gå till marknaden och köpa grönsaker.', 'Ich werde zum Markt gehen und Gemüse kaufen.', '["sebze alacağım", "buy vegetables", "köpa grönsaker", "gemüse kaufen"]', '["buy vegetables", "buy vegetables", "köpa grönsaker", "gemüse kaufen"]', '["köpa grönsaker", "buy vegetables", "köpa grönsaker", "gemüse kaufen"]', '["gemüse kaufen", "buy vegetables", "köpa grönsaker", "gemüse kaufen"]', 'intermediate', true, 15),
(1, 'Telefonum şarj olduğu için konuşabiliriz.', 'We can talk because my phone is charged.', 'Vi kan prata eftersom min telefon är laddad.', 'Wir können reden, weil mein Telefon geladen ist.', '["şarj olduğu için", "charged", "laddad", "geladen"]', '["charged", "charged", "laddad", "geladen"]', '["laddad", "charged", "laddad", "geladen"]', '["geladen", "charged", "laddad", "geladen"]', 'intermediate', true, 16),
(1, 'Hava soğuk olduğu halde yürüyüş yaptım.', 'I went for a walk although it was cold.', 'Jag gick en promenad trots att det var kallt.', 'Ich bin spazieren gegangen, obwohl es kalt war.', '["yürüyüş yaptım", "went for a walk", "gick en promenad", "spazieren gegangen"]', '["went for a walk", "went for a walk", "gick en promenad", "spazieren gegangen"]', '["gick en promenad", "went for a walk", "gick en promenad", "spazieren gegangen"]', '["spazieren gegangen", "went for a walk", "gick en promenad", "spazieren gegangen"]', 'intermediate', true, 17),
(1, 'Kahve içmeden güne başlayamam.', 'I can''t start the day without drinking coffee.', 'Jag kan inte börja dagen utan att dricka kaffe.', 'Ich kann den Tag nicht beginnen, ohne Kaffee zu trinken.', '["kahve içmeden", "drinking coffee", "dricka kaffe", "kaffee zu trinken"]', '["drinking coffee", "drinking coffee", "dricka kaffe", "kaffee zu trinken"]', '["dricka kaffe", "drinking coffee", "dricka kaffe", "kaffee zu trinken"]', '["kaffee zu trinken", "drinking coffee", "dricka kaffe", "kaffee zu trinken"]', 'intermediate', true, 18),
(1, 'Arkadaşlarımı davet edip parti yapacağım.', 'I''ll invite my friends and have a party.', 'Jag ska bjuda in mina vänner och ha en fest.', 'Ich werde meine Freunde einladen und eine Party machen.', '["parti yapacağım", "have a party", "ha en fest", "party machen"]', '["have a party", "have a party", "ha en fest", "party machen"]', '["ha en fest", "have a party", "ha en fest", "party machen"]', '["party machen", "have a party", "ha en fest", "party machen"]', 'intermediate', true, 19),
(1, 'Müzik dinlerken çalışmayı tercih ederim.', 'I prefer to work while listening to music.', 'Jag föredrar att arbeta medan jag lyssnar på musik.', 'Ich bevorzuge es, zu arbeiten, während ich Musik höre.', '["müzik dinlerken", "listening to music", "lyssnar på musik", "musik höre"]', '["listening to music", "listening to music", "lyssnar på musik", "musik höre"]', '["lyssnar på musik", "listening to music", "lyssnar på musik", "musik höre"]', '["musik höre", "listening to music", "lyssnar på musik", "musik höre"]', 'intermediate', true, 20);

-- Category 1: Advanced (10 sentences)
INSERT INTO sentences (category_id, text_tr, text_en, text_sv, text_de, keywords_tr, keywords_en, keywords_sv, keywords_de, difficulty, is_free, sort_order) VALUES
(1, 'Zamanla her şey yoluna girer.', 'Everything will fall into place with time.', 'Med tiden faller allt på plats.', 'Mit der Zeit wird alles ins Lot kommen.', '["yoluna girer", "fall into place", "faller på plats", "ins lot kommen"]', '["fall into place", "fall into place", "faller på plats", "ins lot kommen"]', '["faller på plats", "fall into place", "faller på plats", "ins lot kommen"]', '["ins lot kommen", "fall into place", "faller på plats", "ins lot kommen"]', 'advanced', true, 21),
(1, 'Gözümden kaçmadı, fark ettim.', 'It didn''t escape my notice, I noticed.', 'Det undgick inte min uppmärksamhet, jag märkte.', 'Es ist mir nicht entgangen, ich habe es bemerkt.', '["gözümden kaçmadı", "escape my notice", "undgick inte", "entgangen"]', '["escape my notice", "escape my notice", "undgick inte", "entgangen"]', '["undgick inte", "escape my notice", "undgick inte", "entgangen"]', '["entgangen", "escape my notice", "undgick inte", "entgangen"]', 'advanced', true, 22),
(1, 'Sözünü tutacağına inanıyorum.', 'I believe you''ll keep your word.', 'Jag tror att du kommer att hålla ditt ord.', 'Ich glaube, du wirst dein Wort halten.', '["sözünü tutacağına", "keep your word", "hålla ditt ord", "wort halten"]', '["keep your word", "keep your word", "hålla ditt ord", "wort halten"]', '["hålla ditt ord", "keep your word", "hålla ditt ord", "wort halten"]', '["wort halten", "keep your word", "hålla ditt ord", "wort halten"]', 'advanced', true, 23),
(1, 'Başka bir deyişle, kısaca söylemek gerekirse.', 'In other words, to put it briefly.', 'Med andra ord, för att säga det kort.', 'Mit anderen Worten, um es kurz zu sagen.', '["başka bir deyişle", "in other words", "med andra ord", "mit anderen worten"]', '["in other words", "in other words", "med andra ord", "mit anderen worten"]', '["med andra ord", "in other words", "med andra ord", "mit anderen worten"]', '["mit anderen worten", "in other words", "med andra ord", "mit anderen worten"]', 'advanced', true, 24),
(1, 'Her şeyin bir sonu var.', 'Everything has an end.', 'Allt har ett slut.', 'Alles hat ein Ende.', '["bir sonu var", "has an end", "har ett slut", "ein ende"]', '["has an end", "has an end", "har ett slut", "ein ende"]', '["har ett slut", "has an end", "har ett slut", "ein ende"]', '["ein ende", "has an end", "har ett slut", "ein ende"]', 'advanced', true, 25),
(1, 'Hayat kısa, fırsatları kaçırma.', 'Life is short, don''t miss opportunities.', 'Livet är kort, missa inte chanserna.', 'Das Leben ist kurz, verpasse keine Chancen.', '["fırsatları kaçırma", "miss opportunities", "missa inte chanserna", "verpasse keine chancen"]', '["miss opportunities", "miss opportunities", "missa inte chanserna", "verpasse keine chancen"]', '["missa inte chanserna", "miss opportunities", "missa inte chanserna", "verpasse keine chancen"]', '["verpasse keine chancen", "miss opportunities", "missa inte chanserna", "verpasse keine chancen"]', 'advanced', true, 26),
(1, 'Deneyimle öğrenilir.', 'You learn from experience.', 'Man lär sig genom erfarenhet.', 'Man lernt durch Erfahrung.', '["deneyimle öğrenilir", "learn from experience", "genom erfarenhet", "durch erfahrung"]', '["learn from experience", "learn from experience", "genom erfarenhet", "durch erfahrung"]', '["genom erfarenhet", "learn from experience", "genom erfarenhet", "durch erfahrung"]', '["durch erfahrung", "learn from experience", "genom erfarenhet", "durch erfahrung"]', 'advanced', true, 27),
(1, 'Sabır taşı deler.', 'Patience wears down the stone.', 'Tålamod bär sten.', 'Geduld bricht den Stein.', '["sabır taşı deler", "patience wears down", "tålamod bär", "geduld bricht"]', '["patience wears down", "patience wears down", "tålamod bär", "geduld bricht"]', '["tålamod bär", "patience wears down", "tålamod bär", "geduld bricht"]', '["geduld bricht", "patience wears down", "tålamod bär", "geduld bricht"]', 'advanced', true, 28),
(1, 'Bir taşla iki kuş vurmak.', 'To kill two birds with one stone.', 'Att slå två flugor i en smäll.', 'Zwei Fliegen mit einer Klappe schlagen.', '["iki kuş vurmak", "two birds with one stone", "två flugor i en smäll", "zwei fliegen mit einer klappe"]', '["two birds with one stone", "two birds with one stone", "två flugor i en smäll", "zwei fliegen mit einer klappe"]', '["två flugor i en smäll", "two birds with one stone", "två flugor i en smäll", "zwei fliegen mit einer klappe"]', '["zwei fliegen mit einer klappe", "two birds with one stone", "två flugor i en smäll", "zwei fliegen mit einer klappe"]', 'advanced', true, 29),
(1, 'Zaman akıp gidiyor.', 'Time is passing by.', 'Tiden går.', 'Die Zeit vergeht.', '["akıp gidiyor", "passing by", "går", "vergeht"]', '["passing by", "passing by", "går", "vergeht"]', '["går", "passing by", "går", "vergeht"]', '["vergeht", "passing by", "går", "vergeht"]', 'advanced', true, 30);

-- Category 2: Beginner (10 sentences)
INSERT INTO sentences (category_id, text_tr, text_en, text_sv, text_de, keywords_tr, keywords_en, keywords_sv, keywords_de, difficulty, is_free, sort_order) VALUES
(2, 'Toplantı saat kaçta?', 'What time is the meeting?', 'Vad är klockan för mötet?', 'Wann ist das Meeting?', '[]', '[]', '[]', '[]', 'beginner', true, 31),
(2, 'Email gönderdim.', 'I sent an email.', 'Jag skickade ett mejl.', 'Ich habe eine E-Mail gesendet.', '[]', '[]', '[]', '[]', 'beginner', true, 32),
(2, 'Proje tamamlandı.', 'The project is completed.', 'Projektet är klart.', 'Das Projekt ist abgeschlossen.', '[]', '[]', '[]', '[]', 'beginner', true, 33),
(2, 'Deadline ne zaman?', 'When is the deadline?', 'När är deadline?', 'Wann ist die Deadline?', '[]', '[]', '[]', '[]', 'beginner', true, 34),
(2, 'Sunum yapacağım.', 'I''ll give a presentation.', 'Jag ska hålla en presentation.', 'Ich werde eine Präsentation halten.', '[]', '[]', '[]', '[]', 'beginner', true, 35),
(2, 'Müşteri memnun.', 'The customer is satisfied.', 'Kunden är nöjd.', 'Der Kunde ist zufrieden.', '[]', '[]', '[]', '[]', 'beginner', true, 36),
(2, 'Rapor hazırladım.', 'I prepared the report.', 'Jag förberedde rapporten.', 'Ich habe den Bericht vorbereitet.', '[]', '[]', '[]', '[]', 'beginner', true, 37),
(2, 'Ofis saatleri ne?', 'What are the office hours?', 'Vad är kontorstiderna?', 'Was sind die Bürozeiten?', '[]', '[]', '[]', '[]', 'beginner', true, 38),
(2, 'İş görüşmesi var.', 'There is a job interview.', 'Det finns en jobbintervju.', 'Es gibt ein Vorstellungsgespräch.', '[]', '[]', '[]', '[]', 'beginner', true, 39),
(2, 'Takım çalışması.', 'Teamwork.', 'Lagarbete.', 'Teamarbeit.', '[]', '[]', '[]', '[]', 'beginner', true, 40);

-- Category 2: Intermediate (10 sentences)
INSERT INTO sentences (category_id, text_tr, text_en, text_sv, text_de, keywords_tr, keywords_en, keywords_sv, keywords_de, difficulty, is_free, sort_order) VALUES
(2, 'Toplantıyı ertelememiz gerekebilir.', 'We might need to postpone the meeting.', 'Vi kan behöva skjuta upp mötet.', 'Wir müssen das Meeting möglicherweise verschieben.', '["ertelememiz gerekebilir", "postpone the meeting", "skjuta upp mötet", "meeting verschieben"]', '["postpone the meeting", "postpone the meeting", "skjuta upp mötet", "meeting verschieben"]', '["skjuta upp mötet", "postpone the meeting", "skjuta upp mötet", "meeting verschieben"]', '["meeting verschieben", "postpone the meeting", "skjuta upp mötet", "meeting verschieben"]', 'intermediate', true, 41),
(2, 'Bütçe onaylandı.', 'The budget is approved.', 'Budgeten är godkänd.', 'Das Budget ist genehmigt.', '["onaylandı", "approved", "godkänd", "genehmigt"]', '["approved", "approved", "godkänd", "genehmigt"]', '["godkänd", "approved", "godkänd", "genehmigt"]', '["genehmigt", "approved", "godkänd", "genehmigt"]', 'intermediate', true, 42),
(2, 'Yeni strateji geliştireceğiz.', 'We''ll develop a new strategy.', 'Vi kommer att utveckla en ny strategi.', 'Wir werden eine neue Strategie entwickeln.', '["strateji geliştireceğiz", "develop a new strategy", "utveckla en ny strategi", "strategie entwickeln"]', '["develop a new strategy", "develop a new strategy", "utveckla en ny strategi", "strategie entwickeln"]', '["utveckla en ny strategi", "develop a new strategy", "utveckla en ny strategi", "strategie entwickeln"]', '["strategie entwickeln", "develop a new strategy", "utveckla en ny strategi", "strategie entwickeln"]', 'intermediate', true, 43),
(2, 'Müşteri geri bildirim verdi.', 'The customer gave feedback.', 'Kunden gav feedback.', 'Der Kunde hat Feedback gegeben.', '["geri bildirim verdi", "gave feedback", "gav feedback", "feedback gegeben"]', '["gave feedback", "gave feedback", "gav feedback", "feedback gegeben"]', '["gav feedback", "gave feedback", "gav feedback", "feedback gegeben"]', '["feedback gegeben", "gave feedback", "gav feedback", "feedback gegeben"]', 'intermediate', true, 44),
(2, 'Proje planı hazır.', 'The project plan is ready.', 'Projektplanen är klar.', 'Der Projektplan ist bereit.', '["hazır", "ready", "klar", "bereit"]', '["ready", "ready", "klar", "bereit"]', '["klar", "ready", "klar", "bereit"]', '["bereit", "ready", "klar", "bereit"]', 'intermediate', true, 45),
(2, 'Eğitim programı başlatıldı.', 'The training program is launched.', 'Utbildningsprogrammet är lanserat.', 'Das Schulungsprogramm ist gestartet.', '["başlatıldı", "launched", "lanserat", "gestartet"]', '["launched", "launched", "lanserat", "gestartet"]', '["lanserat", "launched", "lanserat", "gestartet"]', '["gestartet", "launched", "lanserat", "gestartet"]', 'intermediate', true, 46),
(2, 'Satış hedefi aşıldı.', 'The sales target is exceeded.', 'Försäljningsmålet är överskridet.', 'Das Verkaufsziel ist überschritten.', '["aşıldı", "exceeded", "överskridet", "überschritten"]', '["exceeded", "exceeded", "överskridet", "überschritten"]', '["överskridet", "exceeded", "överskridet", "überschritten"]', '["überschritten", "exceeded", "överskridet", "überschritten"]', 'intermediate', true, 47),
(2, 'İş akışı optimize edildi.', 'The workflow is optimized.', 'Arbetsflödet är optimerat.', 'Der Arbeitsablauf ist optimiert.', '["optimize edildi", "optimized", "optimerat", "optimiert"]', '["optimized", "optimized", "optimerat", "optimiert"]', '["optimerat", "optimized", "optimerat", "optimiert"]', '["optimiert", "optimized", "optimerat", "optimiert"]', 'intermediate', true, 48),
(2, 'Yeni yazılım yüklendi.', 'New software is installed.', 'Ny programvara är installerad.', 'Neue Software ist installiert.', '["yüklendi", "installed", "installerad", "installiert"]', '["installed", "installed", "installerad", "installiert"]', '["installerad", "installed", "installerad", "installiert"]', '["installiert", "installed", "installerad", "installiert"]', 'intermediate', true, 49),
(2, 'Takım toplantısı yapıldı.', 'Team meeting was held.', 'Lagmöte hölls.', 'Teammeeting wurde abgehalten.', '["yapıldı", "held", "hölls", "abgehalten"]', '["held", "held", "hölls", "abgehalten"]', '["hölls", "held", "hölls", "abgehalten"]', '["abgehalten", "held", "hölls", "abgehalten"]', 'intermediate', true, 50);

-- Category 2: Advanced (10 sentences)
INSERT INTO sentences (category_id, text_tr, text_en, text_sv, text_de, keywords_tr, keywords_en, keywords_sv, keywords_de, difficulty, is_free, sort_order) VALUES
(2, 'Stratejik ortaklık kurduk.', 'We established a strategic partnership.', 'Vi etablerade ett strategiskt partnerskap.', 'Wir haben eine strategische Partnerschaft etabliert.', '["stratejik ortaklık kurduk", "strategic partnership", "strategiskt partnerskap", "strategische partnerschaft"]', '["strategic partnership", "strategic partnership", "strategiskt partnerskap", "strategische partnerschaft"]', '["strategiskt partnerskap", "strategic partnership", "strategiskt partnerskap", "strategische partnerschaft"]', '["strategische partnerschaft", "strategic partnership", "strategiskt partnerskap", "strategische partnerschaft"]', 'advanced', true, 51),
(2, 'Piyasa analizi yapıldı.', 'Market analysis was conducted.', 'Marknadsanalys genomfördes.', 'Marktanalyse wurde durchgeführt.', '["piyasa analizi yapıldı", "market analysis", "marknadsanalys", "marktanalyse"]', '["market analysis", "market analysis", "marknadsanalys", "marktanalyse"]', '["marknadsanalys", "market analysis", "marknadsanalys", "marktanalyse"]', '["marktanalyse", "market analysis", "marknadsanalys", "marktanalyse"]', 'advanced', true, 52),
(2, 'Kurumsal sosyal sorumluluk projesi başlatıldı.', 'Corporate social responsibility project is launched.', 'Projekt för företags samhällsansvar lanserades.', 'Projekt für unternehmerische soziale Verantwortung gestartet.', '["kurumsal sosyal sorumluluk", "corporate social responsibility", "företags samhällsansvar", "unternehmerische soziale verantwortung"]', '["corporate social responsibility", "corporate social responsibility", "företags samhällsansvar", "unternehmerische soziale verantwortung"]', '["företags samhällsansvar", "corporate social responsibility", "företags samhällsansvar", "unternehmerische soziale verantwortung"]', '["unternehmerische soziale verantwortung", "corporate social responsibility", "företags samhällsansvar", "unternehmerische soziale verantwortung"]', 'advanced', true, 53),
(2, 'Finansal rapor yayınlandı.', 'Financial report is published.', 'Finansiell rapport publicerades.', 'Finanzbericht wurde veröffentlicht.', '["finansal rapor yayınlandı", "financial report", "finansiell rapport", "finanzbericht"]', '["financial report", "financial report", "finansiell rapport", "finanzbericht"]', '["finansiell rapport", "financial report", "finansiell rapport", "finanzbericht"]', '["finanzbericht", "financial report", "finansiell rapport", "finanzbericht"]', 'advanced', true, 54),
(2, 'Yönetim kurulu kararı alındı.', 'Board decision is made.', 'Styrelsebeslut fattades.', 'Vorstandsentscheidung wurde getroffen.', '["yönetim kurulu kararı", "board decision", "styrelsebeslut", "vorstandsentscheidung"]', '["board decision", "board decision", "styrelsebeslut", "vorstandsentscheidung"]', '["styrelsebeslut", "board decision", "styrelsebeslut", "vorstandsentscheidung"]', '["vorstandsentscheidung", "board decision", "styrelsebeslut", "vorstandsentscheidung"]', 'advanced', true, 55),
(2, 'İş geliştirme departmanı kuruldu.', 'Business development department is established.', 'Affärsutvecklingsavdelning etablerades.', 'Geschäftsentwicklungsabteilung wurde gegründet.', '["iş geliştirme departmanı", "business development department", "affärsutvecklingsavdelning", "geschäftsentwicklungsabteilung"]', '["business development department", "business development department", "affärsutvecklingsavdelning", "geschäftsentwicklungsabteilung"]', '["affärsutvecklingsavdelning", "business development department", "affärsutvecklingsavdelning", "geschäftsentwicklungsabteilung"]', '["geschäftsentwicklungsabteilung", "business development department", "affärsutvecklingsavdelning", "geschäftsentwicklungsabteilung"]', 'advanced', true, 56),
(2, 'Risk yönetimi protokolü güncellendi.', 'Risk management protocol is updated.', 'Riskhanteringsprotokoll uppdaterades.', 'Risikomanagementprotokoll wurde aktualisiert.', '["risk yönetimi protokolü", "risk management protocol", "riskhanteringsprotokoll", "risikomanagementprotokoll"]', '["risk management protocol", "risk management protocol", "riskhanteringsprotokoll", "risikomanagementprotokoll"]', '["riskhanteringsprotokoll", "risk management protocol", "riskhanteringsprotokoll", "risikomanagementprotokoll"]', '["risikomanagementprotokoll", "risk management protocol", "riskhanteringsprotokoll", "risikomanagementprotokoll"]', 'advanced', true, 57),
(2, 'Müşteri memnuniyet anketi yapıldı.', 'Customer satisfaction survey was conducted.', 'Kundnöjdhetsundersökning genomfördes.', 'Kundenzufriedenheitsumfrage wurde durchgeführt.', '["müşteri memnuniyet anketi", "customer satisfaction survey", "kundnöjdhetsundersökning", "kundenzufriedenheitsumfrage"]', '["customer satisfaction survey", "customer satisfaction survey", "kundnöjdhetsundersökning", "kundenzufriedenheitsumfrage"]', '["kundnöjdhetsundersökning", "customer satisfaction survey", "kundnöjdhetsundersökning", "kundenzufriedenheitsumfrage"]', '["kundenzufriedenheitsumfrage", "customer satisfaction survey", "kundnöjdhetsundersökning", "kundenzufriedenheitsumfrage"]', 'advanced', true, 58),
(2, 'Performans değerlendirmesi tamamlandı.', 'Performance evaluation is completed.', 'Prestationsutvärdering slutfördes.', 'Leistungsbeurteilung wurde abgeschlossen.', '["performans değerlendirmesi", "performance evaluation", "prestationsutvärdering", "leistungsbeurteilung"]', '["performance evaluation", "performance evaluation", "prestationsutvärdering", "leistungsbeurteilung"]', '["prestationsutvärdering", "performance evaluation", "prestationsutvärdering", "leistungsbeurteilung"]', '["leistungsbeurteilung", "performance evaluation", "prestationsutvärdering", "leistungsbeurteilung"]', 'advanced', true, 59),
(2, 'Kalite kontrol sistemi uygulandı.', 'Quality control system is implemented.', 'Kvalitetskontrollsystem infördes.', 'Qualitätskontrollsystem wurde implementiert.', '["kalite kontrol sistemi", "quality control system", "kvalitetskontrollsystem", "qualitätskontrollsystem"]', '["quality control system", "quality control system", "kvalitetskontrollsystem", "qualitätskontrollsystem"]', '["kvalitetskontrollsystem", "quality control system", "kvalitetskontrollsystem", "qualitätskontrollsystem"]', '["qualitätskontrollsystem", "quality control system", "kvalitetskontrollsystem", "qualitätskontrollsystem"]', 'advanced', true, 60);

-- Category 3: Beginner (10 sentences)
INSERT INTO sentences (category_id, text_tr, text_en, text_sv, text_de, keywords_tr, keywords_en, keywords_sv, keywords_de, difficulty, is_free, sort_order) VALUES
(3, 'Kelimeyi *araştır*.', '*Look up* the word.', '*Slå upp* ordet.', '*Nachschlagen* das Wort.', '["araştır", "look up", "slå upp", "nachschlagen"]', '["look up", "look up", "slå upp", "nachschlagen"]', '["slå upp", "look up", "slå upp", "nachschlagen"]', '["nachschlagen", "look up", "slå upp", "nachschlagen"]', 'beginner', false, 61),
(3, 'Sigarayı *bırak*.', '*Give up* smoking.', '*Sluta* röka.', '*Aufgeben* rauchen.', '["bırak", "give up", "sluta", "aufgeben"]', '["give up", "give up", "sluta", "aufgeben"]', '["sluta", "give up", "sluta", "aufgeben"]', '["aufgeben", "give up", "sluta", "aufgeben"]', 'beginner', false, 62),
(3, 'Işığı *aç*.', '*Turn on* the light.', '*Slå på* ljuset.', '*Einschalten* das Licht.', '["aç", "turn on", "slå på", "einschalten"]', '["turn on", "turn on", "slå på", "einschalten"]', '["slå på", "turn on", "slå på", "einschalten"]', '["einschalten", "turn on", "slå på", "einschalten"]', 'beginner', false, 63),
(3, 'TV''yi *kapat*.', '*Turn off* the TV.', '*Slå av* TV:n.', '*Ausschalten* den Fernseher.', '["kapat", "turn off", "slå av", "ausschalten"]', '["turn off", "turn off", "slå av", "ausschalten"]', '["slå av", "turn off", "slå av", "ausschalten"]', '["ausschalten", "turn off", "slå av", "ausschalten"]', 'beginner', false, 64),
(3, 'Erken *uyan*.', '*Wake up* early.', '*Vakna* tidigt.', '*Aufwachen* früh.', '["uyan", "wake up", "vakna", "aufwachen"]', '["wake up", "wake up", "vakna", "aufwachen"]', '["vakna", "wake up", "vakna", "aufwachen"]', '["aufwachen", "wake up", "vakna", "aufwachen"]', 'beginner', false, 65),
(3, 'Yataktan *kalk*.', '*Get up* from bed.', '*Stig upp* från sängen.', '*Aufstehen* vom Bett.', '["kalk", "get up", "stig upp", "aufstehen"]', '["get up", "get up", "stig upp", "aufstehen"]', '["stig upp", "get up", "stig upp", "aufstehen"]', '["aufstehen", "get up", "stig upp", "aufstehen"]', 'beginner', false, 66),
(3, 'Lütfen *otur*.', '*Sit down* please.', '*Sätt dig* snälla.', '*Setz dich* bitte.', '["otur", "sit down", "sätt dig", "setz dich"]', '["sit down", "sit down", "sätt dig", "setz dich"]', '["sätt dig", "sit down", "sätt dig", "setz dich"]', '["setz dich", "sit down", "sätt dig", "setz dich"]', 'beginner', false, 67),
(3, 'Yavaşça *ayağa kalk*.', '*Stand up* slowly.', '*Stå upp* långsamt.', '*Aufstehen* langsam.', '["ayağa kalk", "stand up", "stå upp", "aufstehen"]', '["stand up", "stand up", "stå upp", "aufstehen"]', '["stå upp", "stand up", "stå upp", "aufstehen"]', '["aufstehen", "stand up", "stå upp", "aufstehen"]', 'beginner', false, 68),
(3, '*Gir*.', '*Come in*.', '*Kom in*.', '*Herein kommen*.', '["gir", "come in", "kom in", "herein kommen"]', '["come in", "come in", "kom in", "herein kommen"]', '["kom in", "come in", "kom in", "herein kommen"]', '["herein kommen", "come in", "kom in", "herein kommen"]', 'beginner', false, 69),
(3, 'Akşam yemeği için *çık*.', '*Go out* for dinner.', '*Gå ut* för middag.', '*Ausgehen* zum Abendessen.', '["çık", "go out", "gå ut", "ausgehen"]', '["go out", "go out", "gå ut", "ausgehen"]', '["gå ut", "go out", "gå ut", "ausgehen"]', '["ausgehen", "go out", "gå ut", "ausgehen"]', 'beginner', false, 70);

-- Category 3: Intermediate (10 sentences)
INSERT INTO sentences (category_id, text_tr, text_en, text_sv, text_de, keywords_tr, keywords_en, keywords_sv, keywords_de, difficulty, is_free, sort_order) VALUES
(3, 'Eski bir arkadaşa *rastla*.', '*Come across* an old friend.', '*Stöta på* en gammal vän.', '*Treffen* einen alten Freund.', '["rastla", "come across", "stöta på", "treffen"]', '["come across", "come across", "stöta på", "treffen"]', '["stöta på", "come across", "stöta på", "treffen"]', '["treffen", "come across", "stöta på", "treffen"]', 'intermediate', false, 71),
(3, 'Toplantıyı *erte*.', '*Put off* the meeting.', '*Skjuta upp* mötet.', '*Verschieben* das Meeting.', '["erte", "put off", "skjuta upp", "verschieben"]', '["put off", "put off", "skjuta upp", "verschieben"]', '["skjuta upp", "put off", "skjuta upp", "verschieben"]', '["verschieben", "put off", "skjuta upp", "verschieben"]', 'intermediate', false, 72),
(3, 'Çalışmaya *devam et*.', '*Carry on* working.', '*Fortsätta* arbeta.', '*Weitermachen* arbeiten.', '["devam et", "carry on", "fortsätta", "weitermachen"]', '["carry on", "carry on", "fortsätta", "weitermachen"]', '["fortsätta", "carry on", "fortsätta", "weitermachen"]', '["weitermachen", "carry on", "fortsätta", "weitermachen"]', 'intermediate', false, 73),
(3, 'Araba *bozul*.', 'The car *broke down*.', 'Bilen *gick sönder*.', 'Das Auto *ging kaputt*.', '["bozul", "broke down", "gick sönder", "ging kaputt"]', '["broke down", "broke down", "gick sönder", "ging kaputt"]', '["gick sönder", "broke down", "gick sönder", "ging kaputt"]', '["ging kaputt", "broke down", "gick sönder", "ging kaputt"]', 'intermediate', false, 74),
(3, 'Şirketi *devral*.', '*Take over* the company.', '*Ta över* företaget.', '*Übernehmen* das Unternehmen.', '["devral", "take over", "ta över", "übernehmen"]', '["take over", "take over", "ta över", "übernehmen"]', '["ta över", "take over", "ta över", "übernehmen"]', '["übernehmen", "take over", "ta över", "übernehmen"]', 'intermediate', false, 75),
(3, 'Konuyu *ortaya çıkar*.', '*Bring up* the topic.', '*Ta upp* ämnet.', '*Ansprechen* das Thema.', '["ortaya çıkar", "bring up", "ta upp", "ansprechen"]', '["bring up", "bring up", "ta upp", "ansprechen"]', '["ta upp", "bring up", "ta upp", "ansprechen"]', '["ansprechen", "bring up", "ta upp", "ansprechen"]', 'intermediate', false, 76),
(3, 'Çocuklara *bak*.', '*Look after* the kids.', '*Ta hand om* barnen.', '*Aufpassen* auf die Kinder.', '["bak", "look after", "ta hand om", "aufpassen"]', '["look after", "look after", "ta hand om", "aufpassen"]', '["ta hand om", "look after", "ta hand om", "aufpassen"]', '["aufpassen", "look after", "ta hand om", "aufpassen"]', 'intermediate', false, 77),
(3, 'İş arkadaşlarıyla *anlaş*.', '*Get along* with colleagues.', '*Kom överens* med kollegor.', '*Auskommen* mit Kollegen.', '["anlaş", "get along", "kom överens", "auskommen"]', '["get along", "get along", "kom överens", "auskommen"]', '["kom överens", "get along", "kom överens", "auskommen"]', '["auskommen", "get along", "kom överens", "auskommen"]', 'intermediate', false, 78),
(3, 'Zaman *tüken*.', '*Run out* of time.', '*Ta slut* på tid.', '*Ausgehen* an Zeit.', '["tüken", "run out", "ta slut", "ausgehen"]', '["run out", "run out", "ta slut", "ausgehen"]', '["ta slut", "run out", "ta slut", "ausgehen"]', '["ausgehen", "run out", "ta slut", "ausgehen"]', 'intermediate', false, 79),
(3, 'Etkinliği *bekle*.', '*Look forward* to the event.', '*Se fram emot* evenemanget.', '*Sich freuen* auf die Veranstaltung.', '["bekle", "look forward", "se fram emot", "sich freuen"]', '["look forward", "look forward", "se fram emot", "sich freuen"]', '["se fram emot", "look forward", "se fram emot", "sich freuen"]', '["sich freuen", "look forward", "se fram emot", "sich freuen"]', 'intermediate', false, 80);

-- Category 3: Advanced (10 sentences)
INSERT INTO sentences (category_id, text_tr, text_en, text_sv, text_de, keywords_tr, keywords_en, keywords_sv, keywords_de, difficulty, is_free, sort_order) VALUES
(3, 'Bununla *kaç*.', '*Get away* with it.', '*Kom undan* med det.', '*Davonkommen* damit.', '["kaç", "get away", "kom undan", "davonkommen"]', '["get away", "get away", "kom undan", "davonkommen"]', '["kom undan", "get away", "kom undan", "davonkommen"]', '["davonkommen", "get away", "kom undan", "davonkommen"]', 'advanced', false, 81),
(3, 'Gürültüye *katlan*.', '*Put up* with the noise.', '*Tåla* bullret.', '*Ertragen* den Lärm.', '["katlan", "put up", "tåla", "ertragen"]', '["put up", "put up", "tåla", "ertragen"]', '["tåla", "put up", "tåla", "ertragen"]', '["ertragen", "put up", "tåla", "ertragen"]', 'advanced', false, 82),
(3, 'Bir fikir *bul*.', '*Come up* with an idea.', '*Kom på* en idé.', '*Kommen* auf eine Idee.', '["bul", "come up", "kom på", "kommen"]', '["come up", "come up", "kom på", "kommen"]', '["kom på", "come up", "kom på", "kommen"]', '["kommen", "come up", "kom på", "kommen"]', 'advanced', false, 83),
(3, 'Eve *gir*.', '*Break into* the house.', '*Bryta sig in* i huset.', '*Einbrechen* in das Haus.', '["gir", "break into", "bryta sig in", "einbrechen"]', '["break into", "break into", "bryta sig in", "einbrechen"]', '["bryta sig in", "break into", "bryta sig in", "einbrechen"]', '["einbrechen", "break into", "bryta sig in", "einbrechen"]', 'advanced', false, 84),
(3, 'Çok fazla iş *üstlen*.', '*Take on* too much work.', '*Ta på sig* för mycket arbete.', '*Übernehmen* zu viel Arbeit.', '["üstlen", "take on", "ta på sig", "übernehmen"]', '["take on", "take on", "ta på sig", "übernehmen"]', '["ta på sig", "take on", "ta på sig", "übernehmen"]', '["übernehmen", "take on", "ta på sig", "übernehmen"]', 'advanced', false, 85),
(3, 'Değişiklik *getir*.', '*Bring about* change.', '*Medföra* förändring.', '*Bewirken* Veränderung.', '["getir", "bring about", "medföra", "bewirken"]', '["bring about", "bring about", "medföra", "bewirken"]', '["medföra", "bring about", "medföra", "bewirken"]', '["bewirken", "bring about", "medföra", "bewirken"]', 'advanced', false, 86),
(3, 'Başkalarına *bak*.', '*Look down* on others.', '*Se ner på* andra.', '*Herabsehen* auf andere.', '["bak", "look down", "se ner på", "herabsehen"]', '["look down", "look down", "se ner på", "herabsehen"]', '["se ner på", "look down", "se ner på", "herabsehen"]', '["herabsehen", "look down", "se ner på", "herabsehen"]', 'advanced', false, 87),
(3, 'Az para ile *idare et*.', '*Get by* on little money.', '*Klara sig* på lite pengar.', '*Auskommen* mit wenig Geld.', '["idare et", "get by", "klara sig", "auskommen"]', '["get by", "get by", "klara sig", "auskommen"]', '["klara sig", "get by", "klara sig", "auskommen"]', '["auskommen", "get by", "klara sig", "auskommen"]', 'advanced', false, 88),
(3, 'Teklifi *reddet*.', '*Turn down* the offer.', '*Avvisa* erbjudandet.', '*Ablehnen* das Angebot.', '["reddet", "turn down", "avvisa", "ablehnen"]', '["turn down", "turn down", "avvisa", "ablehnen"]', '["avvisa", "turn down", "avvisa", "ablehnen"]', '["ablehnen", "turn down", "avvisa", "ablehnen"]', 'advanced', false, 89),
(3, 'Konuyu *değiştir*.', '*Change* the subject.', '*Byta* ämne.', '*Wechseln* das Thema.', '["değiştir", "change", "byta", "wechseln"]', '["change", "change", "byta", "wechseln"]', '["byta", "change", "byta", "wechseln"]', '["wechseln", "change", "byta", "wechseln"]', 'advanced', false, 90);