-- Seed sentences for categories 4-7 (120 sentences total)
-- Category 4: Seyahat (30 sentences, is_free: false)
-- Category 5: Akademik (30 sentences, is_free: false)
-- Category 6: İdiomlar (30 sentences, is_free: false)
-- Category 7: Gramer Kalıpları (30 sentences, is_free: false)

-- Category 4: Beginner (10 sentences)
INSERT INTO sentences (category_id, text_tr, text_en, text_sv, text_de, keywords_tr, keywords_en, keywords_sv, keywords_de, difficulty, is_free, sort_order) VALUES
(4, 'Havaalanı nerede?', 'Where is the airport?', 'Var är flygplatsen?', 'Wo ist der Flughafen?', '[]', '[]', '[]', '[]', 'beginner', false, 91),
(4, 'Biletimi almak istiyorum.', 'I want to buy my ticket.', 'Jag vill köpa min biljett.', 'Ich möchte meine Karte kaufen.', '[]', '[]', '[]', '[]', 'beginner', false, 92),
(4, 'Bagajımı kaybettim.', 'I lost my luggage.', 'Jag tappade bort mitt bagage.', 'Ich habe mein Gepäck verloren.', '[]', '[]', '[]', '[]', 'beginner', false, 93),
(4, 'Otel rezervasyonu yaptım.', 'I made a hotel reservation.', 'Jag bokade ett hotellrum.', 'Ich habe eine Hotelreservierung gemacht.', '[]', '[]', '[]', '[]', 'beginner', false, 94),
(4, 'Taksi çağırın.', 'Call a taxi.', 'Kalla på en taxi.', 'Rufen Sie ein Taxi.', '[]', '[]', '[]', '[]', 'beginner', false, 95),
(4, 'Tren saat kaçta kalkar?', 'What time does the train leave?', 'Vad tid avgår tåget?', 'Wann fährt der Zug ab?', '[]', '[]', '[]', '[]', 'beginner', false, 96),
(4, 'Pasaportumu gösterdim.', 'I showed my passport.', 'Jag visade mitt pass.', 'Ich habe meinen Pass gezeigt.', '[]', '[]', '[]', '[]', 'beginner', false, 97),
(4, 'Vize başvurusu yaptım.', 'I applied for a visa.', 'Jag ansökte om visum.', 'Ich habe ein Visum beantragt.', '[]', '[]', '[]', '[]', 'beginner', false, 98),
(4, 'Turist bilgisi alın.', 'Get tourist information.', 'Få turistinformation.', 'Holen Sie sich Touristeninformationen.', '[]', '[]', '[]', '[]', 'beginner', false, 99),
(4, 'Harita gösterin.', 'Show me the map.', 'Visa mig kartan.', 'Zeigen Sie mir die Karte.', '[]', '[]', '[]', '[]', 'beginner', false, 100);

-- Category 4: Intermediate (10 sentences)
INSERT INTO sentences (category_id, text_tr, text_en, text_sv, text_de, keywords_tr, keywords_en, keywords_sv, keywords_de, difficulty, is_free, sort_order) VALUES
(4, '*Check-in* yapmak istiyorum.', 'I want to *check in*.', 'Jag vill *checka in*.', 'Ich möchte *einchecken*.', '["check-in", "check in", "checka in", "einchecken"]', '["check in", "check in", "checka in", "einchecken"]', '["checka in", "check in", "checka in", "einchecken"]', '["einchecken", "check in", "checka in", "einchecken"]', 'intermediate', false, 101),
(4, '*Boarding pass*''ımı kaybettim.', 'I lost my *boarding pass*.', 'Jag tappade bort mitt *boardingkort*.', 'Ich habe meine *Boardingkarte* verloren.', '["boarding pass", "boarding pass", "boardingkort", "boardingkarte"]', '["boarding pass", "boarding pass", "boardingkort", "boardingkarte"]', '["boardingkort", "boarding pass", "boardingkort", "boardingkarte"]', '["boardingkarte", "boarding pass", "boardingkort", "boardingkarte"]', 'intermediate', false, 102),
(4, '*One-way ticket* almak istiyorum.', 'I want to buy a *one-way ticket*.', 'Jag vill köpa en *enkelbiljett*.', 'Ich möchte eine *Einfachfahrkarte* kaufen.', '["one-way ticket", "one-way ticket", "enkelbiljett", "einfachfahrkarte"]', '["one-way ticket", "one-way ticket", "enkelbiljett", "einfachfahrkarte"]', '["enkelbiljett", "one-way ticket", "enkelbiljett", "einfachfahrkarte"]', '["einfachfahrkarte", "one-way ticket", "enkelbiljett", "einfachfahrkarte"]', 'intermediate', false, 103),
(4, 'Otel ne kadar uzak?', '*How far* is the hotel?', '*Hur långt* är hotellet?', '*Wie weit* ist das Hotel?', '["how far", "how far", "hur långt", "wie weit"]', '["how far", "how far", "hur långt", "wie weit"]', '["hur långt", "how far", "hur långt", "wie weit"]', '["wie weit", "how far", "hur långt", "wie weit"]', 'intermediate', false, 104),
(4, 'Restoran otelin yanında.', 'The restaurant is *next to* the hotel.', 'Restaurangen är *bredvid* hotellet.', 'Das Restaurant ist *neben* dem Hotel.', '["next to", "next to", "bredvid", "neben"]', '["next to", "next to", "bredvid", "neben"]', '["bredvid", "next to", "bredvid", "neben"]', '["neben", "next to", "bredvid", "neben"]', 'intermediate', false, 105),
(4, 'Köşede sola dön.', '*Turn left* *on the corner*.', '*Sväng vänster* *vid hörnet*.', '*Biegen Sie links* *an der Ecke* ab.', '["turn left", "turn left", "sväng vänster", "biegen sie links"]', '["turn left", "turn left", "sväng vänster", "biegen sie links"]', '["sväng vänster", "turn left", "sväng vänster", "biegen sie links"]', '["biegen sie links", "turn left", "sväng vänster", "biegen sie links"]', 'intermediate', false, 106),
(4, 'Para bozdurmam lazım.', 'I need to *change money*.', 'Jag behöver *växla pengar*.', 'Ich muss *Geld wechseln*.', '["change money", "change money", "växla pengar", "geld wechseln"]', '["change money", "change money", "växla pengar", "geld wechseln"]', '["växla pengar", "change money", "växla pengar", "geld wechseln"]', '["geld wechseln", "change money", "växla pengar", "geld wechseln"]', 'intermediate', false, 107),
(4, 'Uçuş gecikti.', 'The flight is *delayed*.', 'Flyget är *försenat*.', 'Der Flug ist *verspätet*.', '["delayed", "delayed", "försenat", "verspätet"]', '["delayed", "delayed", "försenat", "verspätet"]', '["försenat", "delayed", "försenat", "verspätet"]', '["verspätet", "delayed", "försenat", "verspätet"]', 'intermediate', false, 108),
(4, 'Bağlantılı uçuşum var.', 'I have a *connecting flight*.', 'Jag har ett *anslutningsflyg*.', 'Ich habe einen *Anschlussflug*.', '["connecting flight", "connecting flight", "anslutningsflyg", "anschlussflug"]', '["connecting flight", "connecting flight", "anslutningsflyg", "anschlussflug"]', '["anslutningsflyg", "connecting flight", "anslutningsflyg", "anschlussflug"]', '["anschlussflug", "connecting flight", "anslutningsflyg", "anschlussflug"]', 'intermediate', false, 109),
(4, 'Lütfen yavaş konuşun.', 'Please *speak slowly*.', 'Var vänlig *tala långsamt*.', 'Bitte *sprechen Sie langsam*.', '["speak slowly", "speak slowly", "tala långsamt", "sprechen sie langsam"]', '["speak slowly", "speak slowly", "tala långsamt", "sprechen sie langsam"]', '["tala långsamt", "speak slowly", "tala långsamt", "sprechen sie langsam"]', '["sprechen sie langsam", "speak slowly", "tala långsamt", "sprechen sie langsam"]', 'intermediate', false, 110);

-- Category 4: Advanced (10 sentences)
INSERT INTO sentences (category_id, text_tr, text_en, text_sv, text_de, keywords_tr, keywords_en, keywords_sv, keywords_de, difficulty, is_free, sort_order) VALUES
(4, 'Kayıp bagajım için şikayet başvurusu yapmam lazım.', 'I need to *file a claim* for my lost luggage.', 'Jag behöver *göra en reklamation* för mitt förlorade bagage.', 'Ich muss eine *Reklamation einreichen* für mein verlorenes Gepäck.', '["file a claim", "file a claim", "göra en reklamation", "reklamation einreichen"]', '["file a claim", "file a claim", "göra en reklamation", "reklamation einreichen"]', '["göra en reklamation", "file a claim", "göra en reklamation", "reklamation einreichen"]', '["reklamation einreichen", "file a claim", "göra en reklamation", "reklamation einreichen"]', 'advanced', false, 111),
(4, 'Otel tamamen dolu.', 'The hotel is *fully booked*.', 'Hotellet är *fullbokat*.', 'Das Hotel ist *voll ausgebucht*.', '["fully booked", "fully booked", "fullbokat", "voll ausgebucht"]', '["fully booked", "fully booked", "fullbokat", "voll ausgebucht"]', '["fullbokat", "fully booked", "fullbokat", "voll ausgebucht"]', '["voll ausgebucht", "fully booked", "fullbokat", "voll ausgebucht"]', 'advanced', false, 112),
(4, 'Gümrükten geçmem lazım.', 'I have to *go through* customs.', 'Jag måste *gå igenom* tullen.', 'Ich muss durch den *Zoll gehen*.', '["go through", "go through", "gå igenom", "gehen"]', '["go through", "go through", "gå igenom", "gehen"]', '["gå igenom", "go through", "gå igenom", "gehen"]', '["gehen", "go through", "gå igenom", "gehen"]', 'advanced', false, 113),
(4, 'Tren zamanında kalkıyor.', 'The train is *running on time*.', 'Tåget *går i tid*.', 'Der Zug *läuft pünktlich*.', '["running on time", "running on time", "går i tid", "läuft pünktlich"]', '["running on time", "running on time", "går i tid", "läuft pünktlich"]', '["går i tid", "running on time", "går i tid", "läuft pünktlich"]', '["läuft pünktlich", "running on time", "går i tid", "läuft pünktlich"]', 'advanced', false, 114),
(4, 'Biletim için iade istiyorum.', 'I need a *refund* for my ticket.', 'Jag behöver en *återbetalning* för min biljett.', 'Ich brauche eine *Rückerstattung* für meine Karte.', '["refund", "refund", "återbetalning", "rückerstattung"]', '["refund", "refund", "återbetalning", "rückerstattung"]', '["återbetalning", "refund", "återbetalning", "rückerstattung"]', '["rückerstattung", "refund", "återbetalning", "rückerstattung"]', 'advanced', false, 115),
(4, 'Otobüs durağı karşı tarafta.', 'The bus stop is *across the street*.', 'Busshållplatsen är *på andra sidan gatan*.', 'Die Bushaltestelle ist *gegenüber*.', '["across the street", "across the street", "på andra sidan gatan", "gegenüber"]', '["across the street", "across the street", "på andra sidan gatan", "gegenüber"]', '["på andra sidan gatan", "across the street", "på andra sidan gatan", "gegenüber"]', '["gegenüber", "across the street", "på andra sidan gatan", "gegenüber"]', 'advanced', false, 116),
(4, 'Uçuşumu yakalamam lazım.', 'I have to *catch* my flight.', 'Jag måste *hinna* mitt flyg.', 'Ich muss meinen Flug *erreichen*.', '["catch", "catch", "hinna", "erreichen"]', '["catch", "catch", "hinna", "erreichen"]', '["hinna", "catch", "hinna", "erreichen"]', '["erreichen", "catch", "hinna", "erreichen"]', 'advanced', false, 117),
(4, 'Otelde yüzme havuzu var.', 'The hotel has a *swimming pool*.', 'Hotellet har en *simbassäng*.', 'Das Hotel hat einen *Schwimmbad*.', '["swimming pool", "swimming pool", "simbassäng", "schwimmbad"]', '["swimming pool", "swimming pool", "simbassäng", "schwimmbad"]', '["simbassäng", "swimming pool", "simbassäng", "schwimmbad"]', '["schwimmbad", "swimming pool", "simbassäng", "schwimmbad"]', 'advanced', false, 118),
(4, 'İki gece için oda rezervasyonu yapmam lazım.', 'I need to *book a room* for two nights.', 'Jag behöver *boka ett rum* för två nätter.', 'Ich muss ein *Zimmer buchen* für zwei Nächte.', '["book a room", "book a room", "boka ett rum", "zimmer buchen"]', '["book a room", "book a room", "boka ett rum", "zimmer buchen"]', '["boka ett rum", "book a room", "boka ett rum", "zimmer buchen"]', '["zimmer buchen", "book a room", "boka ett rum", "zimmer buchen"]', 'advanced', false, 119),
(4, 'Havaalanı sis nedeniyle kapalı.', 'The airport is closed due to *fog*.', 'Flygplatsen är stängd på grund av *dimma*.', 'Der Flughafen ist wegen *Nebel* geschlossen.', '["fog", "fog", "dimma", "nebel"]', '["fog", "fog", "dimma", "nebel"]', '["dimma", "fog", "dimma", "nebel"]', '["nebel", "fog", "dimma", "nebel"]', 'advanced', false, 120);

-- Category 5: Beginner (10 sentences)
INSERT INTO sentences (category_id, text_tr, text_en, text_sv, text_de, keywords_tr, keywords_en, keywords_sv, keywords_de, difficulty, is_free, sort_order) VALUES
(5, 'Ders saat kaçta başlar?', 'What time does the class start?', 'Vad tid börjar lektionen?', 'Wann beginnt die Vorlesung?', '[]', '[]', '[]', '[]', 'beginner', false, 121),
(5, 'Kitap ödünç almak istiyorum.', 'I want to borrow a book.', 'Jag vill låna en bok.', 'Ich möchte ein Buch ausleihen.', '[]', '[]', '[]', '[]', 'beginner', false, 122),
(5, 'Sınav tarihi ne zaman?', 'When is the exam date?', 'När är examinationen?', 'Wann ist der Prüfungstermin?', '[]', '[]', '[]', '[]', 'beginner', false, 123),
(5, 'Notlarımı aldım.', 'I took my notes.', 'Jag tog mina anteckningar.', 'Ich habe meine Notizen genommen.', '[]', '[]', '[]', '[]', 'beginner', false, 124),
(5, 'Araştırma yapmak istiyorum.', 'I want to do research.', 'Jag vill göra forskning.', 'Ich möchte forschen.', '[]', '[]', '[]', '[]', 'beginner', false, 125),
(5, 'Tez yazıyorum.', 'I''m writing a thesis.', 'Jag skriver en avhandling.', 'Ich schreibe eine Dissertation.', '[]', '[]', '[]', '[]', 'beginner', false, 126),
(5, 'Kütüphane saatleri ne?', 'What are the library hours?', 'Vad är bibliotekets öppettider?', 'Was sind die Bibliotheksöffnungszeiten?', '[]', '[]', '[]', '[]', 'beginner', false, 127),
(5, 'Sunum hazırladım.', 'I prepared a presentation.', 'Jag förberedde en presentation.', 'Ich habe eine Präsentation vorbereitet.', '[]', '[]', '[]', '[]', 'beginner', false, 128),
(5, 'Ders programı nedir?', 'What is the course schedule?', 'Vad är kursplanen?', 'Was ist der Kursplan?', '[]', '[]', '[]', '[]', 'beginner', false, 129),
(5, 'Öğretmenle görüşmek istiyorum.', 'I want to meet with the teacher.', 'Jag vill träffa läraren.', 'Ich möchte den Lehrer treffen.', '[]', '[]', '[]', '[]', 'beginner', false, 130);

-- Category 5: Intermediate (10 sentences)
INSERT INTO sentences (category_id, text_tr, text_en, text_sv, text_de, keywords_tr, keywords_en, keywords_sv, keywords_de, difficulty, is_free, sort_order) VALUES
(5, '*According to* the research...', '*According to* the research...', '*Enligt* forskningen...', '*Gemäß* der Forschung...', '["according to", "according to", "enligt", "gemäß"]', '["according to", "according to", "enligt", "gemäß"]', '["enligt", "according to", "enligt", "gemäß"]', '["gemäß", "according to", "enligt", "gemäß"]', 'intermediate', false, 131),
(5, '*In conclusion*...', '*In conclusion*...', '*Sammanfattningsvis*...', '*Zusammenfassend*...', '["in conclusion", "in conclusion", "sammanfattningsvis", "zusammenfassend"]', '["in conclusion", "in conclusion", "sammanfattningsvis", "zusammenfassend"]', '["sammanfattningsvis", "in conclusion", "sammanfattningsvis", "zusammenfassend"]', '["zusammenfassend", "in conclusion", "sammanfattningsvis", "zusammenfassend"]', 'intermediate', false, 132),
(5, '*On the other hand*...', '*On the other hand*...', '*Å andra sidan*...', '*Andererseits*...', '["on the other hand", "on the other hand", "å andra sidan", "andererseits"]', '["on the other hand", "on the other hand", "å andra sidan", "andererseits"]', '["å andra sidan", "on the other hand", "å andra sidan", "andererseits"]', '["andererseits", "on the other hand", "å andra sidan", "andererseits"]', 'intermediate', false, 133),
(5, 'Deneyi *carry out*.', '*Carry out* the experiment.', '*Genomföra* experimentet.', 'Das Experiment *durchführen*.', '["carry out", "carry out", "genomföra", "durchführen"]', '["carry out", "carry out", "genomföra", "durchführen"]', '["genomföra", "carry out", "genomföra", "durchführen"]', '["durchführen", "carry out", "genomföra", "durchführen"]', 'intermediate', false, 134),
(5, '*Based on* the data...', '*Based on* the data...', '*Baserat på* data...', '*Basierend auf* den Daten...', '["based on", "based on", "baserat på", "basierend auf"]', '["based on", "based on", "baserat på", "basierend auf"]', '["baserat på", "based on", "baserat på", "basierend auf"]', '["basierend auf", "based on", "baserat på", "basierend auf"]', 'intermediate', false, 135),
(5, 'Ödevi *submit*.', '*Submit* the assignment.', '*Lämna in* uppgiften.', 'Die Aufgabe *einreichen*.', '["submit", "submit", "lämna in", "einreichen"]', '["submit", "submit", "lämna in", "einreichen"]', '["lämna in", "submit", "lämna in", "einreichen"]', '["einreichen", "submit", "lämna in", "einreichen"]', 'intermediate', false, 136),
(5, 'Sonuçlar gösteriyor ki...', 'The results *show that*...', 'Resultaten *visar att*...', 'Die Ergebnisse *zeigen, dass*...', '["show that", "show that", "visar att", "zeigen, dass"]', '["show that", "show that", "visar att", "zeigen, dass"]', '["visar att", "show that", "visar att", "zeigen, dass"]', '["zeigen, dass", "show that", "visar att", "zeigen, dass"]', 'intermediate', false, 137),
(5, '*In order to* understand...', '*In order to* understand...', '*För att* förstå...', '*Um zu* verstehen...', '["in order to", "in order to", "för att", "um zu"]', '["in order to", "in order to", "för att", "um zu"]', '["för att", "in order to", "för att", "um zu"]', '["um zu", "in order to", "för att", "um zu"]', 'intermediate', false, 138),
(5, '*As a result of*...', '*As a result of*...', '*Som ett resultat av*...', '*Als Ergebnis von*...', '["as a result of", "as a result of", "som ett resultat av", "als ergebnis von"]', '["as a result of", "as a result of", "som ett resultat av", "als ergebnis von"]', '["som ett resultat av", "as a result of", "som ett resultat av", "als ergebnis von"]', '["als ergebnis von", "as a result of", "som ett resultat av", "als ergebnis von"]', 'intermediate', false, 139),
(5, 'Çalışma odaklanıyor...', 'The study *focuses on*...', 'Studien *fokuserar på*...', 'Die Studie *konzentriert sich auf*...', '["focuses on", "focuses on", "fokuserar på", "konzentriert sich auf"]', '["focuses on", "focuses on", "fokuserar på", "konzentriert sich auf"]', '["fokuserar på", "focuses on", "fokuserar på", "konzentriert sich auf"]', '["konzentriert sich auf", "focuses on", "fokuserar på", "konzentriert sich auf"]', 'intermediate', false, 140);

-- Category 5: Advanced (10 sentences)
INSERT INTO sentences (category_id, text_tr, text_en, text_sv, text_de, keywords_tr, keywords_en, keywords_sv, keywords_de, difficulty, is_free, sort_order) VALUES
(5, 'Bu araştırmada kullanılan metodoloji...', 'The methodology *used in* this research...', 'Metodologin *använd i* denna forskning...', 'Die Methodologie *verwendet in* dieser Forschung...', '["used in", "used in", "använd i", "verwendet in"]', '["used in", "used in", "använd i", "verwendet in"]', '["använd i", "used in", "använd i", "verwendet in"]', '["verwendet in", "used in", "använd i", "verwendet in"]', 'advanced', false, 141),
(5, 'Hipotez test edildi.', 'The hypothesis was *tested*.', 'Hypotesen *testades*.', 'Die Hypothese wurde *getestet*.', '["tested", "tested", "testades", "getestet"]', '["tested", "tested", "testades", "getestet"]', '["testades", "tested", "testades", "getestet"]', '["getestet", "tested", "testades", "getestet"]', 'advanced', false, 142),
(5, 'Literatür taraması gösteriyor...', 'The literature review *indicates*...', 'Litteraturöversikten *indikerar*...', 'Die Literaturübersicht *zeigt an*...', '["indicates", "indicates", "indikerar", "zeigt an"]', '["indicates", "indicates", "indikerar", "zeigt an"]', '["indikerar", "indicates", "indikerar", "zeigt an"]', '["zeigt an", "indicates", "indikerar", "zeigt an"]', 'advanced', false, 143),
(5, 'Bulgular önemli.', 'The findings are *significant*.', 'Fynden är *signifikanta*.', 'Die Ergebnisse sind *signifikant*.', '["significant", "significant", "signifikanta", "signifikant"]', '["significant", "significant", "signifikanta", "signifikant"]', '["signifikanta", "significant", "signifikanta", "signifikant"]', '["signifikant", "significant", "signifikanta", "signifikant"]', 'advanced', false, 144),
(5, 'Araştırma bir dönem boyunca yapıldı.', 'The research was *conducted over* a period of...', 'Forskningen *genomfördes över* en period av...', 'Die Forschung wurde *über einen Zeitraum von* durchgeführt...', '["conducted over", "conducted over", "genomfördes över", "über einen zeitraum von"]', '["conducted over", "conducted over", "genomfördes över", "über einen zeitraum von"]', '["genomfördes över", "conducted over", "genomfördes över", "über einen zeitraum von"]', '["über einen zeitraum von", "conducted over", "genomfördes över", "über einen zeitraum von"]', 'advanced', false, 145),
(5, 'Veri analiz edildi...', 'The data was *analyzed using*...', 'Data *analyserades med hjälp av*...', 'Die Daten wurden *analysiert mit*...', '["analyzed using", "analyzed using", "analyserades med hjälp av", "analysiert mit"]', '["analyzed using", "analyzed using", "analyserades med hjälp av", "analysiert mit"]', '["analyserades med hjälp av", "analyzed using", "analyserades med hjälp av", "analysiert mit"]', '["analysiert mit", "analyzed using", "analyserades med hjälp av", "analysiert mit"]', 'advanced', false, 146),
(5, 'Bu çalışmanın sonuçları...', 'The *implications of* this study...', '*Implikationerna av* denna studie...', 'Die *Implikationen dieser* Studie...', '["implications of", "implications of", "implikationerna av", "implikationen dieser"]', '["implications of", "implications of", "implikationerna av", "implikationen dieser"]', '["implikationerna av", "implications of", "implikationerna av", "implikationen dieser"]', '["implikationen dieser", "implications of", "implikationerna av", "implikationen dieser"]', 'advanced', false, 147),
(5, 'Araştırmanın sınırlılıkları...', 'The *limitations of* the research...', '*Begränsningarna av* forskningen...', 'Die *Einschränkungen der* Forschung...', '["limitations of", "limitations of", "begränsningarna av", "einschränkungen der"]', '["limitations of", "limitations of", "begränsningarna av", "einschränkungen der"]', '["begränsningarna av", "limitations of", "begränsningarna av", "einschränkungen der"]', '["einschränkungen der", "limitations of", "begränsningarna av", "einschränkungen der"]', 'advanced', false, 148),
(5, 'Öneriler şunları içeriyor...', 'The *recommendations include*...', '*Rekommendationerna inkluderar*...', 'Die *Empfehlungen umfassen*...', '["recommendations include", "recommendations include", "rekommendationerna inkluderar", "empfehlungen umfassen"]', '["recommendations include", "recommendations include", "rekommendationerna inkluderar", "empfehlungen umfassen"]', '["rekommendationerna inkluderar", "recommendations include", "rekommendationerna inkluderar", "empfehlungen umfassen"]', '["empfehlungen umfassen", "recommendations include", "rekommendationerna inkluderar", "empfehlungen umfassen"]', 'advanced', false, 149),
(5, 'Sonuç özetliyor...', 'The conclusion *summarizes*...', 'Slutsatsen *sammanfattar*...', 'Die Schlussfolgerung *fasst zusammen*...', '["summarizes", "summarizes", "sammanfattar", "fasst zusammen"]', '["summarizes", "summarizes", "sammanfattar", "fasst zusammen"]', '["sammanfattar", "summarizes", "sammanfattar", "fasst zusammen"]', '["fasst zusammen", "summarizes", "sammanfattar", "fasst zusammen"]', 'advanced', false, 150);

-- Category 6: Beginner (10 sentences)
INSERT INTO sentences (category_id, text_tr, text_en, text_sv, text_de, keywords_tr, keywords_en, keywords_sv, keywords_de, difficulty, is_free, sort_order) VALUES
(6, 'Buzları *kır*.', '*Break the ice*.', '*Bryta isen*.', 'Das Eis *brechen*.', '["break the ice", "break the ice", "bryta isen", "das eis brechen"]', '["break the ice", "break the ice", "bryta isen", "das eis brechen"]', '["bryta isen", "break the ice", "bryta isen", "das eis brechen"]', '["das eis brechen", "break the ice", "bryta isen", "das eis brechen"]', 'beginner', false, 151),
(6, '*Mavi ayda bir*.', '*Once in a blue moon*.', '*En gång i månaden*.', '*Einmal im Monat*.', '["once in a blue moon", "once in a blue moon", "en gång i månaden", "einmal im monat"]', '["once in a blue moon", "once in a blue moon", "en gång i månaden", "einmal im monat"]', '["en gång i månaden", "once in a blue moon", "en gång i månaden", "einmal im monat"]', '["einmal im monat", "once in a blue moon", "en gång i månaden", "einmal im monat"]', 'beginner', false, 152),
(6, 'Çiviyi *tam başından vur*.', '*Hit the nail on the head*.', '*Träffa spiken på huvudet*.', 'Den Nagel auf den Kopf *treffen*.', '["hit the nail on the head", "hit the nail on the head", "träffa spiken på huvudet", "den nagel auf den kopf treffen"]', '["hit the nail on the head", "hit the nail on the head", "träffa spiken på huvudet", "den nagel auf den kopf treffen"]', '["träffa spiken på huvudet", "hit the nail on the head", "träffa spiken på huvudet", "den nagel auf den kopf treffen"]', '["den nagel auf den kopf treffen", "hit the nail on the head", "träffa spiken på huvudet", "den nagel auf den kopf treffen"]', 'beginner', false, 153),
(6, '*Pastanın bir parçası*.', '*A piece of cake*.', '*En bit tårta*.', '*Ein Stück Kuchen*.', '["a piece of cake", "a piece of cake", "en bit tårta", "ein stück kuchen"]', '["a piece of cake", "a piece of cake", "en bit tårta", "ein stück kuchen"]', '["en bit tårta", "a piece of cake", "en bit tårta", "ein stück kuchen"]', '["ein stück kuchen", "a piece of cake", "en bit tårta", "ein stück kuchen"]', 'beginner', false, 154),
(6, '*Aklında tut*.', '*Keep in mind*.', '*Håll i minnet*.', '*Im Gedächtnis behalten*.', '["keep in mind", "keep in mind", "håll i minnet", "im gedächtnis behalten"]', '["keep in mind", "keep in mind", "håll i minnet", "im gedächtnis behalten"]', '["håll i minnet", "keep in mind", "håll i minnet", "im gedächtnis behalten"]', '["im gedächtnis behalten", "keep in mind", "håll i minnet", "im gedächtnis behalten"]', 'beginner', false, 155),
(6, '*Sana bağlı*.', '*It''s up to you*.', '*Det är upp till dig*.', '*Es liegt an dir*.', '["it''s up to you", "it''s up to you", "det är upp till dig", "es liegt an dir"]', '["it''s up to you", "it''s up to you", "det är upp till dig", "es liegt an dir"]', '["det är upp till dig", "it''s up to you", "det är upp till dig", "es liegt an dir"]', '["es liegt an dir", "it''s up to you", "det är upp till dig", "es liegt an dir"]', 'beginner', false, 156),
(6, '*Bu arada*.', '*By the way*.', '*Förresten*.', '*Übrigens*.', '["by the way", "by the way", "förresten", "übrigens"]', '["by the way", "by the way", "förresten", "übrigens"]', '["förresten", "by the way", "förresten", "übrigens"]', '["übrigens", "by the way", "förresten", "übrigens"]', 'beginner', false, 157),
(6, '*Mümkün olan en kısa sürede*.', '*As soon as possible*.', '*Så snart som möjligt*.', '*So bald wie möglich*.', '["as soon as possible", "as soon as possible", "så snart som möjligt", "so bald wie möglich"]', '["as soon as possible", "as soon as possible", "så snart som möjligt", "so bald wie möglich"]', '["så snart som möjligt", "as soon as possible", "så snart som möjligt", "so bald wie möglich"]', '["so bald wie möglich", "as soon as possible", "så snart som möjligt", "so bald wie möglich"]', 'beginner', false, 158),
(6, '*Rahat ol*.', '*Take it easy*.', '*Ta det lugnt*.', '*Nimm es leicht*.', '["take it easy", "take it easy", "ta det lugnt", "nimm es leicht"]', '["take it easy", "take it easy", "ta det lugnt", "nimm es leicht"]', '["ta det lugnt", "take it easy", "ta det lugnt", "nimm es leicht"]', '["nimm es leicht", "take it easy", "ta det lugnt", "nimm es leicht"]', 'beginner', false, 159),
(6, '*Sorun yok*.', '*No problem*.', '*Inget problem*.', '*Kein Problem*.', '["no problem", "no problem", "inget problem", "kein problem"]', '["no problem", "no problem", "inget problem", "kein problem"]', '["inget problem", "no problem", "inget problem", "kein problem"]', '["kein problem", "no problem", "inget problem", "kein problem"]', 'beginner', false, 160);

-- Category 6: Intermediate (10 sentences)
INSERT INTO sentences (category_id, text_tr, text_en, text_sv, text_de, keywords_tr, keywords_en, keywords_sv, keywords_de, difficulty, is_free, sort_order) VALUES
(6, '*Ölmek*.', '*Kick the bucket*.', '*Slå ihjäl sig*.', '*Ins Gras beißen*.', '["kick the bucket", "kick the bucket", "slå ihjäl sig", "ins gras beißen"]', '["kick the bucket", "kick the bucket", "slå ihjäl sig", "ins gras beißen"]', '["slå ihjäl sig", "kick the bucket", "slå ihjäl sig", "ins gras beißen"]', '["ins gras beißen", "kick the bucket", "slå ihjäl sig", "ins gras beißen"]', 'intermediate', false, 161),
(6, '*Sır vermek*.', '*Spill the beans*.', '*Spilla bönorna*.', '*Die Bohnen ausplaudern*.', '["spill the beans", "spill the beans", "spilla bönorna", "die bohnen ausplaudern"]', '["spill the beans", "spill the beans", "spilla bönorna", "die bohnen ausplaudern"]', '["spilla bönorna", "spill the beans", "spilla bönorna", "die bohnen ausplaudern"]', '["die bohnen ausplaudern", "spill the beans", "spilla bönorna", "die bohnen ausplaudern"]', 'intermediate', false, 162),
(6, '*Cesaret etmek*.', '*Bite the bullet*.', '*Bita i det sura äpplet*.', '*In den sauren Apfel beißen*.', '["bite the bullet", "bite the bullet", "bita i det sura äpplet", "in den sauren apfel beißen"]', '["bite the bullet", "bite the bullet", "bita i det sura äpplet", "in den sauren apfel beißen"]', '["bita i det sura äpplet", "bite the bullet", "bita i det sura äpplet", "in den sauren apfel beißen"]', '["in den sauren apfel beißen", "bite the bullet", "bita i det sura äpplet", "in den sauren apfel beißen"]', 'intermediate', false, 163),
(6, '*Çok pahalı*.', '*Cost an arm and a leg*.', '*Kosta en arm och ett ben*.', '*Ein Vermögen kosten*.', '["cost an arm and a leg", "cost an arm and a leg", "kosta en arm och ett ben", "ein vermögen kosten"]', '["cost an arm and a leg", "cost an arm and a leg", "kosta en arm och ett ben", "ein vermögen kosten"]', '["kosta en arm och ett ben", "cost an arm and a leg", "kosta en arm och ett ben", "ein vermögen kosten"]', '["ein vermögen kosten", "cost an arm and a leg", "kosta en arm och ett ben", "ein vermögen kosten"]', 'intermediate', false, 164),
(6, '*Hasta olmak*.', '*Under the weather*.', '*Inte på topp*.', '*Nicht auf der Höhe*.', '["under the weather", "under the weather", "inte på topp", "nicht auf der höhe"]', '["under the weather", "under the weather", "inte på topp", "nicht auf der höhe"]', '["inte på topp", "under the weather", "inte på topp", "nicht auf der höhe"]', '["nicht auf der höhe", "under the weather", "inte på topp", "nicht auf der höhe"]', 'intermediate', false, 165),
(6, '*Dalga geçmek*.', '*Pull someone''s leg*.', '*Dra någon vid näsan*.', '*Jemanden auf den Arm nehmen*.', '["pull someone''s leg", "pull someone''s leg", "dra någon vid näsan", "jemanden auf den arm nehmen"]', '["pull someone''s leg", "pull someone''s leg", "dra någon vid näsan", "jemanden auf den arm nehmen"]', '["dra någon vid näsan", "pull someone''s leg", "dra någon vid näsan", "jemanden auf den arm nehmen"]', '["jemanden auf den arm nehmen", "pull someone''s leg", "dra någon vid näsan", "jemanden auf den arm nehmen"]', 'intermediate', false, 166),
(6, '*Sır vermek*.', '*Let the cat out of the bag*.', '*Släppa katten ur säcken*.', '*Die Katze aus dem Sack lassen*.', '["let the cat out of the bag", "let the cat out of the bag", "släppa katten ur säcken", "die katze aus dem sack lassen"]', '["let the cat out of the bag", "let the cat out of the bag", "släppa katten ur säcken", "die katze aus dem sack lassen"]', '["släppa katten ur säcken", "let the cat out of the bag", "släppa katten ur säcken", "die katze aus dem sack lassen"]', '["die katze aus dem sack lassen", "let the cat out of the bag", "släppa katten ur säcken", "die katze aus dem sack lassen"]', 'intermediate', false, 167),
(6, '*Gece geç saatlere kadar çalışmak*.', '*Burn the midnight oil*.', '*Sitta uppe sent*.', '*Bis spät in die Nacht arbeiten*.', '["burn the midnight oil", "burn the midnight oil", "sitta uppe sent", "bis spät in die nacht arbeiten"]', '["burn the midnight oil", "burn the midnight oil", "sitta uppe sent", "bis spät in die nacht arbeiten"]', '["sitta uppe sent", "burn the midnight oil", "sitta uppe sent", "bis spät in die nacht arbeiten"]', '["bis spät in die nacht arbeiten", "burn the midnight oil", "sitta uppe sent", "bis spät in die nacht arbeiten"]', 'intermediate', false, 168),
(6, '*Geçmişe ağlamak*.', '*Cry over spilt milk*.', '*Gråta över spilld mjölk*.', '*Über verschüttete Milch weinen*.', '["cry over spilt milk", "cry over spilt milk", "gråta över spilld mjölk", "über verschüttete milch weinen"]', '["cry over spilt milk", "cry over spilt milk", "gråta över spilld mjölk", "über verschüttete milch weinen"]', '["gråta över spilld mjölk", "cry over spilt milk", "gråta över spilld mjölk", "über verschüttete milch weinen"]', '["über verschüttete milch weinen", "cry over spilt milk", "gråta över spilld mjölk", "über verschüttete milch weinen"]', 'intermediate', false, 169),
(6, '*Kısaltmak*.', '*Cut corners*.', '*Skära hörn*.', '*Ecken abschneiden*.', '["cut corners", "cut corners", "skära hörn", "ecken abschneiden"]', '["cut corners", "cut corners", "skära hörn", "ecken abschneiden"]', '["skära hörn", "cut corners", "skära hörn", "ecken abschneiden"]', '["ecken abschneiden", "cut corners", "skära hörn", "ecken abschneiden"]', 'intermediate', false, 170);

-- Category 6: Advanced (10 sentences)
INSERT INTO sentences (category_id, text_tr, text_en, text_sv, text_de, keywords_tr, keywords_en, keywords_sv, keywords_de, difficulty, is_free, sort_order) VALUES
(6, '*Yanlış yerde aramak*.', '*Barking up the wrong tree*.', '*Skälla upp fel träd*.', '*Auf dem falschen Baum wedeln*.', '["barking up the wrong tree", "barking up the wrong tree", "skälla upp fel träd", "auf dem falschen baum wedeln"]', '["barking up the wrong tree", "barking up the wrong tree", "skälla upp fel träd", "auf dem falschen baum wedeln"]', '["skälla upp fel träd", "barking up the wrong tree", "skälla upp fel träd", "auf dem falschen baum wedeln"]', '["auf dem falschen baum wedeln", "barking up the wrong tree", "skälla upp fel träd", "auf dem falschen baum wedeln"]', 'advanced', false, 171),
(6, '*Tavukları saymadan önce*.', '*Don''t count your chickens before they hatch*.', '*Räkna inte dina kycklingar innan de kläcks*.', '*Zähle deine Hühner nicht, bevor sie geschlüpft sind*.', '["don''t count your chickens before they hatch", "don''t count your chickens before they hatch", "räkna inte dina kycklingar innan de kläcks", "zähle deine hühner nicht, bevor sie geschlüpft sind"]', '["don''t count your chickens before they hatch", "don''t count your chickens before they hatch", "räkna inte dina kycklingar innan de kläcks", "zähle deine hühner nicht, bevor sie geschlüpft sind"]', '["räkna inte dina kycklingar innan de kläcks", "don''t count your chickens before they hatch", "räkna inte dina kycklingar innan de kläcks", "zähle deine hühner nicht, bevor sie geschlüpft sind"]', '["zähle deine hühner nicht, bevor sie geschlüpft sind", "don''t count your chickens before they hatch", "räkna inte dina kycklingar innan de kläcks", "zähle deine hühner nicht, bevor sie geschlüpft sind"]', 'advanced', false, 172),
(6, '*Bir taşla iki kuş vurmak*.', '*Kill two birds with one stone*.', '*Slå två flugor i en smäll*.', '*Zwei Fliegen mit einer Klappe schlagen*.', '["kill two birds with one stone", "kill two birds with one stone", "slå två flugor i en smäll", "zwei fliegen mit einer klappe schlagen"]', '["kill two birds with one stone", "kill two birds with one stone", "slå två flugor i en smäll", "zwei fliegen mit einer klappe schlagen"]', '["slå två flugor i en smäll", "kill two birds with one stone", "slå två flugor i en smäll", "zwei fliegen mit einer klappe schlagen"]', '["zwei fliegen mit einer klappe schlagen", "kill two birds with one stone", "slå två flugor i en smäll", "zwei fliegen mit einer klappe schlagen"]', 'advanced', false, 173),
(6, '*Top senin sahan*.', '*The ball is in your court*.', '*Bollen är i din planhalva*.', '*Der Ball liegt in deinem Feld*.', '["the ball is in your court", "the ball is in your court", "bollen är i din planhalva", "der ball liegt in deinem feld"]', '["the ball is in your court", "the ball is in your court", "bollen är i din planhalva", "der ball liegt in deinem feld"]', '["bollen är i din planhalva", "the ball is in your court", "bollen är i din planhalva", "der ball liegt in deinem feld"]', '["der ball liegt in deinem feld", "the ball is in your court", "bollen är i din planhalva", "der ball liegt in deinem feld"]', 'advanced', false, 174),
(6, '*Tüm yumurtaları aynı sepete koyma*.', '*Don''t put all your eggs in one basket*.', '*Lägg inte alla ägg i samma korg*.', '*Lege nicht alle Eier in einen Korb*.', '["don''t put all your eggs in one basket", "don''t put all your eggs in one basket", "lägg inte alla ägg i samma korg", "lege nicht alle eier in einen korb"]', '["don''t put all your eggs in one basket", "don''t put all your eggs in one basket", "lägg inte alla ägg i samma korg", "lege nicht alle eier in einen korb"]', '["lägg inte alla ägg i samma korg", "don''t put all your eggs in one basket", "lägg inte alla ägg i samma korg", "lege nicht alle eier in einen korb"]', '["lege nicht alle eier in einen korb", "don''t put all your eggs in one basket", "lägg inte alla ägg i samma korg", "lege nicht alle eier in einen korb"]', 'advanced', false, 175),
(6, '*Eylemler sözlerden daha yüksek sesle konuşur*.', '*Actions speak louder than words*.', '*Handlingar talar högre än ord*.', '*Taten sprechen lauter als Worte*.', '["actions speak louder than words", "actions speak louder than words", "handlingar talar högre än ord", "taten sprechen lauter als worte"]', '["actions speak louder than words", "actions speak louder than words", "handlingar talar högre än ord", "taten sprechen lauter als worte"]', '["handlingar talar högre än ord", "actions speak louder than words", "handlingar talar högre än ord", "taten sprechen lauter als worte"]', '["taten sprechen lauter als worte", "actions speak louder than words", "handlingar talar högre än ord", "taten sprechen lauter als worte"]', 'advanced', false, 176),
(6, '*Kitabı kapağına göre yargılama*.', '*Don''t judge a book by its cover*.', '*Döm inte boken efter omslaget*.', '*Urteile nicht über ein Buch nach seinem Einband*.', '["don''t judge a book by its cover", "don''t judge a book by its cover", "döm inte boken efter omslaget", "urteile nicht über ein buch nach seinem einband"]', '["don''t judge a book by its cover", "don''t judge a book by its cover", "döm inte boken efter omslaget", "urteile nicht über ein buch nach seinem einband"]', '["döm inte boken efter omslaget", "don''t judge a book by its cover", "döm inte boken efter omslaget", "urteile nicht über ein buch nach seinem einband"]', '["urteile nicht über ein buch nach seinem einband", "don''t judge a book by its cover", "döm inte boken efter omslaget", "urteile nicht über ein buch nach seinem einband"]', 'advanced', false, 177),
(6, '*Roma bir günde inşa edilmedi*.', '*Rome wasn''t built in a day*.', '*Rom byggdes inte på en dag*.', '*Rom wurde nicht an einem Tag gebaut*.', '["rome wasn''t built in a day", "rome wasn''t built in a day", "rom byggdes inte på en dag", "rom wurde nicht an einem tag gebaut"]', '["rome wasn''t built in a day", "rome wasn''t built in a day", "rom byggdes inte på en dag", "rom wurde nicht an einem tag gebaut"]', '["rom byggdes inte på en dag", "rome wasn''t built in a day", "rom byggdes inte på en dag", "rom wurde nicht an einem tag gebaut"]', '["rom wurde nicht an einem tag gebaut", "rome wasn''t built in a day", "rom byggdes inte på en dag", "rom wurde nicht an einem tag gebaut"]', 'advanced', false, 178),
(6, '*Erken kalkan yol alır*.', '*The early bird catches the worm*.', '*Den som vaknar tidigt får masken*.', '*Der frühe Vogel fängt den Wurm*.', '["the early bird catches the worm", "the early bird catches the worm", "den som vaknar tidigt får masken", "der frühe vogel fängt den wurm"]', '["the early bird catches the worm", "the early bird catches the worm", "den som vaknar tidigt får masken", "der frühe vogel fängt den wurm"]', '["den som vaknar tidigt får masken", "the early bird catches the worm", "den som vaknar tidigt får masken", "der frühe vogel fängt den wurm"]', '["der frühe vogel fängt den wurm", "the early bird catches the worm", "den som vaknar tidigt får masken", "der frühe vogel fängt den wurm"]', 'advanced', false, 179),
(6, '*Roma''da Romalılar gibi yap*.', '*When in Rome, do as the Romans do*.', '*När du är i Rom, gör som romarna gör*.', '*Wenn du in Rom bist, tu wie die Römer tun*.', '["when in Rome, do as the Romans do", "when in Rome, do as the Romans do", "när du är i rom, gör som romarna gör", "wenn du in rom bist, tu wie die römer tun"]', '["when in Rome, do as the Romans do", "when in Rome, do as the Romans do", "när du är i rom, gör som romarna gör", "wenn du in rom bist, tu wie die römer tun"]', '["när du är i rom, gör som romarna gör", "when in Rome, do as the Romans do", "när du är i rom, gör som romarna gör", "wenn du in rom bist, tu wie die römer tun"]', '["wenn du in rom bist, tu wie die römer tun", "when in Rome, do as the Romans do", "när du är i rom, gör som romarna gör", "wenn du in rom bist, tu wie die römer tun"]', 'advanced', false, 180);

-- Category 7: Beginner (10 sentences)
INSERT INTO sentences (category_id, text_tr, text_en, text_sv, text_de, keywords_tr, keywords_en, keywords_sv, keywords_de, difficulty, is_free, sort_order) VALUES
(7, 'Burada *used to* yaşamak.', '*Used to* live here.', '*Brukade* bo här.', '*Pflegte* hier zu leben.', '["used to", "used to", "brukade", "pflegte"]', '["used to", "used to", "brukade", "pflegte"]', '["brukade", "used to", "brukade", "pflegte"]', '["pflegte", "used to", "brukade", "pflegte"]', 'beginner', false, 181),
(7, '*Would rather* kalmak.', '*Would rather* stay.', '*Föredrar att* stanna.', '*Würde lieber* bleiben.', '["would rather", "would rather", "föredrar att", "würde lieber"]', '["would rather", "would rather", "föredrar att", "würde lieber"]', '["föredrar att", "would rather", "föredrar att", "würde lieber"]', '["würde lieber", "would rather", "föredrar att", "würde lieber"]', 'beginner', false, 182),
(7, '*Even though* yağmur yağıyor.', '*Even though* it''s raining.', '*Även om* det regnar.', '*Obwohl* es regnet.', '["even though", "even though", "även om", "obwohl"]', '["even though", "even though", "även om", "obwohl"]', '["även om", "even though", "även om", "obwohl"]', '["obwohl", "even though", "även om", "obwohl"]', 'beginner', false, 183),
(7, 'Sadece... *not only...but also*.', '*Not only*...*but also*.', '*Inte bara*...*utan också*.', '*Nicht nur*...*sondern auch*.', '["not only...but also", "not only...but also", "inte bara...utan också", "nicht nur...sondern auch"]', '["not only...but also", "not only...but also", "inte bara...utan också", "nicht nur...sondern auch"]', '["inte bara...utan också", "not only...but also", "inte bara...utan också", "nicht nur...sondern auch"]', '["nicht nur...sondern auch", "not only...but also", "inte bara...utan också", "nicht nur...sondern auch"]', 'beginner', false, 184),
(7, 'Ne kadar çok... *the more...the more*.', '*The more*...*the more*.', '*Ju mer*...*desto mer*.', '*Je mehr*...*desto mehr*.', '["the more...the more", "the more...the more", "ju mer...desto mer", "je mehr...desto mehr"]', '["the more...the more", "the more...the more", "ju mer...desto mer", "je mehr...desto mehr"]', '["ju mer...desto mer", "the more...the more", "ju mer...desto mer", "je mehr...desto mehr"]', '["je mehr...desto mehr", "the more...the more", "ju mer...desto mer", "je mehr...desto mehr"]', 'beginner', false, 185),
(7, '*As long as* denersen.', '*As long as* you try.', '*Så länge som* du försöker.', '*Solange* du versuchst.', '["as long as", "as long as", "så länge som", "solange"]', '["as long as", "as long as", "så länge som", "solange"]', '["så länge som", "as long as", "så länge som", "solange"]', '["solange", "as long as", "så länge som", "solange"]', 'beginner', false, 186),
(7, '*In case* of emergency.', '*In case* of emergency.', '*I fall* av nödsituation.', '*Im Falle* eines Notfalls.', '["in case", "in case", "i fall", "im falle"]', '["in case", "in case", "i fall", "im falle"]', '["i fall", "in case", "i fall", "im falle"]', '["im falle", "in case", "i fall", "im falle"]', 'beginner', false, 187),
(7, '*Unless* acele etmezsen.', '*Unless* you hurry.', '*Om inte* du skyndar dig.', '*Es sei denn*, du beeilst dich.', '["unless", "unless", "om inte", "es sei denn"]', '["unless", "unless", "om inte", "es sei denn"]', '["om inte", "unless", "om inte", "es sei denn"]', '["es sei denn", "unless", "om inte", "es sei denn"]', 'beginner', false, 188),
(7, 'Başarmak için *in order to*.', '*In order to* succeed.', '*För att* lyckas.', '*Um zu* erfolgreich sein.', '["in order to", "in order to", "för att", "um zu"]', '["in order to", "in order to", "för att", "um zu"]', '["för att", "in order to", "för att", "um zu"]', '["um zu", "in order to", "för att", "um zu"]', 'beginner', false, 189),
(7, 'Yürümekten *rather than*.', '*Rather than* walk.', '*Hellre än* att gå.', '*Lieber als* zu gehen.', '["rather than", "rather than", "hellre än", "lieber als"]', '["rather than", "rather than", "hellre än", "lieber als"]', '["hellre än", "rather than", "hellre än", "lieber als"]', '["lieber als", "rather than", "hellre än", "lieber als"]', 'beginner', false, 190);

-- Category 7: Intermediate (10 sentences)
INSERT INTO sentences (category_id, text_tr, text_en, text_sv, text_de, keywords_tr, keywords_en, keywords_sv, keywords_de, difficulty, is_free, sort_order) VALUES
(7, '*Had better* çalışmak.', '*Had better* study.', '*Borde* studera.', '*Sollte besser* studieren.', '["had better", "had better", "borde", "sollte besser"]', '["had better", "had better", "borde", "sollte besser"]', '["borde", "had better", "borde", "sollte besser"]', '["sollte besser", "had better", "borde", "sollte besser"]', 'intermediate', false, 191),
(7, '*If I were* you.', '*If I were* you.', '*Om jag vore* du.', '*Wenn ich du wäre*.', '["if I were", "if I were", "om jag vore", "wenn ich du wäre"]', '["if I were", "if I were", "om jag vore", "wenn ich du wäre"]', '["om jag vore", "if I were", "om jag vore", "wenn ich du wäre"]', '["wenn ich du wäre", "if I were", "om jag vore", "wenn ich du wäre"]', 'intermediate', false, 192),
(7, '*As if* biliyormuş gibi.', '*As if* he knew.', '*Som om* han visste.', '*Als ob* er wüsste.', '["as if", "as if", "som om", "als ob"]', '["as if", "as if", "som om", "als ob"]', '["som om", "as if", "som om", "als ob"]', '["als ob", "as if", "som om", "als ob"]', 'intermediate', false, 193),
(7, '*Whether or not*.', '*Whether or not*.', '*Oavsett om*.', '*Ob oder nicht*.', '["whether or not", "whether or not", "oavsett om", "ob oder nicht"]', '["whether or not", "whether or not", "oavsett om", "ob oder nicht"]', '["oavsett om", "whether or not", "oavsett om", "ob oder nicht"]', '["ob oder nicht", "whether or not", "oavsett om", "ob oder nicht"]', 'intermediate', false, 194),
(7, '*So that* I can.', '*So that* I can.', '*Så att* jag kan.', '*Damit* ich kann.', '["so that", "so that", "så att", "damit"]', '["so that", "so that", "så att", "damit"]', '["så att", "so that", "så att", "damit"]', '["damit", "so that", "så att", "damit"]', 'intermediate', false, 195),
(7, '*Provided that*.', '*Provided that*.', '*Förutsatt att*.', '*Vorausgesetzt, dass*.', '["provided that", "provided that", "förutsatt att", "vorausgesetzt, dass"]', '["provided that", "provided that", "förutsatt att", "vorausgesetzt, dass"]', '["förutsatt att", "provided that", "förutsatt att", "vorausgesetzt, dass"]', '["vorausgesetzt, dass", "provided that", "förutsatt att", "vorausgesetzt, dass"]', 'intermediate', false, 196),
(7, '*In spite of*.', '*In spite of*.', '*Trots*.', '*Trotz*.', '["in spite of", "in spite of", "trots", "trotz"]', '["in spite of", "in spite of", "trots", "trotz"]', '["trots", "in spite of", "trots", "trotz"]', '["trotz", "in spite of", "trots", "trotz"]', 'intermediate', false, 197),
(7, '*On condition that*.', '*On condition that*.', '*På villkor att*.', '*Unter der Bedingung, dass*.', '["on condition that", "on condition that", "på villkor att", "unter der bedingung, dass"]', '["on condition that", "on condition that", "på villkor att", "unter der bedingung, dass"]', '["på villkor att", "on condition that", "på villkor att", "unter der bedingung, dass"]', '["unter der bedingung, dass", "on condition that", "på villkor att", "unter der bedingung, dass"]', 'intermediate', false, 198),
(7, '*As though*.', '*As though*.', '*Som om*.', '*Als ob*.', '["as though", "as though", "som om", "als ob"]', '["as though", "as though", "som om", "als ob"]', '["som om", "as though", "som om", "als ob"]', '["als ob", "as though", "som om", "als ob"]', 'intermediate', false, 199),
(7, '*Supposing that*.', '*Supposing that*.', '*Antagande att*.', '*Angenommen, dass*.', '["supposing that", "supposing that", "antagande att", "angenommen, dass"]', '["supposing that", "supposing that", "antagande att", "angenommen, dass"]', '["antagande att", "supposing that", "antagande att", "angenommen, dass"]', '["angenommen, dass", "supposing that", "antagande att", "angenommen, dass"]', 'intermediate', false, 200);

-- Category 7: Advanced (10 sentences)
INSERT INTO sentences (category_id, text_tr, text_en, text_sv, text_de, keywords_tr, keywords_en, keywords_sv, keywords_de, difficulty, is_free, sort_order) VALUES
(7, '*No sooner*...*than*.', '*No sooner*...*than*.', '*Nätt och jämnt*...*förrän*.', '*Kaum*...*als*.', '["no sooner...than", "no sooner...than", "nätt och jämnt...förrän", "kaum...als"]', '["no sooner...than", "no sooner...than", "nätt och jämnt...förrän", "kaum...als"]', '["nätt och jämnt...förrän", "no sooner...than", "nätt och jämnt...förrän", "kaum...als"]', '["kaum...als", "no sooner...than", "nätt och jämnt...förrän", "kaum...als"]', 'advanced', false, 201),
(7, '*Hardly*...*when*.', '*Hardly*...*when*.', '*Nätt och jämnt*...*när*.', '*Kaum*...*als*.', '["hardly...when", "hardly...when", "nätt och jämnt...när", "kaum...als"]', '["hardly...when", "hardly...when", "nätt och jämnt...när", "kaum...als"]', '["nätt och jämnt...när", "hardly...when", "nätt och jämnt...när", "kaum...als"]', '["kaum...als", "hardly...when", "nätt och jämnt...när", "kaum...als"]', 'advanced', false, 202),
(7, '*Scarcely*...*before*.', '*Scarcely*...*before*.', '*Nätt och jämnt*...*innan*.', '*Kaum*...*bevor*.', '["scarcely...before", "scarcely...before", "nätt och jämnt...innan", "kaum...bevor"]', '["scarcely...before", "scarcely...before", "nätt och jämnt...innan", "kaum...bevor"]', '["nätt och jämnt...innan", "scarcely...before", "nätt och jämnt...innan", "kaum...bevor"]', '["kaum...bevor", "scarcely...before", "nätt och jämnt...innan", "kaum...bevor"]', 'advanced', false, 203),
(7, '*What if*.', '*What if*.', '*Tänk om*.', '*Was wenn*.', '["what if", "what if", "tänk om", "was wenn"]', '["what if", "what if", "tänk om", "was wenn"]', '["tänk om", "what if", "tänk om", "was wenn"]', '["was wenn", "what if", "tänk om", "was wenn"]', 'advanced', false, 204),
(7, '*As it were*.', '*As it were*.', '*Så att säga*.', '*Sozusagen*.', '["as it were", "as it were", "så att säga", "sozusagen"]', '["as it were", "as it were", "så att säga", "sozusagen"]', '["så att säga", "as it were", "så att säga", "sozusagen"]', '["sozusagen", "as it were", "så att säga", "sozusagen"]', 'advanced', false, 205),
(7, '*For all I know*.', '*For all I know*.', '*För allt jag vet*.', '*Für alles, was ich weiß*.', '["for all I know", "for all I know", "för allt jag vet", "für alles, was ich weiß"]', '["for all I know", "for all I know", "för allt jag vet", "für alles, was ich weiß"]', '["för allt jag vet", "for all I know", "för allt jag vet", "für alles, was ich weiß"]', '["für alles, was ich weiß", "for all I know", "för allt jag vet", "für alles, was ich weiß"]', 'advanced', false, 206),
(7, '*If only*.', '*If only*.', '*Om bara*.', '*Wenn nur*.', '["if only", "if only", "om bara", "wenn nur"]', '["if only", "if only", "om bara", "wenn nur"]', '["om bara", "if only", "om bara", "wenn nur"]', '["wenn nur", "if only", "om bara", "wenn nur"]', 'advanced', false, 207),
(7, '*But for*.', '*But for*.', '*Utom*.', '*Außer*.', '["but for", "but for", "utom", "außer"]', '["but for", "but for", "utom", "außer"]', '["utom", "but for", "utom", "außer"]', '["außer", "but for", "utom", "außer"]', 'advanced', false, 208),
(7, '*As far as*.', '*As far as*.', '*Så vitt*.', '*Soweit*.', '["as far as", "as far as", "så vitt", "soweit"]', '["as far as", "as far as", "så vitt", "soweit"]', '["så vitt", "as far as", "så vitt", "soweit"]', '["soweit", "as far as", "så vitt", "soweit"]', 'advanced', false, 209),
(7, '*On the grounds that*.', '*On the grounds that*.', '*På grund av att*.', '*Aufgrund dessen, dass*.', '["on the grounds that", "on the grounds that", "på grund av att", "aufgrund dessen, dass"]', '["on the grounds that", "on the grounds that", "på grund av att", "aufgrund dessen, dass"]', '["på grund av att", "on the grounds that", "på grund av att", "aufgrund dessen, dass"]', '["aufgrund dessen, dass", "on the grounds that", "på grund av att", "aufgrund dessen, dass"]', 'advanced', false, 210);