-- 005_seed_sentences_part2.sql
-- Category 4: Seyahat        (30 sentences, is_free: false)
-- Category 5: Akademik       (30 sentences, is_free: false)
-- Category 6: İdiomlar       (30 sentences, is_free: false)
--
-- Her cümle bir tabir/ifade öğretir. Tabir **çift yıldız** ile işaretlenir.

DELETE FROM sentences WHERE category_id IN (4, 5, 6);

-- ─── CATEGORY 4 — Seyahat ───────────────────────────────────────────────────

INSERT INTO sentences (category_id, text_tr, text_en, text_sv, text_de, keywords_tr, keywords_en, keywords_sv, keywords_de, difficulty, is_free, sort_order) VALUES

-- Beginner
(4, 'Saat kaçta **otele giriş** yapabilirim?', 'What time can I **check in** to the hotel?', 'Vilken tid kan jag **checka in** på hotellet?', 'Um wie viel Uhr kann ich im Hotel **einchecken**?', '["otele giriş"]', '["check in"]', '["checka in"]', '["einchecken"]', 'beginner', false, 91),
(4, '**Çıkış saati** öğlen on iki.', 'The **check-out** time is noon.', '**Utcheckningstiden** är mitt på dagen.', 'Die **Abreisezeit** ist mittags um zwölf.', '["çıkış saati"]', '["check-out"]', '["utcheckningstiden"]', '["Abreisezeit"]', 'beginner', false, 92),
(4, 'Oraya gitmek **ne kadar sürer**?', '**How long does it take** to get there?', '**Hur lång tid tar det** att komma dit?', '**Wie lange dauert es**, dorthin zu kommen?', '["ne kadar sürer"]', '["how long does it take"]', '["hur lång tid tar det"]', '["wie lange dauert es"]', 'beginner', false, 93),
(4, 'Buradan **uzak mı**?', '**Is it far from here**?', '**Är det långt härifrån**?', '**Ist es weit von hier**?', '["uzak mı"]', '["is it far from here"]', '["är det långt härifrån"]', '["ist es weit von hier"]', 'beginner', false, 94),
(4, 'Pasaportunuzu **kaybetmemek için dikkat edin**.', 'Please **make sure** you don''t lose your passport.', 'Var noga med att du inte tappar bort passet.', 'Stellen Sie **sicher**, dass Sie Ihren Reisepass nicht verlieren.', '["dikkat edin"]', '["make sure"]', '["se till"]', '["sicher stellen"]', 'beginner', false, 95),
(4, 'Bileti **önceden** almak daha ucuz.', 'Buying the ticket **in advance** is cheaper.', 'Att köpa biljetten **i förväg** är billigare.', 'Ein Ticket **im Voraus** zu kaufen ist günstiger.', '["önceden"]', '["in advance"]', '["i förväg"]', '["im Voraus"]', 'beginner', false, 96),
(4, 'Şehirde nasıl **dolaşabilirim**?', 'How can I **get around** the city?', 'Hur kan jag **ta mig runt** i staden?', 'Wie kann ich mich in der Stadt **fortbewegen**?', '["dolaşabilirim"]', '["get around"]', '["ta mig runt"]', '["fortbewegen"]', 'beginner', false, 97),
(4, 'Vize **olduğu sürece** sorun yok.', 'There''s no problem **as long as** you have a visa.', 'Det är inga problem **så länge** du har ett visum.', 'Es gibt kein Problem, **solange** Sie ein Visum haben.', '["olduğu sürece"]', '["as long as"]', '["så länge"]', '["solange"]', 'beginner', false, 98),
(4, 'Bir çift oda **alabilir miyim**?', '**Can I have** a double room, please?', '**Kan jag få** ett dubbelrum, tack?', '**Kann ich** bitte ein Doppelzimmer **haben**?', '["alabilir miyim"]', '["can I have"]', '["kan jag få"]', '["kann ich haben"]', 'beginner', false, 99),
(4, 'Yakında güzel bir restoran var **mı acaba**?', 'Is there a good restaurant nearby, **by any chance**?', 'Finns det en bra restaurang i närheten, **möjligtvis**?', 'Gibt es zufällig ein gutes Restaurant in der Nähe?', '["mı acaba"]', '["by any chance"]', '["möjligtvis"]', '["zufällig"]', 'beginner', false, 100),

-- Intermediate
(4, 'Tarihi merkezi **arıyorum**, yardımcı olabilir misiniz?', 'I''m **looking for** the historic center, can you help?', 'Jag **letar efter** historiska centrum, kan du hjälpa?', 'Ich **suche** das historische Zentrum, können Sie helfen?', '["arıyorum"]', '["looking for"]', '["letar efter"]', '["suche"]', 'intermediate', false, 101),
(4, 'Bu müzeyi görmek **değer mi**?', 'Is this museum **worth it**?', 'Är det **värt det** att besöka det här museet?', 'Lohnt es sich, dieses Museum zu besuchen?', '["değer mi"]', '["worth it"]', '["värt det"]', '["lohnt es sich"]', 'intermediate', false, 102),
(4, 'Rezervasyonumla ilgili beni **bilgilendir**.', 'Please **let me know** about my reservation.', 'Snälla **meddela mig** om min bokning.', 'Bitte **informieren Sie mich** über meine Reservierung.', '["bilgilendir"]', '["let me know"]', '["meddela mig"]', '["informieren Sie mich"]', 'intermediate', false, 103),
(4, 'Terminal **yolun üzerinde** mi?', 'Is the terminal **on the way**?', 'Är terminalen **på vägen**?', 'Ist das Terminal **auf dem Weg**?', '["yolun üzerinde"]', '["on the way"]', '["på vägen"]', '["auf dem Weg"]', 'intermediate', false, 104),
(4, 'Uçuşuma **geç kalıyorum**.', 'I''m **running late** for my flight.', 'Jag **är sen** till mitt flyg.', 'Ich **komme zu spät** zu meinem Flug.', '["geç kalıyorum"]', '["running late"]', '["är sen"]', '["komme zu spät"]', 'intermediate', false, 105),
(4, 'Bavulumu hazırladım, **gidebiliriz**.', 'I''m **all set**, we can go.', 'Jag är **redo**, vi kan gå.', 'Ich bin **fertig**, wir können gehen.', '["gidebiliriz"]', '["all set"]', '["redo"]', '["fertig"]', 'intermediate', false, 106),
(4, 'Yarın sabah erken **yola çıkıyoruz**.', 'We''re **setting off** early tomorrow morning.', 'Vi **ger oss iväg** tidigt imorgon bitti.', 'Wir **brechen** morgen früh **auf**.', '["yola çıkıyoruz"]', '["setting off"]', '["ger oss iväg"]', '["brechen auf"]', 'intermediate', false, 107),
(4, 'Bizi havalimanında **bırakabilir misin**?', 'Can you **drop us off** at the airport?', 'Kan du **sätta av oss** på flygplatsen?', 'Kannst du uns am Flughafen **absetzen**?', '["bırakabilir misin"]', '["drop us off"]', '["sätta av oss"]', '["absetzen"]', 'intermediate', false, 108),
(4, 'Yanlış trene bindim ve **kayboldum**.', 'I took the wrong train and **got lost**.', 'Jag tog fel tåg och **gick vilse**.', 'Ich nahm den falschen Zug und habe mich **verlaufen**.', '["kayboldum"]', '["got lost"]', '["gick vilse"]', '["verlaufen"]', 'intermediate', false, 109),
(4, 'Son trene **yetişmemiz** lazım.', 'We need to **catch the last train**.', 'Vi måste **hinna med** sista tåget.', 'Wir müssen den letzten Zug **erwischen**.', '["yetişmemiz"]', '["catch the train"]', '["hinna med"]', '["erwischen"]', 'intermediate', false, 110),

-- Advanced
(4, 'Bizi havalimanından **alabilir misin**?', 'Can you **pick us up** from the airport?', 'Kan du **hämta oss** på flygplatsen?', 'Kannst du uns vom Flughafen **abholen**?', '["alabilir misin"]', '["pick us up"]', '["hämta oss"]', '["abholen"]', 'advanced', false, 111),
(4, 'Hava koşulları tatili **kısalttı**.', 'The weather conditions **cut the trip short**.', 'Väderförhållandena **kortade av** resan.', 'Die Wetterbedingungen haben den Urlaub **verkürzt**.', '["kısalttı"]', '["cut the trip short"]', '["kortade av"]', '["verkürzt"]', 'advanced', false, 112),
(4, 'İndirim için herhangi bir **şans var mı**?', 'Is there **any chance** of a discount?', 'Finns det **någon chans** till rabatt?', 'Gibt es **irgendeine Möglichkeit** auf einen Rabatt?', '["şans var mı"]', '["any chance"]', '["någon chans"]', '["irgendeine Möglichkeit"]', 'advanced', false, 113),
(4, 'Bugün **geri dönmemiz** gerekiyor.', 'We need to **head back** today.', 'Vi måste **bege oss tillbaka** idag.', 'Wir müssen heute **zurückkehren**.', '["geri dönmemiz"]', '["head back"]', '["bege oss tillbaka"]', '["zurückkehren"]', 'advanced', false, 114),
(4, 'Rehber bize şehri **gezdirdi**.', 'The guide **showed us around** the city.', 'Guiden **visade oss runt** i staden.', 'Der Führer hat uns die Stadt **gezeigt**.', '["gezdirdi"]', '["showed us around"]', '["visade oss runt"]', '["gezeigt"]', 'advanced', false, 115),
(4, 'Yarın **gezmeye çıkacağız**.', 'Tomorrow we''re going to **go sightseeing**.', 'Imorgon ska vi **gå på sightseeing**.', 'Morgen werden wir **Sightseeing machen**.', '["gezmeye çıkacağız"]', '["go sightseeing"]', '["gå på sightseeing"]', '["Sightseeing machen"]', 'advanced', false, 116),
(4, 'Otel fiyatına kahvaltı **dahil mi**?', 'Is breakfast **included** in the hotel price?', 'Ingår frukost **i hotellpriset**?', 'Ist das Frühstück **im Hotelpreis inbegriffen**?', '["dahil mi"]', '["included"]', '["i hotellpriset"]', '["inbegriffen"]', 'advanced', false, 117),
(4, 'Zaman kaybetmeden **doğrudan** terminale gidelim.', 'Let''s go **straight to** the terminal without wasting time.', 'Låt oss gå **direkt till** terminalen utan att slösa tid.', 'Lass uns **direkt zum** Terminal gehen ohne Zeit zu verlieren.', '["doğrudan"]', '["straight to"]', '["direkt till"]', '["direkt zum"]', 'advanced', false, 118),
(4, 'Pasaport kontrolünden **geçmemiz** gerekiyor.', 'We need to **go through** passport control.', 'Vi behöver **gå igenom** passkontrollen.', 'Wir müssen durch die Passkontrolle **gehen**.', '["geçmemiz"]', '["go through"]', '["gå igenom"]', '["gehen durch"]', 'advanced', false, 119),
(4, 'Tur rehberi bize bölgeyi **anlattı**.', 'The tour guide **walked us through** the area.', 'Guiden **gick igenom** området med oss.', 'Der Reiseführer hat uns das Gebiet **erklärt**.', '["anlattı"]', '["walked us through"]', '["gick igenom"]', '["erklärt"]', 'advanced', false, 120);

-- ─── CATEGORY 5 — Akademik ──────────────────────────────────────────────────

INSERT INTO sentences (category_id, text_tr, text_en, text_sv, text_de, keywords_tr, keywords_en, keywords_sv, keywords_de, difficulty, is_free, sort_order) VALUES

-- Beginner
(5, 'İklim değişikliğine **ek olarak** hava kirliliği de ciddi bir sorun.', '**In addition to** climate change, air pollution is also a serious problem.', '**Förutom** klimatförändringarna är luftföroreningar också ett allvarligt problem.', '**Zusätzlich zum** Klimawandel ist auch Luftverschmutzung ein ernstes Problem.', '["ek olarak"]', '["in addition to"]', '["förutom"]', '["zusätzlich zum"]', 'beginner', false, 121),
(5, 'Araştırma yetersizdi; **bunun sonucunda** proje başarısız oldu.', 'The research was insufficient; **as a result**, the project failed.', 'Forskningen var otillräcklig; **som ett resultat** misslyckades projektet.', 'Die Forschung war unzureichend; **als Ergebnis** scheiterte das Projekt.', '["bunun sonucunda"]', '["as a result"]', '["som ett resultat"]', '["als Ergebnis"]', 'beginner', false, 122),
(5, 'Bu yaklaşım pratik; **öte yandan** pahalı.', 'This approach is practical; **on the other hand**, it''s expensive.', 'Det här tillvägagångssättet är praktiskt; **å andra sidan** är det dyrt.', 'Dieser Ansatz ist praktisch; **andererseits** ist er teuer.', '["öte yandan"]', '["on the other hand"]', '["å andra sidan"]', '["andererseits"]', 'beginner', false, 123),
(5, '**Sonuç olarak**, bu yöntem daha verimli.', '**In conclusion**, this method is more efficient.', '**Sammanfattningsvis** är den här metoden effektivare.', '**Abschließend** lässt sich sagen, dass diese Methode effizienter ist.', '["sonuç olarak"]', '["in conclusion"]', '["sammanfattningsvis"]', '["abschließend"]', 'beginner', false, 124),
(5, 'Bu hipotez **verilere dayanıyor**.', 'This hypothesis is **based on** the data.', 'Den här hypotesen är **baserad på** datan.', 'Diese Hypothese **basiert auf** den Daten.', '["verilere dayanıyor"]', '["based on"]', '["baserad på"]', '["basiert auf"]', 'beginner', false, 125),
(5, 'Verimlilik **açısından** bu yöntem daha iyi.', '**In terms of** efficiency, this method is better.', '**Vad gäller** effektivitet är den här metoden bättre.', '**Was die Effizienz betrifft**, ist diese Methode besser.', '["açısından"]', '["in terms of"]', '["vad gäller"]', '["was betrifft"]', 'beginner', false, 126),
(5, '**Araştırmaya göre**, uyku sağlığı etkiliyor.', '**According to** the research, sleep affects health.', '**Enligt** forskningen påverkar sömn hälsan.', '**Laut** der Forschung beeinflusst Schlaf die Gesundheit.', '["araştırmaya göre"]', '["according to"]', '["enligt"]', '["laut"]', 'beginner', false, 127),
(5, '**Bir başka deyişle**, stratejiyi değiştirmemiz gerekiyor.', '**In other words**, we need to change our strategy.', '**Med andra ord** behöver vi ändra vår strategi.', '**Mit anderen Worten** müssen wir unsere Strategie ändern.', '["bir başka deyişle"]', '["in other words"]', '["med andra ord"]', '["mit anderen Worten"]', 'beginner', false, 128),
(5, '**Özetle**, bulgular ümit verici.', '**To sum up**, the findings are promising.', '**Sammanfattningsvis** är fynden lovande.', '**Zusammenfassend** sind die Ergebnisse vielversprechend.', '["özetle"]', '["to sum up"]', '["sammanfattningsvis"]', '["zusammenfassend"]', 'beginner', false, 129),
(5, '**Örneğin**, bağışıklık sistemi strese tepki verir.', '**For instance**, the immune system responds to stress.', '**Till exempel** reagerar immunsystemet på stress.', '**Zum Beispiel** reagiert das Immunsystem auf Stress.', '["örneğin"]', '["for instance"]', '["till exempel"]', '["zum Beispiel"]', 'beginner', false, 130),

-- Intermediate
(5, 'Bu veri sence **mantıklı mı**?', 'Does this data **make sense** to you?', 'Är det här datat **vettigt** för dig?', 'Ergibt dieses Datum für dich **Sinn**?', '["mantıklı mı"]', '["make sense"]', '["vettigt"]', '["Sinn ergeben"]', 'intermediate', false, 131),
(5, '**Bildiğim kadarıyla**, bu yöntem henüz test edilmedi.', '**As far as I know**, this method hasn''t been tested yet.', '**Vad jag vet** har den här metoden inte testats ännu.', '**Soweit ich weiß** wurde diese Methode noch nicht getestet.', '["bildiğim kadarıyla"]', '["as far as I know"]', '["vad jag vet"]', '["soweit ich weiß"]', 'intermediate', false, 132),
(5, 'Yazar birkaç kritik sorunu **dile getiriyor**.', 'The author **points out** several critical issues.', 'Författaren **påpekar** flera kritiska problem.', 'Der Autor **weist auf** mehrere kritische Probleme **hin**.', '["dile getiriyor"]', '["points out"]', '["påpekar"]', '["weist hin"]', 'intermediate', false, 133),
(5, 'Bu makale önceki çalışmalara **atıfta bulunuyor**.', 'This article **refers to** previous studies.', 'Den här artikeln **hänvisar till** tidigare studier.', 'Dieser Artikel **bezieht sich auf** frühere Studien.', '["atıfta bulunuyor"]', '["refers to"]', '["hänvisar till"]', '["bezieht sich auf"]', 'intermediate', false, 134),
(5, 'Karar verirken bağlamı **dikkate almamız** lazım.', 'We must **take into account** the context when deciding.', 'Vi måste **ta hänsyn till** sammanhanget när vi beslutar.', 'Wir müssen den Kontext **berücksichtigen** wenn wir entscheiden.', '["dikkate almamız"]', '["take into account"]', '["ta hänsyn till"]', '["berücksichtigen"]', 'intermediate', false, 135),
(5, 'Uzun vadeli çözümler **yerine** kısa vadeli önlemler alındı.', 'Short-term measures were taken **rather than** long-term solutions.', 'Kortsiktiga åtgärder vidtogs **snarare än** långsiktiga lösningar.', 'Kurzfristige Maßnahmen wurden **anstatt** langfristiger Lösungen ergriffen.', '["yerine"]', '["rather than"]', '["snarare än"]', '["anstatt"]', 'intermediate', false, 136),
(5, 'Sonuç **ne olursa olsun**, araştırmaya devam ettik.', '**Regardless of** the result, we continued our research.', '**Oavsett** resultatet fortsatte vi vår forskning.', '**Ungeachtet** des Ergebnisses setzten wir unsere Forschung fort.', '["ne olursa olsun"]', '["regardless of"]', '["oavsett"]', '["ungeachtet"]', 'intermediate', false, 137),
(5, 'Koşullar sağlandığı **sürece** deney geçerli.', 'The experiment is valid **provided that** conditions are met.', 'Experimentet är giltigt **förutsatt att** villkoren uppfylls.', 'Das Experiment ist gültig, **vorausgesetzt** die Bedingungen sind erfüllt.', '["sürece"]', '["provided that"]', '["förutsatt att"]', '["vorausgesetzt"]', 'intermediate', false, 138),
(5, 'Bu bulgu konuya **ışık tutuyor**.', 'This finding **sheds light on** the issue.', 'Det här fyndet **kastar ljus på** problemet.', 'Dieser Befund **beleuchtet** das Thema.', '["ışık tutuyor"]', '["sheds light on"]', '["kastar ljus på"]', '["beleuchtet"]', 'intermediate', false, 139),
(5, '**Belirtmek gerekir ki**, yöntemler tartışmalı.', '**It is worth noting** that the methods are debatable.', 'Det är **värt att notera** att metoderna är diskutabla.', 'Es ist **erwähnenswert**, dass die Methoden umstritten sind.', '["belirtmek gerekir ki"]', '["it is worth noting"]', '["värt att notera"]', '["erwähnenswert"]', 'intermediate', false, 140),

-- Advanced
(5, 'Bu çalışma etik **bağlamında** inceleniyor.', 'This study is examined **with regard to** ethics.', 'Den här studien granskas **med avseende på** etik.', 'Diese Studie wird **hinsichtlich** der Ethik untersucht.', '["bağlamında"]', '["with regard to"]', '["med avseende på"]', '["hinsichtlich"]', 'advanced', false, 141),
(5, 'Çalışma, mevcut boşluklara **dikkat çekiyor**.', 'The study **draws attention to** existing gaps.', 'Studien **uppmärksammar** befintliga luckor.', 'Die Studie **lenkt die Aufmerksamkeit** auf bestehende Lücken.', '["dikkat çekiyor"]', '["draws attention to"]', '["uppmärksammar"]', '["lenkt Aufmerksamkeit"]', 'advanced', false, 142),
(5, 'Bu yöntem önceki yaklaşımın **aksine** daha verimli.', '**In contrast to** the previous approach, this method is more efficient.', '**I kontrast till** den tidigare metoden är det här effektivare.', '**Im Gegensatz zum** vorherigen Ansatz ist diese Methode effizienter.', '["aksine"]', '["in contrast to"]', '["i kontrast till"]', '["im Gegensatz zu"]', 'advanced', false, 143),
(5, 'Proje gecikmesi **yüzünden** bütçe aşıldı.', '**Due to** the project delay, the budget was exceeded.', '**På grund av** projektförseningen överskreds budgeten.', '**Aufgrund** der Projektverzögerung wurde das Budget überschritten.', '["yüzünden"]', '["due to"]', '["på grund av"]', '["aufgrund"]', 'advanced', false, 144),
(5, 'Yüksek maliyetler yatırımın düşmesine **yol açtı**.', 'The high costs **led to** a drop in investment.', 'De höga kostnaderna **ledde till** en minskning av investeringarna.', 'Die hohen Kosten **führten zu** einem Rückgang der Investitionen.', '["yol açtı"]', '["led to"]', '["ledde till"]', '["führten zu"]', 'advanced', false, 145),
(5, 'Uzun süreli alan araştırması **yürüttüler**.', 'They **carried out** extensive field research.', 'De **genomförde** omfattande fältforskning.', 'Sie haben umfangreiche Feldforschung **durchgeführt**.', '["yürüttüler"]', '["carried out"]', '["genomförde"]', '["durchgeführt"]', 'advanced', false, 146),
(5, 'Uzmanlar nihayet bir **sonuca vardı**.', 'The experts finally **came to a conclusion**.', 'Experterna **nådde slutligen en slutsats**.', 'Die Experten **kamen schließlich zu einem Schluss**.', '["sonuca vardı"]', '["came to a conclusion"]', '["nådde en slutsats"]', '["kamen zu einem Schluss"]', 'advanced', false, 147),
(5, 'Bu fenomen **büyük ölçüde** ekonomik faktörlerle açıklanıyor.', 'This phenomenon is explained **to a large extent** by economic factors.', 'Det här fenomenet förklaras **till stor del** av ekonomiska faktorer.', 'Dieses Phänomen wird **weitgehend** durch wirtschaftliche Faktoren erklärt.', '["büyük ölçüde"]', '["to a large extent"]', '["till stor del"]', '["weitgehend"]', 'advanced', false, 148),
(5, 'Araştırma ve öğretim **aynı anda** yürütülüyor.', 'Research and teaching are conducted **at the same time**.', 'Forskning och undervisning bedrivs **samtidigt**.', 'Forschung und Lehre werden **gleichzeitig** durchgeführt.', '["aynı anda"]', '["at the same time"]', '["samtidigt"]', '["gleichzeitig"]', 'advanced', false, 149),
(5, 'Yeni bir teori **öne sürdüler**.', 'They **put forward** a new theory.', 'De **lade fram** en ny teori.', 'Sie haben eine neue Theorie **vorgelegt**.', '["öne sürdüler"]', '["put forward"]', '["lade fram"]', '["vorgelegt"]', 'advanced', false, 150);

-- ─── CATEGORY 6 — İdiomlar ──────────────────────────────────────────────────

INSERT INTO sentences (category_id, text_tr, text_en, text_sv, text_de, keywords_tr, keywords_en, keywords_sv, keywords_de, difficulty, is_free, sort_order) VALUES

-- Beginner
(6, 'Acı veriyor ama **dişimi sıkıp** devam ediyorum.', 'It hurts but I''m **biting the bullet** and continuing.', 'Det gör ont men jag **biter ihop** och fortsätter.', 'Es tut weh, aber ich **beiße die Zähne zusammen** und mache weiter.', '["dişimi sıkıp"]', '["biting the bullet"]', '["biter ihop"]', '["beiße die Zähne zusammen"]', 'beginner', false, 151),
(6, 'O kadar utangaç ki toplantılarda **ortalığı ısıtmak** bile zor.', 'He''s so shy that it''s hard to even **break the ice** in meetings.', 'Han är så blyg att det är svårt att ens **bryta isen** på möten.', 'Er ist so schüchtern, dass es schwer ist, in Meetings das **Eis zu brechen**.', '["ortalığı ısıtmak"]', '["break the ice"]', '["bryta isen"]', '["Eis zu brechen"]', 'beginner', false, 152),
(6, 'Sahneye çıkmadan önce **soğuk ayak aldım**.', 'I **got cold feet** right before going on stage.', 'Jag **fick kalla fötter** precis innan jag gick upp på scenen.', 'Ich habe kurz vor dem Auftritt **kalte Füße bekommen**.', '["soğuk ayak aldım"]', '["got cold feet"]', '["fick kalla fötter"]', '["kalte Füße bekommen"]', 'beginner', false, 153),
(6, 'Tam **çiviyi başına çaktın** — bu sorunun özü bu.', 'You''ve really **hit the nail on the head** — that''s exactly the problem.', 'Du **slog huvudet på spiken** — det är precis problemet.', 'Du hast den **Nagel auf den Kopf getroffen** — das ist genau das Problem.', '["çiviyi başına çaktın"]', '["hit the nail on the head"]', '["slog huvudet på spiken"]', '["Nagel auf den Kopf getroffen"]', 'beginner', false, 154),
(6, 'Dikkat et, **kedileri poşetten çıkardın** yani sırrı ele verdin.', 'Be careful — you just **let the cat out of the bag**.', 'Var försiktig — du **sladdrade** precis.', 'Sei vorsichtig — du hast gerade die **Katze aus dem Sack gelassen**.', '["kedileri poşetten çıkardın"]', '["let the cat out of the bag"]', '["sladdrade"]', '["Katze aus dem Sack gelassen"]', 'beginner', false, 155),
(6, 'Bu konuda hiç **aynı fikirde olamıyoruz**.', 'We never **see eye to eye** on this issue.', 'Vi är aldrig **överens** i den här frågan.', 'Wir sind in dieser Sache nie **einer Meinung**.', '["aynı fikirde olamıyoruz"]', '["see eye to eye"]', '["överens"]', '["einer Meinung"]', 'beginner', false, 156),
(6, 'Bu sorun **buzdağının görünen kısmı** sadece.', 'This problem is just **the tip of the iceberg**.', 'Det här problemet är bara **toppen av isberget**.', 'Dieses Problem ist nur **die Spitze des Eisbergs**.', '["buzdağının görünen kısmı"]', '["the tip of the iceberg"]', '["toppen av isberget"]', '["die Spitze des Eisbergs"]', 'beginner', false, 157),
(6, 'Sırrı ele verdi — **fasulyeyi döktü**.', 'He gave away the secret — he **spilled the beans**.', 'Han avslöjade hemligheten — han **sladde**.', 'Er hat das Geheimnis verraten — er hat **die Bohnen verschüttet**.', '["fasulyeyi döktü"]', '["spilled the beans"]', '["sladde"]', '["die Bohnen verschüttet"]', 'beginner', false, 158),
(6, 'Bu adı bir yerden biliyorum — bir **zil çalıyor** aklımda.', 'I know this name from somewhere — it **rings a bell**.', 'Jag känner igen det här namnet — det **klingar bekant**.', 'Ich kenne diesen Namen von irgendwo — das **klingt bekannt**.', '["zil çalıyor"]', '["rings a bell"]', '["klingar bekant"]', '["klingt bekannt"]', 'beginner', false, 159),
(6, '**Parmakları çapraz tut**, umarım kazanırız.', '**Keep your fingers crossed** — I hope we win.', '**Håll tummarna** — jag hoppas vi vinner.', 'Halte die **Daumen gedrückt** — ich hoffe, wir gewinnen.', '["parmakları çapraz tut"]', '["keep your fingers crossed"]', '["håll tummarna"]', '["Daumen gedrückt"]', 'beginner', false, 160),

-- Intermediate
(6, '**Arada bir** sinemaya gidiyoruz.', 'We go to the cinema **once in a while**.', 'Vi går på bio **ibland**.', 'Wir gehen **ab und zu** ins Kino.', '["arada bir"]', '["once in a while"]', '["ibland"]', '["ab und zu"]', 'intermediate', false, 161),
(6, 'O teklif **aniden, hiç beklenmedik şekilde** geldi.', 'That offer came completely **out of the blue**.', 'Det erbjudandet kom helt **ur det blå**.', 'Dieses Angebot kam völlig **aus dem Nichts**.', '["aniden, hiç beklenmedik şekilde"]', '["out of the blue"]', '["ur det blå"]', '["aus dem Nichts"]', 'intermediate', false, 162),
(6, '**Bir anda** her şey değişti.', '**All of a sudden**, everything changed.', '**Plötsligt** förändrades allt.', '**Auf einmal** änderte sich alles.', '["bir anda"]', '["all of a sudden"]', '["plötsligt"]', '["auf einmal"]', 'intermediate', false, 163),
(6, 'Bu araba **çok pahalıya mal oldu**.', 'This car **cost an arm and a leg**.', 'Den här bilen **kostade en förmögenhet**.', 'Dieses Auto hat **ein Vermögen gekostet**.', '["çok pahalıya mal oldu"]', '["cost an arm and a leg"]', '["kostade en förmögenhet"]', '["ein Vermögen gekostet"]', 'intermediate', false, 164),
(6, '**Zaman zaman** parkta yürüyüş yapıyorum.', 'I go for walks in the park **every now and then**.', 'Jag går på promenad i parken **då och då**.', 'Ich mache **ab und zu** Spaziergänge im Park.', '["zaman zaman"]', '["every now and then"]', '["då och då"]', '["ab und zu"]', 'intermediate', false, 165),
(6, 'Bu sınav benim için **çocuk oyuncağı** oldu.', 'This exam was **a piece of cake** for me.', 'Det här provet var **en lätt match** för mig.', 'Diese Prüfung war für mich **ein Kinderspiel**.', '["çocuk oyuncağı"]', '["a piece of cake"]', '["en lätt match"]', '["ein Kinderspiel"]', 'intermediate', false, 166),
(6, 'Bugün **kendimi iyi hissetmiyorum**, hasta gibiyim.', 'I''m feeling **under the weather** today.', 'Jag mår **lite dåligt** idag.', 'Ich **fühle mich heute nicht gut**.', '["kendimi iyi hissetmiyorum"]', '["under the weather"]', '["lite dåligt"]', '["fühle mich nicht gut"]', 'intermediate', false, 167),
(6, 'Bu teklif için bir kez **denemeye değer**.', 'It''s worth **giving it a shot** once.', 'Det är värt att **ge det ett försök** en gång.', 'Es ist einen Versuch wert, es **auszuprobieren**.', '["denemeye değer"]', '["giving it a shot"]', '["ge det ett försök"]', '["auszuprobieren"]', 'intermediate', false, 168),
(6, 'Bu konuda hâlâ **kararsız** kalıyorum.', 'I''m still **on the fence** about this.', 'Jag är fortfarande **tveksam** till det här.', 'Ich bin in dieser Sache noch **unentschlossen**.', '["kararsız"]', '["on the fence"]', '["tveksam"]', '["unentschlossen"]', 'intermediate', false, 169),
(6, 'O davranışınla köprüleri **yaktın**.', 'With that behaviour you **burned your bridges**.', 'Med det beteendet **brände du dina broar**.', 'Mit diesem Verhalten hast du alle **Brücken hinter dir verbrannt**.', '["yaktın"]', '["burned your bridges"]', '["brände dina broar"]', '["Brücken verbrannt"]', 'intermediate', false, 170),

-- Advanced
(6, 'Fırsatı **kaçırdın**, uçak kalkmış zaten.', 'You **missed the boat** — the plane has already left.', 'Du **missade chansen** — flyget har redan åkt.', 'Du hast den **Zug verpasst** — das Flugzeug ist schon weg.', '["kaçırdın"]', '["missed the boat"]', '["missade chansen"]', '["Zug verpasst"]', 'advanced', false, 171),
(6, 'Beni **kandırmaya çalışıyor**, ciddiye alma.', 'He''s just **pulling my leg**, don''t take it seriously.', 'Han **skojar bara med mig**, ta det inte på allvar.', 'Er **verarscht mich nur**, nimm das nicht ernst.', '["kandırmaya çalışıyor"]', '["pulling my leg"]', '["skojar med mig"]', '["verarscht mich"]', 'advanced', false, 172),
(6, 'Durum kontrolden **çıktı**.', 'The situation **got out of hand**.', 'Situationen **gick ur kontroll**.', 'Die Situation **geriet außer Kontrolle**.', '["kontrolden çıktı"]', '["got out of hand"]', '["gick ur kontroll"]', '["außer Kontrolle"]', 'advanced', false, 173),
(6, 'Mesajda **satır aralarını okumalısın**.', 'You need to **read between the lines** of the message.', 'Du måste **läsa mellan raderna** i meddelandet.', 'Du musst in der Nachricht **zwischen den Zeilen lesen**.', '["satır aralarını okumalısın"]', '["read between the lines"]', '["läsa mellan raderna"]', '["zwischen den Zeilen lesen"]', 'advanced', false, 174),
(6, '**Top artık sende** — sen karar ver.', '**The ball is in your court** now — you decide.', '**Bollen är nu hos dig** — du bestämmer.', '**Der Ball liegt nun bei dir** — du entscheidest.', '["top artık sende"]', '["the ball is in your court"]', '["bollen är hos dig"]', '["der Ball liegt bei dir"]', 'advanced', false, 175),
(6, 'Üstlendiğin sorumluluk fazla; **ağzından büyük lokmalar alıyorsun**.', 'You''re **biting off more than you can chew** with these responsibilities.', 'Du **tar på dig mer än du kan hantera** med de här ansvarsområdena.', 'Du **beißt mehr ab, als du kauen kannst** mit diesen Verantwortlichkeiten.', '["ağzından büyük lokmalar alıyorsun"]', '["biting off more than you can chew"]', '["tar på dig mer än du kan hantera"]', '["beißt mehr ab als kauen kannst"]', 'advanced', false, 176),
(6, '**Eylemler sözcüklerden daha yüksek sesle konuşur**.', '**Actions speak louder than words**.', '**Handlingar talar högre än ord**.', '**Taten sprechen lauter als Worte**.', '["eylemler sözcüklerden daha yüksek sesle konuşur"]', '["actions speak louder than words"]', '["handlingar talar högre än ord"]', '["Taten sprechen lauter als Worte"]', 'advanced', false, 177),
(6, 'Konuyu doğrudan söylemiyor; **etrafında dolaşıyor**.', 'He''s not saying it directly; he''s **beating around the bush**.', 'Han säger det inte direkt; han **går runt het gröt**.', 'Er sagt es nicht direkt; er **redet um den heißen Brei herum**.', '["etrafında dolaşıyor"]', '["beating around the bush"]', '["går runt het gröt"]', '["redet um den heißen Brei herum"]', 'advanced', false, 178),
(6, 'Tartışmaya katılman **ateşe körük olur**.', 'Joining the argument would be **adding fuel to the fire**.', 'Att gå med i argumentet vore att **hälla bensin på brasan**.', 'Sich der Diskussion anzuschließen wäre **Öl ins Feuer gießen**.', '["ateşe körük olur"]', '["adding fuel to the fire"]', '["hälla bensin på brasan"]', '["Öl ins Feuer gießen"]', 'advanced', false, 179),
(6, 'Herkes biliyor ama kimse konuşmuyor — **odadaki fil**.', 'Everyone knows but nobody talks about it — **the elephant in the room**.', 'Alla vet men ingen pratar om det — **elefanten i rummet**.', 'Alle wissen es, aber keiner spricht darüber — **der Elefant im Raum**.', '["odadaki fil"]', '["the elephant in the room"]', '["elefanten i rummet"]', '["der Elefant im Raum"]', 'advanced', false, 180);
