-- Seed sentences for categories 7-9 (90 sentences total)
-- Category 7: Gramer Kalıpları / Grammar Patterns (30 sentences, is_free: false)
-- Category 8: Teknoloji / Technology (30 sentences, is_free: false)
-- Category 9: Sağlık / Health (30 sentences, is_free: false)
-- Each sentence teaches ONE key phrase/expression marked with **phrase**

-- ─────────────────────────────────────────────────────────────────
-- Category 7: Gramer Kalıpları — Beginner (10 sentences)
-- ─────────────────────────────────────────────────────────────────
INSERT INTO sentences (category_id, text_tr, text_en, text_sv, text_de, keywords_tr, keywords_en, keywords_sv, keywords_de, difficulty, is_free, sort_order) VALUES
(7, 'Eskiden her sabah koşmaya **alışkındım**.', 'I **used to** run every morning.', 'Jag **brukade** springa varje morgon.', 'Ich **pflegte** jeden Morgen zu laufen.', '["alışkındım"]', '["used to"]', '["brukade"]', '["pflegte"]', 'beginner', false, 271),
(7, 'Tam gitmek **üzereydim** ki telefon çaldı.', 'I was **about to** leave when the phone rang.', 'Jag var **på väg att** gå när telefonen ringde.', 'Ich war **im Begriff** zu gehen, als das Telefon klingelte.', '["üzereydim"]', '["about to"]', '["på väg att"]', '["im Begriff"]', 'beginner', false, 272),
(7, '**Eve gelir gelmez** seni arayacağım.', 'I will call you **as soon as** I get home.', 'Jag ringer dig **så snart** jag kommer hem.', 'Ich rufe dich an, **sobald** ich zu Hause bin.', '["eve gelir gelmez"]', '["as soon as"]', '["så snart"]', '["sobald"]', 'beginner', false, 273),
(7, '**Yorgun olmasına rağmen** çalışmaya devam etti.', '**Even though** she was tired, she kept working.', '**Även om** hon var trött fortsatte hon att arbeta.', '**Obwohl** sie müde war, arbeitete sie weiter.', '["yorgun olmasına rağmen"]', '["even though"]', '["även om"]', '["obwohl"]', 'beginner', false, 274),
(7, 'Sessiz **olduğun sürece** burada kalabilirsin.', 'You can stay here **as long as** you are quiet.', 'Du kan stanna här **så länge** du är tyst.', 'Du kannst hier bleiben, **solange** du ruhig bist.', '["olduğun sürece"]', '["as long as"]', '["så länge"]', '["solange"]', 'beginner', false, 275),
(7, 'Buraya gitmek **yerine** evde kalmayı tercih ederim.', 'I **would rather** stay home than go there.', 'Jag **skulle hellre** stanna hemma än gå dit.', 'Ich **würde lieber** zu Hause bleiben als dort hingehen.', '["yerine"]', '["would rather"]', '["skulle hellre"]', '["würde lieber"]', 'beginner', false, 276),
(7, 'Geç kalmadan önce **çıksan iyi olur**.', 'You **had better** leave before you are late.', 'Du **borde** gå innan du blir sen.', 'Du **solltest besser** gehen, bevor du zu spät bist.', '["çıksan iyi olur"]', '["had better"]', '["borde"]', '["solltest besser"]', 'beginner', false, 277),
(7, '**Keşke** daha erken başlasaydım.', 'I **wish** I had started earlier.', 'Jag **önskar** att jag hade börjat tidigare.', 'Ich **wünschte**, ich hätte früher angefangen.', '["keşke"]', '["wish"]', '["önskar"]', '["wünschte"]', 'beginner', false, 278),
(7, 'Bu saat eve **gitme vakti**.', 'It''s **time to** go home.', 'Det är **dags att** gå hem.', 'Es ist **Zeit**, nach Hause zu gehen.', '["gitme vakti"]', '["time to"]', '["dags att"]', '["Zeit"]', 'beginner', false, 279),
(7, 'Sınavı geçmek için çok çalışmam **gerekiyor**.', 'I **need to** study a lot to pass the exam.', 'Jag **behöver** studera mycket för att klara provet.', 'Ich **muss** viel lernen, um die Prüfung zu bestehen.', '["gerekiyor"]', '["need to"]', '["behöver"]', '["muss"]', 'beginner', false, 280);

-- Category 7: Gramer Kalıpları — Intermediate (10 sentences)
INSERT INTO sentences (category_id, text_tr, text_en, text_sv, text_de, keywords_tr, keywords_en, keywords_sv, keywords_de, difficulty, is_free, sort_order) VALUES
(7, 'O **sadece** İngilizce değil, Fransızca da konuşuyor.', '**Not only** does she speak English, **but also** French.', '**Inte bara** talar hon engelska, **utan också** franska.', '**Nicht nur** spricht sie Englisch, **sondern auch** Französisch.', '["sadece değil aynı zamanda"]', '["not only but also"]', '["inte bara utan också"]', '["nicht nur sondern auch"]', 'intermediate', false, 281),
(7, 'O kadar yoruldum ki **yerinden bile kalkamadım**.', 'I was **so** tired **that** I couldn''t even get up.', 'Jag var **så** trött **att** jag inte ens kunde resa mig.', 'Ich war **so** müde, **dass** ich mich nicht mal aufstehen konnte.', '["o kadar ki"]', '["so that"]', '["så att"]', '["so dass"]', 'intermediate', false, 282),
(7, 'İnsanlar stres altında **hata yapmaya meyillidir**.', 'People **tend to** make mistakes under stress.', 'Människor **tenderar att** göra misstag under stress.', 'Menschen **neigen dazu**, unter Stress Fehler zu machen.', '["meyillidir"]', '["tend to"]', '["tenderar att"]', '["neigen dazu"]', 'intermediate', false, 283),
(7, 'Toplantı saat 10''da **başlaması gerekiyor**.', 'The meeting **is supposed to** start at 10.', 'Mötet **är tänkt att** börja klockan 10.', 'Das Meeting **soll** um 10 Uhr beginnen.', '["başlaması gerekiyor"]', '["is supposed to"]', '["är tänkt att"]', '["soll"]', 'intermediate', false, 284),
(7, 'Seninle biraz konuşmak **istiyorum**.', 'I **would like to** talk to you for a moment.', 'Jag **skulle vilja** prata med dig ett ögonblick.', 'Ich **würde gerne** kurz mit dir sprechen.', '["istiyorum"]', '["would like to"]', '["skulle vilja"]', '["würde gerne"]', 'intermediate', false, 285),
(7, '**Ne olursa olsun** pes etmeyeceğim.', '**No matter what**, I will not give up.', '**Oavsett vad** som händer ger jag inte upp.', '**Egal was passiert**, ich werde nicht aufgeben.', '["ne olursa olsun"]', '["no matter what"]', '["oavsett vad"]', '["egal was"]', 'intermediate', false, 286),
(7, 'Anahtarı kaybetmeye karşı bir yedek yanımda taşıyorum **diye**.', 'I carry a spare key **in case** I lose mine.', 'Jag bär en reservnyckel **ifall** jag tappar bort min.', 'Ich trage einen Ersatzschlüssel **für den Fall**, dass ich meinen verliere.', '["diye"]', '["in case"]', '["ifall"]', '["für den Fall"]', 'intermediate', false, 287),
(7, '**Yeterince çalışman koşuluyla** başarabilirsin.', 'You can succeed **provided that** you work hard enough.', 'Du kan lyckas **förutsatt att** du arbetar tillräckligt hårt.', 'Du kannst erfolgreich sein, **vorausgesetzt** du arbeitest hart genug.', '["koşuluyla"]', '["provided that"]', '["förutsatt att"]', '["vorausgesetzt"]', 'intermediate', false, 288),
(7, '**İzin almadıkça** odaya giremezsin.', 'You cannot enter the room **unless** you have permission.', 'Du kan inte gå in i rummet **om inte** du har tillstånd.', 'Du kannst den Raum nicht betreten, **es sei denn** du hast eine Erlaubnis.', '["almadıkça"]', '["unless"]', '["om inte"]', '["es sei denn"]', 'intermediate', false, 289),
(7, '**Hem çalışıyor hem de** okula gidiyor.', '**Both** she works **and** goes to school.', 'Hon **både** jobbar **och** går i skolan.', 'Sie **sowohl** arbeitet **als auch** geht zur Schule.', '["hem hem de"]', '["both and"]', '["både och"]', '["sowohl als auch"]', 'intermediate', false, 290);

-- Category 7: Gramer Kalıpları — Advanced (10 sentences)
INSERT INTO sentences (category_id, text_tr, text_en, text_sv, text_de, keywords_tr, keywords_en, keywords_sv, keywords_de, difficulty, is_free, sort_order) VALUES
(7, '**Ne o ne de** ben o toplantıya katıldık.', '**Neither** he **nor** I attended that meeting.', '**Varken** han **eller** jag deltog i det mötet.', '**Weder** er **noch** ich nahmen an dem Meeting teil.', '["ne ne de"]', '["neither nor"]', '["varken eller"]', '["weder noch"]', 'advanced', false, 291),
(7, '**Eve geldiğinde** herkes zaten uyumuştu.', '**By the time** she got home, everyone was already asleep.', '**Vid det laget** hon kom hem sov alla redan.', '**Als** sie nach Hause kam, schliefen alle schon.', '["geldiğinde"]', '["by the time"]', '["vid det laget"]', '["als"]', 'advanced', false, 292),
(7, '**Ya parasını ödeseydin**, ne yapardın?', '**What if** you couldn''t pay the bill?', '**Tänk om** du inte kunde betala räkningen?', '**Was wäre, wenn** du die Rechnung nicht bezahlen könntest?', '["ya ödeseydin"]', '["what if"]', '["tänk om"]', '["was wäre wenn"]', 'advanced', false, 293),
(7, '**Ne kadar çok çalışırsan**, o kadar çok başarırsın.', '**The more** you practice, **the better** you get.', '**Ju mer** du övar, **desto bättre** blir du.', '**Je mehr** du übst, **desto besser** wirst du.', '["ne kadar o kadar"]', '["the more the better"]', '["ju mer desto bättre"]', '["je mehr desto besser"]', 'advanced', false, 294),
(7, '**Artık** bu sorunu çözme zamanı.', 'It''s **about time** we solved this problem.', 'Det är **hög tid** att vi löser det här problemet.', 'Es wird **höchste Zeit**, dieses Problem zu lösen.', '["artık zamanı"]', '["about time"]', '["hög tid"]', '["höchste Zeit"]', 'advanced', false, 295),
(7, 'Sanki hiç olmamış **gibi davranıyordu**.', 'He talked **as if** nothing had happened.', 'Han pratade **som om** ingenting hade hänt.', 'Er redete, **als ob** nichts passiert wäre.', '["gibi"]', '["as if"]', '["som om"]', '["als ob"]', 'advanced', false, 296),
(7, '**Zamanında teslim etmek koşuluyla** projeyi kabul ederim.', 'I will accept the project **on condition that** it is delivered on time.', 'Jag accepterar projektet **under förutsättning att** det levereras i tid.', 'Ich nehme das Projekt **unter der Bedingung** an, dass es pünktlich geliefert wird.', '["koşuluyla"]', '["on condition that"]', '["under förutsättning att"]', '["unter der Bedingung"]', 'advanced', false, 297),
(7, 'Seni uyarmadan **önce** bir şey söylemezdim.', 'I would **not** say anything **until** I warned you.', 'Jag skulle **inte** säga något **förrän** jag varnade dig.', 'Ich würde nichts sagen, **bis** ich dich gewarnt habe.', '["önce değil"]', '["not until"]', '["inte förrän"]', '["bis"]', 'advanced', false, 298),
(7, '**Sınav olmasaydı** bu kadar çalışmazdım.', '**Were it not for** the exam, I would not study this much.', '**Om det inte vore för** provet skulle jag inte studera så här mycket.', '**Wäre es nicht** für die Prüfung, würde ich nicht so viel lernen.', '["olmasaydı"]', '["were it not for"]', '["om det inte vore för"]', '["wäre es nicht für"]', 'advanced', false, 299),
(7, 'Daha iyi anlamak **için** örnekler kullanıyorum.', 'I use examples **in order to** understand better.', 'Jag använder exempel **för att** förstå bättre.', 'Ich benutze Beispiele, **um** besser zu verstehen.', '["için"]', '["in order to"]', '["för att"]', '["um zu"]', 'advanced', false, 300);

-- ─────────────────────────────────────────────────────────────────
-- Category 8: Teknoloji — Beginner (10 sentences)
-- ─────────────────────────────────────────────────────────────────
INSERT INTO sentences (category_id, text_tr, text_en, text_sv, text_de, keywords_tr, keywords_en, keywords_sv, keywords_de, difficulty, is_free, sort_order) VALUES
(8, 'Hesabına **giriş yap**.', '**Log in** to your account.', '**Logga in** på ditt konto.', '**Melde dich an** bei deinem Konto.', '["giriş yap"]', '["log in"]', '["logga in"]', '["melde dich an"]', 'beginner', false, 301),
(8, 'Yeni bir hesap **oluştur**.', '**Sign up** for a new account.', '**Skapa** ett nytt konto.', '**Registriere dich** für ein neues Konto.', '["oluştur"]', '["sign up"]', '["skapa"]', '["registriere dich"]', 'beginner', false, 302),
(8, 'Dosyalarını düzenli olarak **yedekle**.', '**Back up** your files regularly.', '**Säkerhetskopiera** dina filer regelbundet.', '**Sichere** deine Dateien regelmäßig.', '["yedekle"]', '["back up"]', '["säkerhetskopiera"]', '["sichere"]', 'beginner', false, 303),
(8, 'Kullanmayı bitirince hesabından **çıkış yap**.', '**Log out** when you are done.', '**Logga ut** när du är klar.', '**Melde dich ab**, wenn du fertig bist.', '["çıkış yap"]', '["log out"]', '["logga ut"]', '["melde dich ab"]', 'beginner', false, 304),
(8, 'Şarj cihazını **tak**.', '**Plug in** the charger.', '**Koppla in** laddaren.', '**Schließe** das Ladegerät **an**.', '["tak"]', '["plug in"]', '["koppla in"]', '["schließe an"]', 'beginner', false, 305),
(8, 'Uygulamayı App Store''dan **indir**.', '**Download** the app from the App Store.', '**Ladda ner** appen från App Store.', '**Lade** die App aus dem App Store **herunter**.', '["indir"]', '["download"]', '["ladda ner"]', '["herunter laden"]', 'beginner', false, 306),
(8, 'Fotoğrafı buluta **yükle**.', '**Upload** the photo to the cloud.', '**Ladda upp** fotot till molnet.', '**Lade** das Foto in die Cloud **hoch**.', '["yükle"]', '["upload"]', '["ladda upp"]', '["hochladen"]', 'beginner', false, 307),
(8, 'O gönderiyi arkadaşınla **paylaş**.', '**Share** that post with your friend.', '**Dela** det inlägget med din vän.', '**Teile** diesen Beitrag mit deinem Freund.', '["paylaş"]', '["share"]', '["dela"]', '["teile"]', 'beginner', false, 308),
(8, 'Akışı aşağı **kaydır**.', '**Scroll** down the feed.', '**Skrolla** nedåt i flödet.', '**Scrolle** im Feed nach unten.', '["kaydır"]', '["scroll"]', '["skrolla"]', '["scrolle"]', 'beginner', false, 309),
(8, 'Bildirimi okumak için **üzerine dokun**.', '**Tap on** the notification to read it.', '**Tryck på** aviseringen för att läsa den.', '**Tippe auf** die Benachrichtigung, um sie zu lesen.', '["üzerine dokun"]', '["tap on"]', '["tryck på"]', '["tippe auf"]', 'beginner', false, 310);

-- Category 8: Teknoloji — Intermediate (10 sentences)
INSERT INTO sentences (category_id, text_tr, text_en, text_sv, text_de, keywords_tr, keywords_en, keywords_sv, keywords_de, difficulty, is_free, sort_order) VALUES
(8, 'O video kısa sürede **viral oldu**.', 'That video **went viral** overnight.', 'Den videon **gick viralt** över en natt.', 'Dieses Video **ging viral** über Nacht.', '["viral oldu"]', '["went viral"]', '["gick viralt"]', '["ging viral"]', 'intermediate', false, 311),
(8, 'Telefonumun depolama alanı **dolmak üzere**.', 'My phone''s storage is **about to run out**.', 'Mitt telefons lagring håller på att **ta slut**.', 'Der Speicher meines Handys ist dabei, **voll zu werden**.', '["dolmak üzere"]', '["run out"]', '["ta slut"]', '["voll werden"]', 'intermediate', false, 312),
(8, 'Yeni yazıcıyı bilgisayara **bağlayıp yapılandırdım**.', 'I **set up** the new printer on my computer.', 'Jag **konfigurerade** den nya skrivaren på min dator.', 'Ich habe den neuen Drucker am Computer **eingerichtet**.', '["bağlayıp yapılandırdım"]', '["set up"]', '["konfigurerade"]', '["eingerichtet"]', 'intermediate', false, 313),
(8, 'Güvenlik açıklarını kapatmak için uygulamayı **güncelle**.', '**Update** the app to fix security issues.', '**Uppdatera** appen för att åtgärda säkerhetsproblem.', '**Aktualisiere** die App, um Sicherheitsprobleme zu beheben.', '["güncelle"]', '["update"]', '["uppdatera"]', '["aktualisiere"]', 'intermediate', false, 314),
(8, 'Android''den iPhone''a **geçtim**.', 'I **switched to** iPhone from Android.', 'Jag **bytte till** iPhone från Android.', 'Ich habe **auf** iPhone **gewechselt** von Android.', '["geçtim"]', '["switched to"]', '["bytte till"]', '["gewechselt auf"]', 'intermediate', false, 315),
(8, 'Takvimini telefonunla **eşitle**.', '**Sync** your calendar with your phone.', '**Synkronisera** din kalender med din telefon.', '**Synchronisiere** deinen Kalender mit deinem Handy.', '["eşitle"]', '["sync"]', '["synkronisera"]', '["synchronisiere"]', 'intermediate', false, 316),
(8, 'Uygulama sürekli **çöküyor**, yeniden yüklemem gerekiyor.', 'The app keeps **crashing**, I need to reinstall it.', 'Appen håller på att **krascha**, jag behöver installera om den.', 'Die App **stürzt** ständig **ab**, ich muss sie neu installieren.', '["çöküyor"]', '["crashing"]', '["krascha"]', '["stürzt ab"]', 'intermediate', false, 317),
(8, 'Hesabını korumak için **iki faktörlü doğrulama** aç.', 'Enable **two-factor authentication** to protect your account.', 'Aktivera **tvåfaktorsautentisering** för att skydda ditt konto.', 'Aktiviere die **Zwei-Faktor-Authentifizierung**, um dein Konto zu schützen.', '["iki faktörlü doğrulama"]', '["two-factor authentication"]', '["tvåfaktorsautentisering"]', '["Zwei-Faktor-Authentifizierung"]', 'intermediate', false, 318),
(8, 'Cihazı Wi-Fi ağına **bağla**.', '**Connect** the device **to** the Wi-Fi network.', '**Anslut** enheten **till** Wi-Fi-nätverket.', '**Verbinde** das Gerät **mit** dem WLAN-Netzwerk.', '["bağla"]', '["connect to"]', '["anslut till"]', '["verbinde mit"]', 'intermediate', false, 319),
(8, 'Şifrenin en az 8 karakter **olması gerekiyor**.', 'Your password **needs to** have at least 8 characters.', 'Ditt lösenord **måste** ha minst 8 tecken.', 'Dein Passwort **muss** mindestens 8 Zeichen haben.', '["olması gerekiyor"]', '["needs to"]', '["måste"]', '["muss"]', 'intermediate', false, 320);

-- Category 8: Teknoloji — Advanced (10 sentences)
INSERT INTO sentences (category_id, text_tr, text_en, text_sv, text_de, keywords_tr, keywords_en, keywords_sv, keywords_de, difficulty, is_free, sort_order) VALUES
(8, 'Sistemin **saldırıya uğradığını** fark ettim.', 'I noticed the system **got hacked**.', 'Jag märkte att systemet **blev hackat**.', 'Ich bemerkte, dass das System **gehackt wurde**.', '["saldırıya uğradı"]', '["got hacked"]', '["blev hackat"]', '["gehackt wurde"]', 'advanced', false, 321),
(8, 'Sahte e-posta bağlantılarına tıklama: bu bir **kimlik avı saldırısı** olabilir.', 'Don''t click fake email links — it could be a **phishing attack**.', 'Klicka inte på falska e-postlänkar — det kan vara en **nätfiskeattack**.', 'Klicke nicht auf gefälschte E-Mail-Links — es könnte ein **Phishing-Angriff** sein.', '["kimlik avı saldırısı"]', '["phishing attack"]', '["nätfiskeattack"]', '["Phishing-Angriff"]', 'advanced', false, 322),
(8, 'O hesabı **engellemeyi kaldırdım** ve tekrar takip edebildim.', 'I **unblocked** that account and could follow again.', 'Jag **avblockerade** det kontot och kunde följa igen.', 'Ich habe das Konto **entsperrt** und konnte wieder folgen.', '["engellemeyi kaldırdım"]', '["unblocked"]', '["avblockerade"]', '["entsperrt"]', 'advanced', false, 323),
(8, 'Mesajlar **uçtan uca şifreli** olduğu için güvende.', 'Messages are safe because they are **end-to-end encrypted**.', 'Meddelandena är säkra eftersom de är **end-to-end-krypterade**.', 'Nachrichten sind sicher, weil sie **Ende-zu-Ende-verschlüsselt** sind.', '["uçtan uca şifreli"]', '["end-to-end encrypted"]', '["end-to-end-krypterade"]', '["Ende-zu-Ende-verschlüsselt"]', 'advanced', false, 324),
(8, 'Tüm belgelerimi **bulut depolamada** saklıyorum.', 'I keep all my documents in **cloud storage**.', 'Jag lagrar alla mina dokument i **molnlagring**.', 'Ich speichere alle meine Dokumente in der **Cloud**.', '["bulut depolamada"]', '["cloud storage"]', '["molnlagring"]', '["Cloud"]', 'advanced', false, 325),
(8, 'Sosyal medya **algoritması** ilgi alanlarına göre içerik önerir.', 'The social media **algorithm** recommends content based on your interests.', 'Sociala mediers **algoritm** rekommenderar innehåll baserat på dina intressen.', 'Der Social-Media-**Algorithmus** empfiehlt Inhalte basierend auf deinen Interessen.', '["algoritması"]', '["algorithm"]', '["algoritm"]', '["Algorithmus"]', 'advanced', false, 326),
(8, 'Bağlantı yavaş çünkü **bant genişliği** yetersiz.', 'The connection is slow because the **bandwidth** is limited.', 'Anslutningen är långsam eftersom **bandbredden** är begränsad.', 'Die Verbindung ist langsam, weil die **Bandbreite** begrenzt ist.', '["bant genişliği"]', '["bandwidth"]', '["bandbredden"]', '["Bandbreite"]', 'advanced', false, 327),
(8, 'Sorunun kaynağını bulmak için sistemi **gidermeye çalışıyorum**.', 'I am trying to **troubleshoot** the system to find the cause.', 'Jag försöker **felsöka** systemet för att hitta orsaken.', 'Ich versuche, das System zu **debuggen**, um die Ursache zu finden.', '["gidermeye çalışıyorum"]', '["troubleshoot"]', '["felsöka"]', '["debuggen"]', 'advanced', false, 328),
(8, 'Çocuklar için **ekran süresi** sınırı belirlemek önemli.', 'It is important to set a **screen time** limit for children.', 'Det är viktigt att sätta en gräns för **skärmtid** för barn.', 'Es ist wichtig, für Kinder eine **Bildschirmzeit**-Grenze festzulegen.', '["ekran süresi"]', '["screen time"]', '["skärmtid"]', '["Bildschirmzeit"]', 'advanced', false, 329),
(8, 'Zihnini temizlemek için bir hafta **dijital detoks** yapmaya karar verdim.', 'I decided to do a **digital detox** for a week to clear my mind.', 'Jag bestämde mig för att göra en **digital detox** i en vecka för att rensa mitt sinne.', 'Ich beschloss, eine Woche lang **Digital Detox** zu machen, um meinen Kopf frei zu bekommen.', '["dijital detoks"]', '["digital detox"]', '["digital detox"]', '["Digital Detox"]', 'advanced', false, 330);

-- ─────────────────────────────────────────────────────────────────
-- Category 9: Sağlık — Beginner (10 sentences)
-- ─────────────────────────────────────────────────────────────────
INSERT INTO sentences (category_id, text_tr, text_en, text_sv, text_de, keywords_tr, keywords_en, keywords_sv, keywords_de, difficulty, is_free, sort_order) VALUES
(9, 'Bugün biraz **keyifsiz hissediyorum**.', 'I **feel under the weather** today.', 'Jag **mår inte bra** idag.', 'Ich **fühle mich nicht gut** heute.', '["keyifsiz hissediyorum"]', '["feel under the weather"]', '["mår inte bra"]', '["fühle mich nicht gut"]', 'beginner', false, 331),
(9, 'Geçen hafta **soğuk aldım**.', 'I **caught a cold** last week.', 'Jag **fick en förkylning** förra veckan.', 'Ich habe mich letzte Woche **erkältet**.', '["soğuk aldım"]', '["caught a cold"]', '["fick en förkylning"]', '["erkältet"]', 'beginner', false, 332),
(9, 'Bütün gün **başım ağrıyor**.', 'I **have a headache** all day.', 'Jag har **huvudvärk** hela dagen.', 'Ich habe den ganzen Tag **Kopfschmerzen**.', '["başım ağrıyor"]', '["have a headache"]', '["huvudvärk"]', '["Kopfschmerzen"]', 'beginner', false, 333),
(9, 'Doktora göre hafif **ateşim var**.', 'According to the doctor, I have a mild **fever**.', 'Enligt läkaren har jag lätt **feber**.', 'Laut dem Arzt habe ich leichtes **Fieber**.', '["ateşim var"]', '["fever"]', '["feber"]', '["Fieber"]', 'beginner', false, 334),
(9, 'Hemen bir **doktora gitmelisin**.', 'You should **see a doctor** right away.', 'Du borde **gå till läkaren** direkt.', 'Du solltest sofort **zum Arzt gehen**.', '["doktora gitmelisin"]', '["see a doctor"]', '["gå till läkaren"]', '["zum Arzt gehen"]', 'beginner', false, 335),
(9, 'Birkaç güne kadar **iyileşeceğini** umuyorum.', 'I hope you **get better** in a few days.', 'Jag hoppas att du **mår bättre** om några dagar.', 'Ich hoffe, du **wirst bald besser** in ein paar Tagen.', '["iyileşeceğini"]', '["get better"]', '["mår bättre"]', '["wirst besser"]', 'beginner', false, 336),
(9, '**Kendinize iyi bakın**, geçmiş olsun.', '**Take care of yourself** and get well soon.', '**Ta hand om dig** och bli frisk snart.', '**Pass auf dich auf** und gute Besserung.', '["kendinize iyi bakın"]', '["take care of yourself"]', '["ta hand om dig"]', '["pass auf dich auf"]', 'beginner', false, 337),
(9, 'Ayağa kalktığımda **başım dönüyor**.', 'I **feel dizzy** when I stand up.', 'Jag **känner mig yr** när jag reser mig.', 'Mir wird **schwindelig**, wenn ich aufstehe.', '["başım dönüyor"]', '["feel dizzy"]', '["känner mig yr"]', '["schwindelig"]', 'beginner', false, 338),
(9, '**Boğazım ağrıyor** ve yutkunmakta güçlük çekiyorum.', 'I **have a sore throat** and difficulty swallowing.', 'Jag har **ont i halsen** och svårt att svälja.', 'Ich habe **Halsschmerzen** und Schwierigkeiten beim Schlucken.', '["boğazım ağrıyor"]', '["have a sore throat"]', '["ont i halsen"]', '["Halsschmerzen"]', 'beginner', false, 339),
(9, 'Dinlen ve bol su iç, **iyileşirsin**.', 'Rest and drink plenty of water, you will **feel better**.', 'Vila och drick mycket vatten, du kommer att **må bättre**.', 'Ruh dich aus und trink viel Wasser, du wirst dich **besser fühlen**.', '["iyileşirsin"]', '["feel better"]', '["må bättre"]', '["besser fühlen"]', 'beginner', false, 340);

-- Category 9: Sağlık — Intermediate (10 sentences)
INSERT INTO sentences (category_id, text_tr, text_en, text_sv, text_de, keywords_tr, keywords_en, keywords_sv, keywords_de, difficulty, is_free, sort_order) VALUES
(9, 'Grip **kapıp** birkaç gündür yataktan çıkamıyorum.', 'I **came down with** the flu and have been in bed for days.', 'Jag **fick** influensa och har legat i sängen i flera dagar.', 'Ich habe **die Grippe bekommen** und liege seit Tagen im Bett.', '["kapıp"]', '["came down with"]', '["fick"]', '["die Grippe bekommen"]', 'intermediate', false, 341),
(9, 'Ameliyattan **atlatmak** birkaç hafta sürdü.', 'It took a few weeks to **get over** the surgery.', 'Det tog några veckor att **återhämta sig** från operationen.', 'Es dauerte einige Wochen, um sich von der Operation **zu erholen**.', '["atlatmak"]', '["get over"]', '["återhämta sig"]', '["erholen"]', 'intermediate', false, 342),
(9, 'Kazadan sonra tamamen **iyileşmesi** altı ay sürdü.', 'It took six months to **recover from** the accident.', 'Det tog sex månader att **återhämta sig från** olyckan.', 'Es dauerte sechs Monate, sich von dem Unfall **zu erholen**.', '["iyileşmesi"]', '["recover from"]', '["återhämta sig från"]', '["erholen von"]', 'intermediate', false, 343),
(9, 'Fındıklara **alerjim var**, onları yiyemiyorum.', 'I **am allergic to** nuts and cannot eat them.', 'Jag **är allergisk mot** nötter och kan inte äta dem.', 'Ich **bin allergisch gegen** Nüsse und kann sie nicht essen.', '["alerjim var"]', '["am allergic to"]', '["är allergisk mot"]', '["bin allergisch gegen"]', 'intermediate', false, 344),
(9, 'Yıllık **kontrol muayenemi** geçen ay yaptırdım.', 'I had my annual **check-up** last month.', 'Jag hade min årliga **kontroll** förra månaden.', 'Ich hatte letzten Monat meine jährliche **Vorsorgeuntersuchung**.', '["kontrol muayenemi"]', '["check-up"]', '["kontroll"]', '["Vorsorgeuntersuchung"]', 'intermediate', false, 345),
(9, 'Daha sağlıklı olmak için şekeri **azaltmam** gerekiyor.', 'I need to **cut back on** sugar to be healthier.', 'Jag behöver **minska på** socker för att vara friskare.', 'Ich muss Zucker **reduzieren**, um gesünder zu sein.', '["azaltmam"]', '["cut back on"]', '["minska på"]', '["reduzieren"]', 'intermediate', false, 346),
(9, 'Haftada en az üç kez spor yaparak **formumu koruyorum**.', 'I **stay in shape** by exercising at least three times a week.', 'Jag **håller mig i form** genom att träna minst tre gånger i veckan.', 'Ich **bleibe fit**, indem ich mindestens dreimal pro Woche Sport treibe.', '["formumu koruyorum"]', '["stay in shape"]', '["håller mig i form"]', '["bleibe fit"]', 'intermediate', false, 347),
(9, 'Düzenli yürüyüş yaparak **formda kalmaya** çalışıyorum.', 'I try to **keep fit** by walking regularly.', 'Jag försöker **hålla mig i form** genom att gå regelbundet.', 'Ich versuche, mich durch regelmäßiges Gehen **fit zu halten**.', '["formda kalmaya"]', '["keep fit"]', '["hålla mig i form"]', '["fit zu halten"]', 'intermediate', false, 348),
(9, 'Kilo vermek için düşük karbonhidratlı **diyet uyguluyorum**.', 'I **follow a diet** low in carbs to lose weight.', 'Jag **följer en diet** med lågt kolhydratinnehåll för att gå ner i vikt.', 'Ich **halte eine Diät** mit wenig Kohlenhydraten ein, um abzunehmen.', '["diyet uyguluyorum"]', '["follow a diet"]', '["följer en diet"]', '["halte eine Diät"]', 'intermediate', false, 349),
(9, 'Sağlığım için **sigarayı bıraktım**.', 'I **gave up smoking** for my health.', 'Jag **slutade röka** för min hälsas skull.', 'Ich habe **mit dem Rauchen aufgehört** für meine Gesundheit.', '["sigarayı bıraktım"]', '["gave up smoking"]', '["slutade röka"]', '["mit dem Rauchen aufgehört"]', 'intermediate', false, 350);

-- Category 9: Sağlık — Advanced (10 sentences)
INSERT INTO sentences (category_id, text_tr, text_en, text_sv, text_de, keywords_tr, keywords_en, keywords_sv, keywords_de, difficulty, is_free, sort_order) VALUES
(9, 'Bu ilacın bazı **yan etkileri** olabilir, dikkatli ol.', 'This medication can have some **side effects**, be careful.', 'Denna medicin kan ha några **biverkningar**, var försiktig.', 'Dieses Medikament kann einige **Nebenwirkungen** haben, sei vorsichtig.', '["yan etkileri"]', '["side effects"]', '["biverkningar"]', '["Nebenwirkungen"]', 'advanced', false, 351),
(9, 'Doktor bana ağrı kesici **reçete etti**.', 'The doctor **prescribed** me painkillers.', 'Läkaren **ordinerade** mig smärtstillande medel.', 'Der Arzt hat mir Schmerzmittel **verschrieben**.', '["reçete etti"]', '["prescribed"]', '["ordinerade"]', '["verschrieben"]', 'advanced', false, 352),
(9, 'Dizindeki sorunu çözmek için **ameliyata girmesi** gerekiyor.', 'He needs to **go under the knife** to fix the knee problem.', 'Han behöver **opereras** för att lösa knäproblemet.', 'Er muss **operiert werden**, um das Knieproblem zu lösen.', '["ameliyata girmesi"]', '["go under the knife"]', '["opereras"]', '["operiert werden"]', 'advanced', false, 353),
(9, 'İyileşiyordu ama sonra **nüksetti**.', 'He was getting better but then had a **relapse**.', 'Han mådde bättre men fick sedan **ett återfall**.', 'Er wurde besser, hatte aber dann einen **Rückfall**.', '["nüksetti"]', '["relapse"]', '["ett återfall"]', '["Rückfall"]', 'advanced', false, 354),
(9, '**Koruyucu sağlık hizmetleri**, hastalıkların erken tespitini sağlar.', '**Preventive care** helps detect illnesses early.', '**Förebyggande vård** hjälper till att tidigt upptäcka sjukdomar.', '**Vorsorge** hilft dabei, Krankheiten frühzeitig zu erkennen.', '["koruyucu sağlık hizmetleri"]', '["preventive care"]', '["förebyggande vård"]', '["Vorsorge"]', 'advanced', false, 355),
(9, '**Ruh sağlığı** en az fiziksel sağlık kadar önemlidir.', '**Mental health** is just as important as physical health.', '**Psykisk hälsa** är lika viktig som fysisk hälsa.', '**Psychische Gesundheit** ist genauso wichtig wie körperliche Gesundheit.', '["ruh sağlığı"]', '["mental health"]', '["psykisk hälsa"]', '["Psychische Gesundheit"]', 'advanced', false, 356),
(9, 'Düzenli uyku **bağışıklık sistemini** güçlendirir.', 'Regular sleep strengthens the **immune system**.', 'Regelbunden sömn stärker **immunsystemet**.', 'Regelmäßiger Schlaf stärkt das **Immunsystem**.', '["bağışıklık sistemini"]', '["immune system"]', '["immunsystemet"]', '["Immunsystem"]', 'advanced', false, 357),
(9, 'Diyabet gibi **kronik durumlar** süregelen tedavi gerektirir.', '**Chronic conditions** like diabetes require ongoing treatment.', '**Kroniska tillstånd** som diabetes kräver kontinuerlig behandling.', '**Chronische Erkrankungen** wie Diabetes erfordern eine dauerhafte Behandlung.', '["kronik durumlar"]', '["chronic conditions"]', '["kroniska tillstånd"]', '["chronische Erkrankungen"]', 'advanced', false, 358),
(9, 'Çok fazla çalışınca kendimi **tamamen tükenmişlik** içinde buldum.', 'After working too much I found myself completely **burned out**.', 'Efter att ha jobbat för mycket befann jag mig helt **utbränd**.', 'Nach zu viel Arbeit fand ich mich vollständig **ausgebrannt**.', '["tamamen tükenmişlik"]', '["burned out"]', '["utbränd"]', '["ausgebrannt"]', 'advanced', false, 359),
(9, 'Farklı bir görüş almak için başka bir doktora **ikinci görüş** danıştım.', 'I consulted another doctor for a **second opinion**.', 'Jag rådfrågade en annan läkare för att få en **second opinion**.', 'Ich konsultierte einen anderen Arzt für eine **zweite Meinung**.', '["ikinci görüş"]', '["second opinion"]', '["second opinion"]', '["zweite Meinung"]', 'advanced', false, 360);
