-- 018_seed_sentences_cat3_to_10.sql
-- 10 new sentences per category (3-10), all 7 languages
-- sort_order continues after each category's existing max

-- ─────────────────────────────────────────────────────────────────
-- Category 3: Phrasal Verbs — 3 beginner, 4 intermediate, 3 advanced
-- Existing: sort_order 61-90 → new: 91-100
-- ─────────────────────────────────────────────────────────────────
INSERT INTO sentences (
  category_id, text_tr, text_en, text_sv, text_de, text_es, text_fr, text_pt,
  keywords_tr, keywords_en, keywords_sv, keywords_de, keywords_es, keywords_fr, keywords_pt,
  difficulty, is_free, sort_order
) VALUES

(3, 'Bu formu eksiksiz **doldurmam** gerekiyor.',
    'I need to **fill in** this form completely.',
    'Jag behöver **fylla i** det här formuläret fullständigt.',
    'Ich muss dieses Formular vollständig **ausfüllen**.',
    'Necesito **rellenar** este formulario completamente.',
    'Je dois **remplir** ce formulaire complètement.',
    'Preciso **preencher** este formulário completamente.',
    '["doldurmam"]', '["fill in"]', '["fylla i"]', '["ausfüllen"]',
    '["rellenar"]', '["remplir"]', '["preencher"]',
    'beginner', false, 91),

(3, 'Şu an müsait değilim, seni birazdan **geri arayacağım**.',
    'I''m busy right now, I''ll **call you back** shortly.',
    'Jag är upptagen just nu, jag **ringer tillbaka** snart.',
    'Ich bin gerade beschäftigt, ich **rufe dich zurück**.',
    'Ahora estoy ocupado, te **llamo de vuelta** pronto.',
    'Je suis occupé là, je te **rappelle** bientôt.',
    'Estou ocupado agora, vou te **ligar de volta** em breve.',
    '["geri arayacağım"]', '["call back"]', '["ringer tillbaka"]', '["rufe zurück"]',
    '["llamo de vuelta"]', '["rappelle"]', '["ligar de volta"]',
    'beginner', false, 92),

(3, 'Ne zaman döneceğini **öğrenmek** istiyorum.',
    'I want to **find out** when she''ll be back.',
    'Jag vill **ta reda på** när hon kommer tillbaka.',
    'Ich möchte **herausfinden**, wann sie zurückkommt.',
    'Quiero **averiguar** cuándo va a volver.',
    'Je veux **savoir** quand elle va revenir.',
    'Quero **descobrir** quando ela volta.',
    '["öğrenmek"]', '["find out"]', '["ta reda på"]', '["herausfinden"]',
    '["averiguar"]', '["savoir"]', '["descobrir"]',
    'beginner', false, 93),

(3, 'Toplantıda o tartışmalı konuyu **gündeme getirdi**.',
    'He **brought up** that controversial topic at the meeting.',
    'Han **tog upp** det kontroversiella ämnet på mötet.',
    'Er hat das heikle Thema in der Besprechung **zur Sprache gebracht**.',
    '**Sacó a relucir** ese tema polémico en la reunión.',
    'Il a **soulevé** ce sujet controversé lors de la réunion.',
    'Ele **levantou** aquele tema polêmico na reunião.',
    '["gündeme getirdi"]', '["brought up"]', '["tog upp"]', '["zur Sprache gebracht"]',
    '["sacó a relucir"]', '["soulevé"]', '["levantou"]',
    'intermediate', false, 94),

(3, 'Bu soruna sonunda harika bir çözüm **buldum**.',
    'I finally **came up with** a great solution to this problem.',
    'Jag **kom på** en bra lösning på det här problemet till slut.',
    'Ich habe endlich eine tolle Lösung für dieses Problem **gefunden**.',
    'Por fin **se me ocurrió** una gran solución a este problema.',
    'J''ai finalement **trouvé** une excellente solution à ce problème.',
    'Finalmente **pensei em** uma ótima solução para este problema.',
    '["buldum"]', '["came up with"]', '["kom på"]', '["gefunden"]',
    '["se me ocurrió"]', '["trouvé"]', '["pensei em"]',
    'intermediate', false, 95),

(3, 'Şirket el değiştirdi — yeni bir yönetim **devraldı**.',
    'The company changed hands — a new management **took over**.',
    'Företaget bytte ägare — en ny ledning **tog över**.',
    'Das Unternehmen wechselte den Besitzer — ein neues Management **übernahm**.',
    'La empresa cambió de manos — una nueva dirección **se hizo cargo**.',
    'L''entreprise a changé de mains — une nouvelle direction **a pris le relais**.',
    'A empresa mudou de mãos — uma nova gestão **assumiu**.',
    '["devraldı"]', '["took over"]', '["tog över"]', '["übernahm"]',
    '["se hizo cargo"]', '["a pris le relais"]', '["assumiu"]',
    'intermediate', false, 96),

(3, 'Bir hata yaptığımı kibarca **fark ettirdi**.',
    'She **pointed out** politely that I had made a mistake.',
    'Hon **påpekade** artigt att jag hade gjort ett misstag.',
    'Sie **wies freundlich darauf hin**, dass ich einen Fehler gemacht hatte.',
    'Me **señaló** amablemente que había cometido un error.',
    'Elle m''a **signalé** poliment que j''avais fait une erreur.',
    'Ela **apontou** educadamente que eu tinha cometido um erro.',
    '["fark ettirdi"]', '["pointed out"]', '["påpekade"]', '["wies darauf hin"]',
    '["señaló"]', '["signalé"]', '["apontou"]',
    'intermediate', false, 97),

(3, 'Ne kadar uğraşsa da hep beklentileri **karşılayamıyor**.',
    'No matter how hard he tries, he can never **live up to** the expectations.',
    'Hur hårt han än försöker kan han aldrig **leva upp till** förväntningarna.',
    'Egal wie sehr er sich bemüht, er kann die Erwartungen nie **erfüllen**.',
    'Por mucho que lo intente, nunca puede **estar a la altura** de las expectativas.',
    'Peu importe ses efforts, il n''arrive jamais à **être à la hauteur** des attentes.',
    'Por mais que tente, ele nunca consegue **estar à altura** das expectativas.',
    '["karşılayamıyor"]', '["live up to"]', '["leva upp till"]', '["erfüllen"]',
    '["estar a la altura"]', '["être à la hauteur"]', '["estar à altura"]',
    'advanced', false, 98),

(3, 'Yoğun eleştiriler karşısında bile **geri adım atmadı**.',
    'She didn''t **back down** even in the face of heavy criticism.',
    'Hon **backade inte** ens inför hård kritik.',
    'Sie ist auch angesichts heftiger Kritik **nicht zurückgewichen**.',
    'No **dio marcha atrás** ni siquiera ante las duras críticas.',
    'Elle n''a pas **reculé** même face aux critiques sévères.',
    'Ela não **recuou** mesmo diante das críticas pesadas.',
    '["geri adım atmadı"]', '["back down"]', '["backade inte"]', '["nicht zurückgewichen"]',
    '["dio marcha atrás"]', '["reculé"]', '["recuou"]',
    'advanced', false, 99),

(3, 'Bu sefer **cezasız kurtuldu** ama bir daha olmaz.',
    'He **got away with** it this time, but it won''t happen again.',
    'Han **kom undan** den här gången, men det händer inte igen.',
    'Er ist diesmal **damit durchgekommen**, aber das wird nicht noch mal passieren.',
    'Se **salió con la suya** esta vez, pero no volverá a pasar.',
    'Il **s''en est tiré** cette fois, mais ça ne se reproduira pas.',
    'Ele **se safou** dessa vez, mas não vai acontecer de novo.',
    '["cezasız kurtuldu"]', '["got away with"]', '["kom undan"]', '["durchgekommen"]',
    '["salió con la suya"]', '["s''en est tiré"]', '["se safou"]',
    'advanced', false, 100);

-- ─────────────────────────────────────────────────────────────────
-- Category 4: Travel — 3 beginner, 4 intermediate, 3 advanced
-- Existing: sort_order 91-120 → new: 121-130
-- ─────────────────────────────────────────────────────────────────
INSERT INTO sentences (
  category_id, text_tr, text_en, text_sv, text_de, text_es, text_fr, text_pt,
  keywords_tr, keywords_en, keywords_sv, keywords_de, keywords_es, keywords_fr, keywords_pt,
  difficulty, is_free, sort_order
) VALUES

(4, 'Lütfen bir **tek gidiş** bilet istiyorum.',
    'I''d like a **one-way** ticket, please.',
    'Jag skulle vilja ha en **enkelresa**, tack.',
    'Ich möchte eine **Einzelfahrkarte**, bitte.',
    'Quisiera un billete **de ida**, por favor.',
    'Je voudrais un billet **aller simple**, s''il vous plaît.',
    'Gostaria de uma passagem **só de ida**, por favor.',
    '["tek gidiş"]', '["one-way"]', '["enkelresa"]', '["Einzelfahrkarte"]',
    '["de ida"]', '["aller simple"]', '["só de ida"]',
    'beginner', false, 121),

(4, '**Pencere kenarı** bir koltuk tercih ederim.',
    'I prefer a **window seat**.',
    'Jag föredrar en **fönsterplats**.',
    'Ich bevorzuge einen **Fensterplatz**.',
    'Prefiero un asiento de **ventanilla**.',
    'Je préfère une place **côté fenêtre**.',
    'Prefiro um assento de **janela**.',
    '["pencere kenarı"]', '["window seat"]', '["fönsterplats"]', '["Fensterplatz"]',
    '["ventanilla"]', '["côté fenêtre"]', '["janela"]',
    'beginner', false, 122),

(4, 'Sadece **el bagajım** var, büyük valizim yok.',
    'I only have **carry-on luggage**, no big suitcase.',
    'Jag har bara **handbagage**, ingen stor resväska.',
    'Ich habe nur **Handgepäck**, keinen großen Koffer.',
    'Solo tengo **equipaje de mano**, sin maleta grande.',
    'Je n''ai que des **bagages à main**, sans grande valise.',
    'Só tenho **bagagem de mão**, sem mala grande.',
    '["el bagajım"]', '["carry-on luggage"]', '["handbagage"]', '["Handgepäck"]',
    '["equipaje de mano"]', '["bagages à main"]', '["bagagem de mão"]',
    'beginner', false, 123),

(4, 'Stressiz seyahat etmek için her zaman az eşyayla **hafif seyahat ederim**.',
    'To travel stress-free, I always **travel light**.',
    'För att resa stressfritt **reser jag alltid lätt**.',
    'Um stressfrei zu reisen, **reise ich immer mit wenig Gepäck**.',
    'Para viajar sin estrés, siempre **viajo ligero**.',
    'Pour voyager sans stress, je **voyage toujours léger**.',
    'Para viajar sem estresse, sempre **viajo leve**.',
    '["hafif seyahat ederim"]', '["travel light"]', '["reser lätt"]', '["mit wenig Gepäck"]',
    '["viajo ligero"]', '["voyage léger"]', '["viajo leve"]',
    'intermediate', false, 124),

(4, 'Frankfurt''ta **aktarma yapıp** başka bir uçağa binmem gerekiyor.',
    'I need to **change planes** in Frankfurt.',
    'Jag behöver **byta flyg** i Frankfurt.',
    'Ich muss in Frankfurt **umsteigen**.',
    'Tengo que **hacer transbordo** en Frankfurt.',
    'Je dois **changer d''avion** à Francfort.',
    'Preciso **fazer conexão** em Frankfurt.',
    '["aktarma yapıp"]', '["change planes"]', '["byta flyg"]', '["umsteigen"]',
    '["hacer transbordo"]', '["changer d''avion"]', '["fazer conexão"]',
    'intermediate', false, 125),

(4, 'Trafiğe **takıldık**, yarım saat gecikebiliriz.',
    'We''re **stuck in traffic**, we might be half an hour late.',
    'Vi sitter **fast i trafiken** och kan bli en halvtimme sena.',
    'Wir stecken **im Stau** und könnten eine halbe Stunde zu spät sein.',
    'Estamos **atascados en el tráfico**, podemos llegar media hora tarde.',
    'On est **coincés dans les embouteillages**, on pourrait avoir une demi-heure de retard.',
    'Estamos **presos no trânsito**, podemos atrasar meia hora.',
    '["takıldık"]', '["stuck in traffic"]', '["fast i trafiken"]', '["im Stau"]',
    '["atascados en el tráfico"]', '["coincés dans les embouteillages"]', '["presos no trânsito"]',
    'intermediate', false, 126),

(4, 'Şehirde **toplu taşımayla** gezmek hem daha ucuz hem daha pratik.',
    'Getting around by **public transport** is both cheaper and more practical.',
    'Att ta sig runt med **kollektivtrafik** är både billigare och mer praktiskt.',
    'Mit **öffentlichen Verkehrsmitteln** zu reisen ist sowohl billiger als auch praktischer.',
    'Moverse en **transporte público** es más barato y práctico.',
    'Se déplacer en **transport en commun** est à la fois moins cher et plus pratique.',
    'Andar de **transporte público** é mais barato e prático.',
    '["toplu taşımayla"]', '["public transport"]', '["kollektivtrafik"]', '["öffentlichen Verkehrsmitteln"]',
    '["transporte público"]', '["transport en commun"]', '["transporte público"]',
    'intermediate', false, 127),

(4, 'Uzun uçuşun ardından ciddi **jetlag** yaşıyorum.',
    'I''m suffering from severe **jet lag** after the long flight.',
    'Jag lider av svår **jetlag** efter den långa flygningen.',
    'Ich leide nach dem langen Flug an schwerem **Jetlag**.',
    'Tengo un **jet lag** severo después del largo vuelo.',
    'Je souffre d''un fort **décalage horaire** après le long vol.',
    'Estou sofrendo de **jet lag** severo após o longo voo.',
    '["jetlag"]', '["jet lag"]', '["jetlag"]', '["Jetlag"]',
    '["jet lag"]', '["décalage horaire"]', '["jet lag"]',
    'advanced', false, 128),

(4, '**Bütçeye uygun** seyahat etmek için önceden rezervasyon şart.',
    'To **travel on a budget**, booking in advance is a must.',
    'För att **resa på budget** är det nödvändigt att boka i förväg.',
    'Um **günstig zu reisen**, ist eine Vorausbuchung unerlässlich.',
    'Para **viajar con poco dinero**, hay que reservar con antelación.',
    'Pour **voyager à petit budget**, réserver à l''avance est indispensable.',
    'Para **viajar com orçamento limitado**, reservar com antecedência é essencial.',
    '["bütçeye uygun"]', '["travel on a budget"]', '["resa på budget"]', '["günstig reisen"]',
    '["viajar con poco dinero"]', '["voyager à petit budget"]', '["viajar com orçamento limitado"]',
    'advanced', false, 129),

(4, 'İstanbul''da dört saatlik **transit beklememiz** var.',
    'We have a four-hour **layover** in Istanbul.',
    'Vi har en fyratimmars **mellanlandning** i Istanbul.',
    'Wir haben eine vierstündige **Zwischenlandung** in Istanbul.',
    'Tenemos una **escala** de cuatro horas en Estambul.',
    'On a une **escale** de quatre heures à Istanbul.',
    'Temos uma **escala** de quatro horas em Istambul.',
    '["transit beklememiz"]', '["layover"]', '["mellanlandning"]', '["Zwischenlandung"]',
    '["escala"]', '["escale"]', '["escala"]',
    'advanced', false, 130);

-- ─────────────────────────────────────────────────────────────────
-- Category 5: Academic — 3 beginner, 4 intermediate, 3 advanced
-- Existing: sort_order 121-150 → new: 151-160
-- ─────────────────────────────────────────────────────────────────
INSERT INTO sentences (
  category_id, text_tr, text_en, text_sv, text_de, text_es, text_fr, text_pt,
  keywords_tr, keywords_en, keywords_sv, keywords_de, keywords_es, keywords_fr, keywords_pt,
  difficulty, is_free, sort_order
) VALUES

(5, '**Örneğin**, diyetimizi değiştirerek çevreye katkıda bulunabiliriz.',
    '**For example**, we can contribute to the environment by changing our diet.',
    '**Till exempel** kan vi bidra till miljön genom att ändra vår kost.',
    '**Zum Beispiel** können wir durch eine Ernährungsumstellung zur Umwelt beitragen.',
    '**Por ejemplo**, podemos contribuir al medio ambiente cambiando nuestra dieta.',
    '**Par exemple**, nous pouvons contribuer à l''environnement en changeant notre alimentation.',
    '**Por exemplo**, podemos contribuir para o meio ambiente mudando nossa dieta.',
    '["örneğin"]', '["for example"]', '["till exempel"]', '["zum Beispiel"]',
    '["por ejemplo"]', '["par exemple"]', '["por exemplo"]',
    'beginner', false, 151),

(5, '**Bu araştırmaya göre**, düzenli egzersiz stresi belirgin biçimde azaltıyor.',
    '**According to** this research, regular exercise significantly reduces stress.',
    '**Enligt** den här forskningen minskar regelbunden motion stress avsevärt.',
    '**Laut** dieser Studie reduziert regelmäßiges Training Stress erheblich.',
    '**Según** esta investigación, el ejercicio regular reduce significativamente el estrés.',
    '**Selon** cette recherche, l''exercice régulier réduit significativement le stress.',
    '**Segundo** esta pesquisa, o exercício regular reduz significativamente o estresse.',
    '["bu araştırmaya göre"]', '["according to"]', '["enligt"]', '["laut"]',
    '["según"]', '["selon"]', '["segundo"]',
    'beginner', false, 152),

(5, 'Pek çok Avrupa dili, **İngilizce ve Almanca gibi**, aynı kökenden geliyor.',
    'Many European languages, **such as** English and German, share the same root.',
    'Många europeiska språk, **såsom** engelska och tyska, delar samma rot.',
    'Viele europäische Sprachen, **wie zum Beispiel** Englisch und Deutsch, haben dieselbe Wurzel.',
    'Muchos idiomas europeos, **como** el inglés y el alemán, comparten la misma raíz.',
    'De nombreuses langues européennes, **comme** l''anglais et l''allemand, partagent la même racine.',
    'Muitas línguas europeias, **como** o inglês e o alemão, compartilham a mesma raiz.',
    '["İngilizce ve Almanca gibi"]', '["such as"]', '["såsom"]', '["wie zum Beispiel"]',
    '["como"]', '["comme"]', '["como"]',
    'beginner', false, 153),

(5, 'Bu verilere bakarak kesin bir **sonuca varmak** güç.',
    'It is difficult to **draw a conclusion** from this data.',
    'Det är svårt att **dra en slutsats** av dessa uppgifter.',
    'Aus diesen Daten eine **Schlussfolgerung zu ziehen** ist schwierig.',
    'Es difícil **llegar a una conclusión** a partir de estos datos.',
    'Il est difficile de **tirer une conclusion** de ces données.',
    'É difícil **chegar a uma conclusão** a partir desses dados.',
    '["sonuca varmak"]', '["draw a conclusion"]', '["dra en slutsats"]', '["Schlussfolgerung ziehen"]',
    '["llegar a una conclusión"]', '["tirer une conclusion"]', '["chegar a uma conclusão"]',
    'intermediate', false, 154),

(5, 'Analizi yaparken bu faktörü **göz önünde bulundurmalıyız**.',
    'We should **take this factor into account** when analysing.',
    'Vi bör **ta hänsyn till** den här faktorn när vi analyserar.',
    'Wir sollten diesen Faktor beim Analysieren **berücksichtigen**.',
    'Debemos **tener en cuenta** este factor al analizar.',
    'Nous devons **prendre en compte** ce facteur lors de l''analyse.',
    'Devemos **levar em conta** esse fator ao analisar.',
    '["göz önünde bulundurmalıyız"]', '["take into account"]', '["ta hänsyn till"]', '["berücksichtigen"]',
    '["tener en cuenta"]', '["prendre en compte"]', '["levar em conta"]',
    'intermediate', false, 155),

(5, '**Özetle**, bu çalışma iklim değişikliğinin ciddi sonuçlarını ortaya koymaktadır.',
    '**To sum up**, this study reveals the serious consequences of climate change.',
    '**Sammanfattningsvis** avslöjar den här studien de allvarliga konsekvenserna av klimatförändringarna.',
    '**Zusammenfassend** zeigt diese Studie die schwerwiegenden Folgen des Klimawandels.',
    '**En resumen**, este estudio revela las graves consecuencias del cambio climático.',
    '**En résumé**, cette étude révèle les graves conséquences du changement climatique.',
    '**Em resumo**, este estudo revela as graves consequências das mudanças climáticas.',
    '["özetle"]', '["to sum up"]', '["sammanfattningsvis"]', '["zusammenfassend"]',
    '["en resumen"]', '["en résumé"]', '["em resumo"]',
    'intermediate', false, 156),

(5, 'Bu bulgular mevcut politikaların yeniden **gözden geçirilmesini** ima ediyor.',
    'These findings **imply** that current policies need to be reconsidered.',
    'Dessa resultat **antyder** att nuvarande policyer måste omprövas.',
    'Diese Ergebnisse **legen nahe**, dass die aktuelle Politik überdacht werden muss.',
    'Estos hallazgos **implican** que las políticas actuales deben ser reconsideradas.',
    'Ces résultats **impliquent** que les politiques actuelles doivent être reconsidérées.',
    'Esses achados **implicam** que as políticas atuais precisam ser reconsideradas.',
    '["gözden geçirilmesini"]', '["imply"]', '["antyder"]', '["legen nahe"]',
    '["implican"]', '["impliquent"]', '["implicam"]',
    'intermediate', false, 157),

(5, 'Bu çalışma konunun daha iyi anlaşılmasına **ışık tutmaktadır**.',
    'This study **sheds light on** a better understanding of the topic.',
    'Den här studien **kastar ljus över** en bättre förståelse av ämnet.',
    'Diese Studie **beleuchtet** ein besseres Verständnis des Themas.',
    'Este estudio **arroja luz sobre** una mejor comprensión del tema.',
    'Cette étude **éclaire** une meilleure compréhension du sujet.',
    'Este estudo **lança luz sobre** uma melhor compreensão do tema.',
    '["ışık tutmaktadır"]', '["sheds light on"]', '["kastar ljus över"]', '["beleuchtet"]',
    '["arroja luz sobre"]', '["éclaire"]', '["lança luz sobre"]',
    'advanced', false, 158),

(5, 'Bu bulgular mevcut teorinin **sorgulanmasına** yol açtı.',
    'These findings **called into question** the existing theory.',
    'Dessa resultat **ifrågasatte** den befintliga teorin.',
    'Diese Ergebnisse **stellten die bestehende Theorie infrage**.',
    'Estos hallazgos **pusieron en duda** la teoría existente.',
    'Ces résultats ont **remis en question** la théorie existante.',
    'Esses achados **colocaram em questão** a teoria existente.',
    '["sorgulanmasına"]', '["called into question"]', '["ifrågasatte"]', '["infrage gestellt"]',
    '["pusieron en duda"]', '["remis en question"]', '["colocaram em questão"]',
    'advanced', false, 159),

(5, 'Eğitim düzeyi ile gelir düzeyi arasında güçlü bir **korelasyon** bulundu.',
    'A strong **correlation** was found between education level and income.',
    'Ett starkt **samband** hittades mellan utbildningsnivå och inkomst.',
    'Zwischen Bildungsniveau und Einkommen wurde eine starke **Korrelation** gefunden.',
    'Se encontró una fuerte **correlación** entre el nivel educativo y los ingresos.',
    'Une forte **corrélation** a été trouvée entre le niveau d''éducation et les revenus.',
    'Uma forte **correlação** foi encontrada entre o nível de educação e a renda.',
    '["korelasyon"]', '["correlation"]', '["samband"]', '["Korrelation"]',
    '["correlación"]', '["corrélation"]', '["correlação"]',
    'advanced', false, 160);

-- ─────────────────────────────────────────────────────────────────
-- Category 6: Idioms — 3 beginner, 4 intermediate, 3 advanced
-- Existing: sort_order 151-180 → new: 181-190
-- ─────────────────────────────────────────────────────────────────
INSERT INTO sentences (
  category_id, text_tr, text_en, text_sv, text_de, text_es, text_fr, text_pt,
  keywords_tr, keywords_en, keywords_sv, keywords_de, keywords_es, keywords_fr, keywords_pt,
  difficulty, is_free, sort_order
) VALUES

(6, 'Yabancılarla dolu odada bir espri yaparak **buzu kırdı**.',
    'He **broke the ice** in the room full of strangers with a joke.',
    'Han **bröt isen** i rummet fullt av okända med ett skämt.',
    'Er hat das **Eis gebrochen** im Raum voller Fremder mit einem Witz.',
    '**Rompió el hielo** en la sala llena de desconocidos con un chiste.',
    'Il a **brisé la glace** dans la pièce pleine d''inconnus avec une blague.',
    'Ele **quebrou o gelo** na sala cheia de desconhecidos com uma piada.',
    '["buzu kırdı"]', '["broke the ice"]', '["bröt isen"]', '["Eis gebrochen"]',
    '["rompió el hielo"]', '["brisé la glace"]', '["quebrou o gelo"]',
    'beginner', false, 181),

(6, 'Ne kadar çok kişi gelirse o kadar iyi — **ne kadar çok olursak o kadar iyiyiz**!',
    'The more the merrier — **the more the merrier**!',
    'Ju fler desto bättre — **ju fler desto bättre**!',
    'Je mehr, desto besser — **je mehr, desto besser**!',
    '¡Cuantos más, mejor — **cuantos más, mejor**!',
    'Plus on est de fous, plus on rit — **plus on est de fous, plus on rit** !',
    'Quanto mais, melhor — **quanto mais, melhor**!',
    '["ne kadar çok olursak o kadar iyiyiz"]', '["the more the merrier"]', '["ju fler desto bättre"]', '["je mehr desto besser"]',
    '["cuantos más mejor"]', '["plus on est de fous plus on rit"]', '["quanto mais melhor"]',
    'beginner', false, 182),

(6, 'Bu kavgada iki taraf da suçlu — **bir elle çırpılmaz**.',
    'Both sides are at fault here — **it takes two to tango**.',
    'Båda sidor är skyldiga här — **det tar två för att tango**.',
    'Beide Seiten sind hier schuld — **es gehören immer zwei dazu**.',
    'Ambos tienen la culpa aquí — **se necesitan dos para bailar el tango**.',
    'Les deux parties sont fautives ici — **ça prend deux pour danser le tango**.',
    'Os dois têm culpa aqui — **é preciso dois para dançar o tango**.',
    '["bir elle çırpılmaz"]', '["it takes two to tango"]', '["det tar två för att tango"]', '["es gehören immer zwei dazu"]',
    '["se necesitan dos para bailar el tango"]', '["ça prend deux pour danser le tango"]', '["é preciso dois para dançar o tango"]',
    'beginner', false, 183),

(6, 'Zor kararı uzun süre erteledi ama sonunda **dişini sıkıp** kabul etti.',
    'He put off the hard decision for a long time but finally **bit the bullet**.',
    'Han sköt upp det svåra beslutet länge men **bet ihop** till slut.',
    'Er hat die schwere Entscheidung lange hinausgezögert, aber schließlich **in den sauren Apfel gebissen**.',
    'Pospuso la difícil decisión por mucho tiempo pero finalmente **tomó el toro por los cuernos**.',
    'Il a repoussé la décision difficile longtemps mais a finalement **mordu la balle**.',
    'Ele adiou a decisão difícil por muito tempo mas finalmente **encarou de frente**.',
    '["dişini sıkıp"]', '["bit the bullet"]', '["bet ihop"]', '["in den sauren Apfel gebissen"]',
    '["tomó el toro por los cuernos"]', '["mordu la balle"]', '["encarou de frente"]',
    'intermediate', false, 184),

(6, 'O yorumunla tam **çivinin başına vurdun**, herkes aynı şeyi düşünüyordu.',
    'With that comment you really **hit the nail on the head** — everyone was thinking the same.',
    'Med den kommentaren **slog du spiken på huvudet** — alla tänkte likadant.',
    'Mit diesem Kommentar hast du **den Nagel auf den Kopf getroffen** — alle dachten dasselbe.',
    'Con ese comentario **diste en el clavo** — todos pensaban lo mismo.',
    'Avec ce commentaire tu as **mis le doigt dessus** — tout le monde pensait pareil.',
    'Com esse comentário você **acertou em cheio** — todos pensavam a mesma coisa.',
    '["çivinin başına vurdun"]', '["hit the nail on the head"]', '["slog spiken på huvudet"]', '["Nagel auf den Kopf getroffen"]',
    '["diste en el clavo"]', '["mis le doigt dessus"]', '["acertou em cheio"]',
    'intermediate', false, 185),

(6, 'Teklif yapmak istiyordu ama son anda **cesareti kırıldı**.',
    'He wanted to propose but **got cold feet** at the last moment.',
    'Han ville friersa men **fick kalla fötter** i sista stund.',
    'Er wollte einen Antrag machen, aber bekam kurz vorher **kalte Füße**.',
    'Quería proponer matrimonio pero **le entró el pánico** en el último momento.',
    'Il voulait faire sa demande mais a eu **les jambes en coton** à la dernière seconde.',
    'Ele queria pedir em casamento mas **ficou com frio na barriga** no último momento.',
    '["cesareti kırıldı"]', '["got cold feet"]', '["fick kalla fötter"]', '["kalte Füße"]',
    '["le entró el pánico"]', '["les jambes en coton"]', '["ficou com frio na barriga"]',
    'intermediate', false, 186),

(6, 'Aynı anda beş proje üstlendi — tam **ağzından büyük lokma aldı**.',
    'She took on five projects at once — she really **bit off more than she could chew**.',
    'Hon tog på sig fem projekt på en gång — hon **bet av mer än hon kunde tugga**.',
    'Sie übernahm fünf Projekte auf einmal — sie hat sich eindeutig **zu viel vorgenommen**.',
    'Asumió cinco proyectos a la vez — claramente **se metió en más de lo que podía manejar**.',
    'Elle a pris cinq projets en même temps — elle a clairement **voulu courir plusieurs lièvres à la fois**.',
    'Ela assumiu cinco projetos de uma vez — claramente **foi maior do que a boca**.',
    '["ağzından büyük lokma aldı"]', '["bit off more than she could chew"]', '["bet av mer än hon kunde tugga"]', '["zu viel vorgenommen"]',
    '["se metió en más de lo que podía manejar"]', '["courir plusieurs lièvres à la fois"]', '["foi maior do que a boca"]',
    'intermediate', false, 187),

(6, 'Uzun mücadelenin ardından sonunda **havlu attı**.',
    'After a long fight, he finally **threw in the towel**.',
    'Efter en lång kamp **kastade han in handduken** till slut.',
    'Nach einem langen Kampf **warf er das Handtuch**.',
    'Después de una larga lucha, finalmente **tiró la toalla**.',
    'Après un long combat, il a finalement **jeté l''éponge**.',
    'Após uma longa luta, ele finalmente **jogou a toalha**.',
    '["havlu attı"]', '["threw in the towel"]', '["kastade in handduken"]', '["Handtuch geworfen"]',
    '["tiró la toalla"]', '["jeté l''éponge"]', '["jogou a toalha"]',
    'advanced', false, 188),

(6, 'Sürprizi **ağzından kaçırdı** ve planı mahvetti.',
    'She **let the cat out of the bag** and ruined the surprise.',
    'Hon **skvallrade** och förstörde överraskningen.',
    'Sie hat **die Katze aus dem Sack gelassen** und die Überraschung ruiniert.',
    '**Descubrió el pastel** y arruinó la sorpresa.',
    'Elle a **vendu la mèche** et a gâché la surprise.',
    'Ela **soltou o segredo** e estragou a surpresa.',
    '["ağzından kaçırdı"]', '["let the cat out of the bag"]', '["skvallrade"]', '["Katze aus dem Sack gelassen"]',
    '["descubrió el pastel"]', '["vendu la mèche"]', '["soltou o segredo"]',
    'advanced', false, 189),

(6, 'Proje teslimi için sabaha kadar **gece yağını yaktı**.',
    'She **burned the midnight oil** to meet the project deadline.',
    'Hon **jobbade till långt in på natten** för att klara projektdeadlinen.',
    'Sie hat **bis tief in die Nacht gearbeitet**, um die Projektabgabe zu schaffen.',
    '**Quemó las pestañas** para cumplir el plazo del proyecto.',
    'Elle a **travaillé jusqu''au bout de la nuit** pour tenir le délai du projet.',
    'Ela **trabalhou até de madrugada** para cumprir o prazo do projeto.',
    '["gece yağını yaktı"]', '["burned the midnight oil"]', '["jobbade till långt in på natten"]', '["bis tief in die Nacht gearbeitet"]',
    '["quemó las pestañas"]', '["travaillé jusqu''au bout de la nuit"]', '["trabalhou até de madrugada"]',
    'advanced', false, 190);

-- ─────────────────────────────────────────────────────────────────
-- Category 7: Grammar Patterns — 3 beginner, 4 intermediate, 3 advanced
-- Existing: sort_order 271-300 → new: 301-310
-- ─────────────────────────────────────────────────────────────────
INSERT INTO sentences (
  category_id, text_tr, text_en, text_sv, text_de, text_es, text_fr, text_pt,
  keywords_tr, keywords_en, keywords_sv, keywords_de, keywords_es, keywords_fr, keywords_pt,
  difficulty, is_free, sort_order
) VALUES

(7, '**Yorgunluğuna rağmen** saatler boyu çalışmaya devam etti.',
    '**Despite** her tiredness, she kept working for hours.',
    '**Trots** sin trötthet fortsatte hon att arbeta i timmar.',
    '**Trotz** ihrer Müdigkeit arbeitete sie stundenlang weiter.',
    '**A pesar de** su cansancio, siguió trabajando durante horas.',
    '**Malgré** sa fatigue, elle a continué à travailler pendant des heures.',
    '**Apesar de** seu cansaço, ela continuou trabalhando por horas.',
    '["yorgunluğuna rağmen"]', '["despite"]', '["trots"]', '["trotz"]',
    '["a pesar de"]', '["malgré"]', '["apesar de"]',
    'beginner', false, 301),

(7, '**Görünüşe göre** plan son dakikada değişti.',
    '**It seems that** the plan changed at the last minute.',
    '**Det verkar som att** planen ändrades i sista stund.',
    '**Es scheint, dass** der Plan in letzter Minute geändert wurde.',
    '**Parece que** el plan cambió en el último momento.',
    '**Il semble que** le plan ait changé à la dernière minute.',
    '**Parece que** o plano mudou no último minuto.',
    '["görünüşe göre"]', '["it seems that"]', '["det verkar som att"]', '["es scheint dass"]',
    '["parece que"]', '["il semble que"]', '["parece que"]',
    'beginner', false, 302),

(7, '**Sanki** hiçbir şey olmamış gibi davranıyor.',
    'He''s acting **as if** nothing happened.',
    'Han beter sig **som om** ingenting hänt.',
    'Er verhält sich, **als ob** nichts passiert wäre.',
    'Actúa **como si** no hubiera pasado nada.',
    'Il se comporte **comme si** rien ne s''était passé.',
    'Ele está agindo **como se** nada tivesse acontecido.',
    '["sanki"]', '["as if"]', '["som om"]', '["als ob"]',
    '["como si"]', '["comme si"]', '["como se"]',
    'beginner', false, 303),

(7, '**Ne kadar çok** pratik yaparsan **o kadar çok** gelişirsin.',
    '**The more** you practise, **the more** you improve.',
    '**Ju mer** du övar, **desto mer** förbättras du.',
    '**Je mehr** du übst, **desto mehr** verbesserst du dich.',
    '**Cuanto más** practiques, **más** mejorarás.',
    '**Plus** tu pratiques, **plus** tu t''améliores.',
    '**Quanto mais** você pratica, **mais** você melhora.',
    '["ne kadar çok... o kadar çok"]', '["the more... the more"]', '["ju mer... desto mer"]', '["je mehr... desto mehr"]',
    '["cuanto más... más"]', '["plus... plus"]', '["quanto mais... mais"]',
    'intermediate', false, 304),

(7, 'Bu film izlemeye kesinlikle **değer**.',
    'This film is definitely **worth** watching.',
    'Den här filmen är definitivt **värd** att se.',
    'Dieser Film ist definitiv **sehenswert**.',
    'Esta película definitivamente **vale la pena** verla.',
    'Ce film **vaut vraiment** la peine d''être vu.',
    'Este filme definitivamente **vale a pena** assistir.',
    '["değer"]', '["worth watching"]', '["värd att se"]', '["sehenswert"]',
    '["vale la pena"]', '["vaut la peine"]', '["vale a pena"]',
    'intermediate', false, 305),

(7, 'Arabamı tamircide **tamir ettirdim**.',
    'I **had** my car **repaired** at the mechanic.',
    'Jag lät **reparera** bilen på verkstaden.',
    'Ich ließ mein Auto beim Mechaniker **reparieren**.',
    'Mandé **reparar** el coche en el taller.',
    'J''ai fait **réparer** ma voiture chez le mécanicien.',
    'Mandei **consertar** meu carro no mecânico.',
    '["tamir ettirdim"]', '["had repaired"]', '["lät reparera"]', '["ließ reparieren"]',
    '["mandé reparar"]', '["fait réparer"]', '["mandei consertar"]',
    'intermediate', false, 306),

(7, 'Güzel bir şarkı duyunca **kendimi dans etmekten alamıyorum**.',
    'I **can''t help** dancing when I hear a good song.',
    'Jag **kan inte låta bli** att dansa när jag hör en bra låt.',
    'Ich **kann nicht anders**, als zu tanzen, wenn ich ein gutes Lied höre.',
    '**No puedo evitar** bailar cuando escucho una buena canción.',
    'Je **ne peux pas m''empêcher** de danser quand j''entends une bonne chanson.',
    '**Não consigo me impedir** de dançar quando ouço uma boa música.',
    '["kendimi dans etmekten alamıyorum"]', '["can''t help"]', '["kan inte låta bli"]', '["kann nicht anders"]',
    '["no puedo evitar"]', '["ne peux pas m''empêcher"]', '["não consigo me impedir"]',
    'intermediate', false, 307),

(7, '**Söylemeye gerek yok**, sağlık her şeyden daha değerlidir.',
    '**It goes without saying** that health is more valuable than anything.',
    '**Det är självklart** att hälsa är mer värdefullt än allt annat.',
    '**Es versteht sich von selbst**, dass Gesundheit wertvoller ist als alles andere.',
    '**Huelga decir** que la salud es más valiosa que cualquier cosa.',
    '**Il va sans dire** que la santé est plus précieuse que tout.',
    '**Nem é preciso dizer** que a saúde é mais valiosa do que qualquer coisa.',
    '["söylemeye gerek yok"]', '["it goes without saying"]', '["det är självklart"]', '["es versteht sich von selbst"]',
    '["huelga decir"]', '["il va sans dire"]', '["nem é preciso dizer"]',
    'advanced', false, 308),

(7, 'Geçmişi düşünmenin **bir anlamı yok**.',
    '**There''s no point in** thinking about what''s already in the past.',
    '**Det finns ingen mening med** att tänka på det som redan är förbi.',
    '**Es hat keinen Sinn**, über Vergangenes nachzudenken.',
    '**No tiene sentido** pensar en lo que ya pasó.',
    '**Ça ne sert à rien** de penser à ce qui est déjà passé.',
    '**Não adianta** ficar pensando no que já passou.',
    '["bir anlamı yok"]', '["there''s no point in"]', '["ingen mening med"]', '["hat keinen Sinn"]',
    '["no tiene sentido"]', '["ça ne sert à rien"]', '["não adianta"]',
    'advanced', false, 309),

(7, 'Fransızcayı **bırak**, İngilizceyi bile tam konuşamıyorum.',
    'I can''t even speak English properly, **let alone** French.',
    'Jag kan inte ens engelska ordentligt, **än mindre** franska.',
    'Ich kann nicht mal Englisch richtig, **geschweige denn** Französisch.',
    'Ni siquiera sé hablar bien inglés, **mucho menos** francés.',
    'Je ne parle même pas bien anglais, **encore moins** le français.',
    'Não sei nem falar inglês direito, **muito menos** francês.',
    '["bırak"]', '["let alone"]', '["än mindre"]', '["geschweige denn"]',
    '["mucho menos"]', '["encore moins"]', '["muito menos"]',
    'advanced', false, 310);

-- ─────────────────────────────────────────────────────────────────
-- Category 8: Technology — 3 beginner, 4 intermediate, 3 advanced
-- Existing: sort_order 301-330 → new: 331-340
-- ─────────────────────────────────────────────────────────────────
INSERT INTO sentences (
  category_id, text_tr, text_en, text_sv, text_de, text_es, text_fr, text_pt,
  keywords_tr, keywords_en, keywords_sv, keywords_de, keywords_es, keywords_fr, keywords_pt,
  difficulty, is_free, sort_order
) VALUES

(8, 'Hata mesajının **ekran görüntüsünü al** ve bana gönder.',
    '**Take a screenshot** of the error message and send it to me.',
    '**Ta en skärmdump** av felmeddelandet och skicka det till mig.',
    'Mach einen **Screenshot** der Fehlermeldung und schick ihn mir.',
    '**Haz una captura de pantalla** del mensaje de error y envíamela.',
    '**Fais une capture d''écran** du message d''erreur et envoie-la moi.',
    '**Tire um print** da mensagem de erro e me envie.',
    '["ekran görüntüsünü al"]', '["take a screenshot"]', '["ta en skärmdump"]', '["Screenshot"]',
    '["captura de pantalla"]', '["capture d''écran"]', '["print"]',
    'beginner', false, 331),

(8, 'Toplantıda konuşmuyorsan kendini **sustur**.',
    '**Mute yourself** during the meeting if you''re not speaking.',
    '**Stäng av mikrofonen** under mötet om du inte pratar.',
    '**Schalte dich stumm** im Meeting, wenn du nicht sprichst.',
    '**Silencia** el micrófono durante la reunión si no estás hablando.',
    '**Coupe ton micro** pendant la réunion si tu ne parles pas.',
    '**Silencie seu microfone** durante a reunião se não estiver falando.',
    '["sustur"]', '["mute yourself"]', '["stäng av mikrofonen"]', '["schalte stumm"]',
    '["silencia"]', '["coupe ton micro"]', '["silencie seu microfone"]',
    'beginner', false, 332),

(8, 'Uygulama yavaşladıysa **önbelleği temizle**.',
    '**Clear the cache** if the app is running slowly.',
    '**Rensa cachen** om appen är långsam.',
    '**Leere den Cache**, wenn die App langsam läuft.',
    '**Borra la caché** si la aplicación va lenta.',
    '**Vide le cache** si l''application est lente.',
    '**Limpe o cache** se o aplicativo estiver lento.',
    '["önbelleği temizle"]', '["clear the cache"]', '["rensa cachen"]', '["Cache leeren"]',
    '["borra la caché"]', '["vide le cache"]', '["limpe o cache"]',
    'beginner', false, 333),

(8, 'Bu akşam sosyal medyada **canlı yayın açacağım**.',
    'I''ll **go live** on social media tonight.',
    'Jag ska **sända live** på sociala medier ikväll.',
    'Ich werde heute Abend auf Social Media **live gehen**.',
    'Esta noche voy a **hacer un directo** en redes sociales.',
    'Ce soir je vais **faire un live** sur les réseaux sociaux.',
    'Esta noite vou **fazer uma live** nas redes sociais.',
    '["canlı yayın açacağım"]', '["go live"]', '["sända live"]', '["live gehen"]',
    '["hacer un directo"]', '["faire un live"]', '["fazer uma live"]',
    'intermediate', false, 334),

(8, 'Dikkatim dağılmasın diye bir süre **çevrimdışına geçtim**.',
    'I **went offline** for a while to avoid distractions.',
    'Jag **gick offline** ett tag för att undvika distraktioner.',
    'Ich bin eine Weile **offline gegangen**, um Ablenkungen zu vermeiden.',
    'Me **desconecté** un rato para evitar distracciones.',
    'Je me suis **déconnecté** un moment pour éviter les distractions.',
    'Fiquei **offline** por um tempo para evitar distrações.',
    '["çevrimdışına geçtim"]', '["went offline"]', '["gick offline"]', '["offline gegangen"]',
    '["desconecté"]', '["déconnecté"]', '["offline"]',
    'intermediate', false, 335),

(8, 'Bu mesajı **sabitle** ki herkes kolayca bulsun.',
    '**Pin** this message so everyone can find it easily.',
    '**Fäst** det här meddelandet så att alla kan hitta det lätt.',
    '**Hefte** diese Nachricht an, damit alle sie leicht finden können.',
    '**Fija** este mensaje para que todos puedan encontrarlo fácilmente.',
    '**Épingle** ce message pour que tout le monde puisse le trouver facilement.',
    '**Fixe** esta mensagem para que todos possam encontrá-la facilmente.',
    '["sabitle"]', '["pin"]', '["fäst"]', '["hefte an"]',
    '["fija"]', '["épingle"]', '["fixe"]',
    'intermediate', false, 336),

(8, 'Silinen dosyaları **kurtarma** yazılımıyla geri aldım.',
    'I **recovered** the deleted files using recovery software.',
    'Jag **återställde** de raderade filerna med återställningsprogram.',
    'Ich habe die gelöschten Dateien mit einer Wiederherstellungssoftware **wiederhergestellt**.',
    '**Recuperé** los archivos eliminados con un software de recuperación.',
    'J''ai **récupéré** les fichiers supprimés avec un logiciel de récupération.',
    '**Recuperei** os arquivos deletados com um software de recuperação.',
    '["kurtarma"]', '["recovered"]', '["återställde"]', '["wiederhergestellt"]',
    '["recuperé"]', '["récupéré"]', '["recuperei"]',
    'intermediate', false, 337),

(8, 'Tekrar eden görevleri **otomatize etmek** için bir betik yazdım.',
    'I wrote a script to **automate** repetitive tasks.',
    'Jag skrev ett skript för att **automatisera** repetitiva uppgifter.',
    'Ich habe ein Skript geschrieben, um sich wiederholende Aufgaben zu **automatisieren**.',
    'Escribí un script para **automatizar** las tareas repetitivas.',
    'J''ai écrit un script pour **automatiser** les tâches répétitives.',
    'Escrevi um script para **automatizar** tarefas repetitivas.',
    '["otomatize etmek"]', '["automate"]', '["automatisera"]', '["automatisieren"]',
    '["automatizar"]', '["automatiser"]', '["automatizar"]',
    'advanced', false, 338),

(8, 'Bu proje **açık kaynaklı** — herkes katkıda bulunabilir.',
    'This project is **open source** — anyone can contribute.',
    'Det här projektet är **öppen källkod** — vem som helst kan bidra.',
    'Dieses Projekt ist **Open Source** — jeder kann dazu beitragen.',
    'Este proyecto es de **código abierto** — cualquiera puede contribuir.',
    'Ce projet est **open source** — tout le monde peut contribuer.',
    'Este projeto é **open source** — qualquer pessoa pode contribuir.',
    '["açık kaynaklı"]', '["open source"]', '["öppen källkod"]', '["Open Source"]',
    '["código abierto"]', '["open source"]', '["open source"]',
    'advanced', false, 339),

(8, 'Kişisel bilgileri korumak için **veri şifreleme** şarttır.',
    '**Data encryption** is essential to protect personal information.',
    '**Datakryptering** är viktigt för att skydda personuppgifter.',
    '**Datenverschlüsselung** ist unerlässlich zum Schutz persönlicher Daten.',
    'El **cifrado de datos** es esencial para proteger la información personal.',
    'Le **chiffrement des données** est essentiel pour protéger les informations personnelles.',
    'A **criptografia de dados** é essencial para proteger informações pessoais.',
    '["veri şifreleme"]', '["data encryption"]', '["datakryptering"]', '["Datenverschlüsselung"]',
    '["cifrado de datos"]', '["chiffrement des données"]', '["criptografia de dados"]',
    'advanced', false, 340);

-- ─────────────────────────────────────────────────────────────────
-- Category 9: Health — 3 beginner, 4 intermediate, 3 advanced
-- Existing: sort_order 331-360 → new: 361-370
-- ─────────────────────────────────────────────────────────────────
INSERT INTO sentences (
  category_id, text_tr, text_en, text_sv, text_de, text_es, text_fr, text_pt,
  keywords_tr, keywords_en, keywords_sv, keywords_de, keywords_es, keywords_fr, keywords_pt,
  difficulty, is_free, sort_order
) VALUES

(9, 'Doktor benden **kan tahlili** yaptırmamı istedi.',
    'The doctor asked me to get a **blood test**.',
    'Läkaren bad mig att ta ett **blodprov**.',
    'Der Arzt bat mich, eine **Blutuntersuchung** machen zu lassen.',
    'El médico me pidió que me hiciera un **análisis de sangre**.',
    'Le médecin m''a demandé de faire une **prise de sang**.',
    'O médico me pediu para fazer um **exame de sangue**.',
    '["kan tahlili"]', '["blood test"]', '["blodprov"]', '["Blutuntersuchung"]',
    '["análisis de sangre"]', '["prise de sang"]', '["exame de sangue"]',
    'beginner', false, 361),

(9, 'Bu ilacı günde iki kez **almanız** gerekiyor.',
    'You need to **take this medication** twice a day.',
    'Du behöver **ta det här läkemedlet** två gånger om dagen.',
    'Sie müssen dieses Medikament zweimal täglich **einnehmen**.',
    'Tiene que **tomar este medicamento** dos veces al día.',
    'Vous devez **prendre ce médicament** deux fois par jour.',
    'Você precisa **tomar este medicamento** duas vezes ao dia.',
    '["almanız"]', '["take this medication"]', '["ta läkemedlet"]', '["einnehmen"]',
    '["tomar este medicamento"]', '["prendre ce médicament"]', '["tomar este medicamento"]',
    'beginner', false, 362),

(9, 'Bir hafta dinlenirsen **kısa sürede kendine gelirsin**.',
    'Rest for a week and you''ll **be back on your feet** in no time.',
    'Vila en vecka och du är **på benen igen** på nolltid.',
    'Ruh dich eine Woche aus und du bist **schnell wieder auf den Beinen**.',
    'Descansa una semana y estarás **de vuelta en pie** en poco tiempo.',
    'Repose-toi une semaine et tu seras **sur pied** en un rien de temps.',
    'Descanse uma semana e você estará **de pé** em pouco tempo.',
    '["kısa sürede kendine gelirsin"]', '["back on your feet"]', '["på benen igen"]', '["wieder auf den Beinen"]',
    '["de vuelta en pie"]', '["sur pied"]', '["de pé"]',
    'beginner', false, 363),

(9, 'Doktor beni bir uzmana **sevk etti**.',
    'The doctor **referred me to** a specialist.',
    'Läkaren **remitterade** mig till en specialist.',
    'Der Arzt hat mich an einen Spezialisten **überwiesen**.',
    'El médico me **derivó a** un especialista.',
    'Le médecin m''a **orienté vers** un spécialiste.',
    'O médico me **encaminhou para** um especialista.',
    '["sevk etti"]', '["referred me to"]', '["remitterade"]', '["überwiesen"]',
    '["derivó a"]', '["orienté vers"]', '["encaminhou para"]',
    'intermediate', false, 364),

(9, 'Bu semptomlar çoğunlukla **strese bağlı** olabiliyor.',
    'These symptoms can often be **stress-related**.',
    'Dessa symtom kan ofta vara **stressrelaterade**.',
    'Diese Symptome können oft **stressbedingt** sein.',
    'Estos síntomas a menudo pueden ser **relacionados con el estrés**.',
    'Ces symptômes peuvent souvent être **liés au stress**.',
    'Esses sintomas muitas vezes podem ser **relacionados ao estresse**.',
    '["strese bağlı"]', '["stress-related"]', '["stressrelaterade"]', '["stressbedingt"]',
    '["relacionados con el estrés"]', '["liés au stress"]', '["relacionados ao estresse"]',
    'intermediate', false, 365),

(9, 'Düzenli egzersiz **kalp hastalığı riskini azaltır**.',
    'Regular exercise **reduces the risk of** heart disease.',
    'Regelbunden motion **minskar risken för** hjärtsjukdom.',
    'Regelmäßiges Training **verringert das Risiko** von Herzerkrankungen.',
    'El ejercicio regular **reduce el riesgo de** enfermedades cardíacas.',
    'L''exercice régulier **réduit le risque** de maladies cardiaques.',
    'O exercício regular **reduz o risco de** doenças cardíacas.',
    '["kalp hastalığı riskini azaltır"]', '["reduces the risk of"]', '["minskar risken för"]', '["verringert das Risiko"]',
    '["reduce el riesgo de"]', '["réduit le risque de"]', '["reduz o risco de"]',
    'intermediate', false, 366),

(9, 'Sağlıklı kalmak istiyorsan **ne yediğine dikkat et**.',
    'If you want to stay healthy, **watch what you eat**.',
    'Om du vill hålla dig frisk måste du **se upp med vad du äter**.',
    'Wenn du gesund bleiben willst, **pass auf, was du isst**.',
    'Si quieres mantenerte sano, **cuida lo que comes**.',
    'Si tu veux rester en bonne santé, **fais attention à ce que tu manges**.',
    'Se você quer se manter saudável, **cuide o que come**.',
    '["ne yediğine dikkat et"]', '["watch what you eat"]', '["se upp med vad du äter"]', '["pass auf was du isst"]',
    '["cuida lo que comes"]', '["fais attention à ce que tu manges"]', '["cuide o que come"]',
    'intermediate', false, 367),

(9, 'Bu durum **genetik faktörlerle ilişkilendiriliyor**.',
    'This condition is **associated with** genetic factors.',
    'Detta tillstånd **förknippas med** genetiska faktorer.',
    'Dieser Zustand wird mit **genetischen Faktoren in Verbindung gebracht**.',
    'Esta condición se **asocia con** factores genéticos.',
    'Cette condition est **associée à** des facteurs génétiques.',
    'Esta condição está **associada a** fatores genéticos.',
    '["genetik faktörlerle ilişkilendiriliyor"]', '["associated with"]', '["förknippas med"]', '["in Verbindung gebracht"]',
    '["asocia con"]', '["associée à"]', '["associada a"]',
    'advanced', false, 368),

(9, 'Terapi, stresle başa çıkmak için **baş etme stratejileri** geliştirmeye yardımcı olur.',
    'Therapy helps develop **coping strategies** for dealing with stress.',
    'Terapi hjälper till att utveckla **hanteringsstrategier** för att hantera stress.',
    'Therapie hilft dabei, **Bewältigungsstrategien** für den Umgang mit Stress zu entwickeln.',
    'La terapia ayuda a desarrollar **estrategias de afrontamiento** del estrés.',
    'La thérapie aide à développer des **stratégies d''adaptation** pour gérer le stress.',
    'A terapia ajuda a desenvolver **estratégias de enfrentamento** para lidar com o estresse.',
    '["baş etme stratejileri"]', '["coping strategies"]', '["hanteringsstrategier"]', '["Bewältigungsstrategien"]',
    '["estrategias de afrontamiento"]', '["stratégies d''adaptation"]', '["estratégias de enfrentamento"]',
    'advanced', false, 369),

(9, 'Ağrıya karşı **toleransı** çok yüksek.',
    'She has a very high **pain tolerance**.',
    'Hon har en mycket hög **smärttolerans**.',
    'Sie hat eine sehr hohe **Schmerztoleranz**.',
    'Tiene una **tolerancia al dolor** muy alta.',
    'Elle a une **tolérance à la douleur** très élevée.',
    'Ela tem uma **tolerância à dor** muito alta.',
    '["toleransı"]', '["pain tolerance"]', '["smärttolerans"]', '["Schmerztoleranz"]',
    '["tolerancia al dolor"]', '["tolérance à la douleur"]', '["tolerância à dor"]',
    'advanced', false, 370);

-- ─────────────────────────────────────────────────────────────────
-- Category 10: Social & Modern — 3 beginner, 4 intermediate, 3 advanced
-- No existing sentences → sort_order 1-10
-- ─────────────────────────────────────────────────────────────────
INSERT INTO sentences (
  category_id, text_tr, text_en, text_sv, text_de, text_es, text_fr, text_pt,
  keywords_tr, keywords_en, keywords_sv, keywords_de, keywords_es, keywords_fr, keywords_pt,
  difficulty, is_free, sort_order
) VALUES

(10, 'Seni **geri takip ettim**, bakalım ne paylaşıyorsun.',
     'I **followed you back** — let''s see what you post.',
     'Jag **följde tillbaka** dig — vi får se vad du delar.',
     'Ich habe dich **zurückgefolgt** — mal sehen, was du postest.',
     'Te **seguí de vuelta** — vamos a ver qué publicas.',
     'Je t''ai **suivi en retour** — voyons ce que tu publies.',
     'Te **segui de volta** — vamos ver o que você posta.',
     '["geri takip ettim"]', '["followed back"]', '["följde tillbaka"]', '["zurückgefolgt"]',
     '["seguí de vuelta"]', '["suivi en retour"]', '["segui de volta"]',
     'beginner', false, 1),

(10, 'Bu konu şu an sosyal medyada **gündemde**.',
     'This topic is currently **trending** on social media.',
     'Det här ämnet **trendar** just nu på sociala medier.',
     'Dieses Thema ist gerade in den sozialen Medien **im Trend**.',
     'Este tema está **en tendencia** en las redes sociales ahora mismo.',
     'Ce sujet est actuellement **en tendance** sur les réseaux sociaux.',
     'Este assunto está **em alta** nas redes sociais agora.',
     '["gündemde"]', '["trending"]', '["trendar"]', '["im Trend"]',
     '["en tendencia"]', '["en tendance"]', '["em alta"]',
     'beginner', false, 2),

(10, 'Yeni bir **profil fotoğrafı** yükledi, çok güzel olmuş.',
     'She uploaded a new **profile picture** — it looks great.',
     'Hon laddade upp ett nytt **profilfoto** — det ser bra ut.',
     'Sie hat ein neues **Profilbild** hochgeladen — es sieht toll aus.',
     'Subió una nueva **foto de perfil** — quedó muy bien.',
     'Elle a mis une nouvelle **photo de profil** — ça rend très bien.',
     'Ela carregou uma nova **foto de perfil** — ficou muito bonita.',
     '["profil fotoğrafı"]', '["profile picture"]', '["profilfoto"]', '["Profilbild"]',
     '["foto de perfil"]', '["photo de profil"]', '["foto de perfil"]',
     'beginner', false, 3),

(10, 'Mesajımı **gördü ama cevap vermedi** — bu çok sinir bozucu.',
     'She **left me on read** without replying — so annoying.',
     'Hon **läste men svarade inte** — det är verkligen irriterande.',
     'Sie hat meine Nachricht **gelesen aber nicht geantwortet** — wirklich nervig.',
     'Me **dejó en visto** sin responder — qué molesto.',
     'Elle m''a **laissé en lu** sans répondre — vraiment agaçant.',
     'Ela me **deixou no visto** sem responder — que chato.',
     '["gördü ama cevap vermedi"]', '["left me on read"]', '["läste men svarade inte"]', '["gelesen aber nicht geantwortet"]',
     '["dejó en visto"]', '["laissé en lu"]', '["deixou no visto"]',
     'intermediate', false, 4),

(10, 'Üç haftalık yazışmanın ardından birden **hayatımdan silindi**.',
     'After three weeks of messaging, he suddenly **ghosted** me.',
     'Efter tre veckor av meddelanden **ghostade** han mig plötsligt.',
     'Nach drei Wochen Nachrichten hat er mich plötzlich **geghostet**.',
     'Después de tres semanas escribiéndome, de repente me **dejó en el aire**.',
     'Après trois semaines d''échanges, il m''a soudainement **ghosté**.',
     'Depois de três semanas de mensagens, ele de repente me **deu um ghosting**.',
     '["hayatımdan silindi"]', '["ghosted"]', '["ghostade"]', '["geghostet"]',
     '["dejó en el aire"]', '["ghosté"]', '["ghosting"]',
     'intermediate', false, 5),

(10, 'Her etkinliğe koşuyorum çünkü **bir şeyleri kaçırma korkusu** yaşıyorum.',
     'I rush to every event because I have **FOMO** — fear of missing out.',
     'Jag rusar till varje event för att jag har **FOMO** — rädslan att missa något.',
     'Ich hetze zu jedem Event, weil ich **FOMO** habe — die Angst, etwas zu verpassen.',
     'Me apresuro a cada evento porque tengo **FOMO** — el miedo de perderse algo.',
     'Je cours à chaque événement parce que j''ai la **FOMO** — la peur de rater quelque chose.',
     'Corro para cada evento porque tenho **FOMO** — o medo de perder algo.',
     '["bir şeyleri kaçırma korkusu"]', '["FOMO"]', '["FOMO"]', '["FOMO"]',
     '["FOMO"]', '["FOMO"]', '["FOMO"]',
     'intermediate', false, 6),

(10, 'Artık tam zamanlı bir **içerik üreticisiyim**, şirkette çalışmıyorum.',
     'I''m now a full-time **content creator** — I no longer work at a company.',
     'Jag är nu en heltids **innehållsskapare** — jag jobbar inte längre på ett företag.',
     'Ich bin jetzt ein Vollzeit-**Content Creator** — ich arbeite nicht mehr in einer Firma.',
     'Ahora soy **creador de contenido** a tiempo completo — ya no trabajo en una empresa.',
     'Je suis maintenant **créateur de contenu** à temps plein — je ne travaille plus en entreprise.',
     'Agora sou **criador de conteúdo** em tempo integral — não trabalho mais em empresa.',
     '["içerik üreticisiyim"]', '["content creator"]', '["innehållsskapare"]', '["Content Creator"]',
     '["creador de contenido"]', '["créateur de contenu"]', '["criador de conteúdo"]',
     'intermediate', false, 7),

(10, 'Sosyal medya **yankı odaları** oluşturuyor — hep aynı görüşleri duyuyorsunuz.',
     'Social media creates **echo chambers** — you only ever hear the same views.',
     'Sociala medier skapar **ekokammare** — du hör alltid bara samma åsikter.',
     'Soziale Medien schaffen **Echokammern** — man hört immer nur dieselben Meinungen.',
     'Las redes sociales crean **cámaras de eco** — siempre escuchas las mismas opiniones.',
     'Les réseaux sociaux créent des **chambres d''écho** — on n''entend que les mêmes opinions.',
     'As redes sociais criam **câmaras de eco** — você só ouve sempre as mesmas opiniões.',
     '["yankı odaları"]', '["echo chambers"]', '["ekokammare"]', '["Echokammern"]',
     '["cámaras de eco"]', '["chambres d''écho"]', '["câmaras de eco"]',
     'advanced', false, 8),

(10, '**İptal kültürü** artık her yerde konuşuluyor — ama herkese farklı geliyor.',
     '**Cancel culture** is discussed everywhere now — but everyone sees it differently.',
     '**Cancelkultur** diskuteras nu överallt — men alla ser det på olika sätt.',
     '**Cancel Culture** wird jetzt überall diskutiert — aber jeder sieht es anders.',
     'La **cultura de la cancelación** se debate en todas partes — pero cada uno lo ve diferente.',
     'La **culture de l''annulation** est discutée partout — mais chacun le voit différemment.',
     'A **cultura do cancelamento** é debatida em todo lugar — mas cada um vê de forma diferente.',
     '["iptal kültürü"]', '["cancel culture"]', '["cancelkultur"]', '["Cancel Culture"]',
     '["cultura de la cancelación"]', '["culture de l''annulation"]', '["cultura do cancelamento"]',
     'advanced', false, 9),

(10, 'İnternette bıraktığın **dijital iz** kalıcıdır, dikkatli ol.',
     'The **digital footprint** you leave online is permanent — be careful.',
     'Det **digitala fotavtryck** du lämnar online är permanent — var försiktig.',
     'Der **digitale Fußabdruck**, den du im Internet hinterlässt, ist dauerhaft — sei vorsichtig.',
     'La **huella digital** que dejas en internet es permanente — ten cuidado.',
     'L''**empreinte numérique** que tu laisses sur internet est permanente — fais attention.',
     'A **pegada digital** que você deixa na internet é permanente — tenha cuidado.',
     '["dijital iz"]', '["digital footprint"]', '["digitala fotavtryck"]', '["digitale Fußabdruck"]',
     '["huella digital"]', '["empreinte numérique"]', '["pegada digital"]',
     'advanced', false, 10);
