-- ============================================================
-- Seed: dialog_categories
-- 15 core categories for Dialog feature
-- ============================================================

insert into public.dialog_categories (
  slug,
  title_tr, title_en, title_sv, title_de, title_es, title_fr, title_pt,
  description_tr, description_en, description_sv, description_de, description_es, description_fr, description_pt,
  icon,
  sort_order,
  is_active
) values
(
  'greetings-introductions',
  'Selamlaşma ve Tanışma', 'Greetings & Introductions', 'Hälsningar och presentation', 'Begrüßung und Vorstellen', 'Saludos e introducciones', 'Salutations et présentations', 'Saudações e apresentações',
  'Selamlaşma, kendini tanıtma ve temel tanışma diyalogları.',
  'Dialogs for greeting, introducing yourself, and basic first-time conversations.',
  'Dialoger för hälsningar, att presentera sig och enkla första samtal.',
  'Dialoge zum Begrüßen, Vorstellen und für einfache erste Gespräche.',
  'Diálogos para saludar, presentarse y mantener conversaciones básicas de primer encuentro.',
  'Dialogues pour saluer, se présenter et tenir de premières conversations simples.',
  'Diálogos para cumprimentar, se apresentar e manter conversas iniciais básicas.',
  '👋',
  1,
  true
),
(
  'cafe-restaurant',
  'Kafe ve Restoran', 'Cafe & Restaurant', 'Kafé och restaurang', 'Café und Restaurant', 'Cafetería y restaurante', 'Café et restaurant', 'Café e restaurante',
  'Sipariş verme, tercih belirtme, hesap isteme ve masa ile ilgili diyaloglar.',
  'Dialogs for ordering, stating preferences, asking for the bill, and handling table-related situations.',
  'Dialoger för att beställa, ange preferenser, be om notan och hantera situationer vid bordet.',
  'Dialoge zum Bestellen, Wünsche äußern, nach der Rechnung fragen und Situationen am Tisch.',
  'Diálogos para pedir, expresar preferencias, pedir la cuenta y manejar situaciones en la mesa.',
  'Dialogues pour commander, exprimer des préférences, demander l’addition et gérer des situations à table.',
  'Diálogos para pedir, indicar preferências, pedir a conta e lidar com situações à mesa.',
  '☕',
  2,
  true
),
(
  'shopping-store',
  'Alışveriş ve Mağaza', 'Shopping & Store', 'Shopping och butik', 'Einkaufen und Geschäft', 'Compras y tienda', 'Achats et magasin', 'Compras e loja',
  'Ürün sorma, beden bulma, fiyat öğrenme, ödeme ve iade diyalogları.',
  'Dialogs for asking about products, finding sizes, checking prices, paying, and returns.',
  'Dialoger för att fråga om produkter, hitta storlekar, kontrollera priser, betala och returnera.',
  'Dialoge zum Nachfragen über Produkte, Größen finden, Preise prüfen, bezahlen und umtauschen.',
  'Diálogos para preguntar por productos, encontrar tallas, consultar precios, pagar y hacer devoluciones.',
  'Dialogues pour demander des produits, trouver des tailles, vérifier les prix, payer et faire des retours.',
  'Diálogos para perguntar sobre produtos, encontrar tamanhos, verificar preços, pagar e fazer devoluções.',
  '🛍️',
  3,
  true
),
(
  'directions-navigation',
  'Yol Tarifi ve Adres Sorma', 'Directions & Navigation', 'Vägbeskrivning och navigation', 'Wegbeschreibung und Orientierung', 'Direcciones y orientación', 'Indications et orientation', 'Direções e localização',
  'Adres sorma, yön tarif etme ve bir yeri bulma diyalogları.',
  'Dialogs for asking for directions, giving directions, and finding places.',
  'Dialoger för att fråga efter vägen, ge vägbeskrivningar och hitta platser.',
  'Dialoge zum Nach-dem-Weg-Fragen, Wegbeschreibungen geben und Orte finden.',
  'Diálogos para pedir indicaciones, dar direcciones y encontrar lugares.',
  'Dialogues pour demander son chemin, donner des indications et trouver des lieux.',
  'Diálogos para pedir direções, orientar caminhos e encontrar lugares.',
  '🧭',
  4,
  true
),
(
  'taxi-transport',
  'Taksi ve Ulaşım', 'Taxi & Transport', 'Taxi och transport', 'Taxi und Verkehr', 'Taxi y transporte', 'Taxi et transport', 'Táxi e transporte',
  'Taksiye binme, toplu taşıma, bilet ve rota ile ilgili diyaloglar.',
  'Dialogs for taking a taxi, using public transport, buying tickets, and discussing routes.',
  'Dialoger för taxi, kollektivtrafik, biljetter och rutter.',
  'Dialoge für Taxi, öffentliche Verkehrsmittel, Fahrkarten und Routen.',
  'Diálogos para tomar un taxi, usar transporte público, comprar billetes y hablar de rutas.',
  'Dialogues pour prendre un taxi, utiliser les transports publics, acheter des billets et parler des itinéraires.',
  'Diálogos para pegar táxi, usar transporte público, comprar bilhetes e falar sobre rotas.',
  '🚕',
  5,
  true
),
(
  'airport-checkin',
  'Havaalanı ve Check-in', 'Airport & Check-in', 'Flygplats och incheckning', 'Flughafen und Check-in', 'Aeropuerto y check-in', 'Aéroport et enregistrement', 'Aeroporto e check-in',
  'Uçuş, bagaj, check-in, kapı ve havalimanı süreçleri ile ilgili diyaloglar.',
  'Dialogs for flights, baggage, check-in, gate information, and airport processes.',
  'Dialoger om flyg, bagage, incheckning, gate-information och processer på flygplatsen.',
  'Dialoge über Flüge, Gepäck, Check-in, Gate-Informationen und Abläufe am Flughafen.',
  'Diálogos sobre vuelos, equipaje, check-in, puerta de embarque y procesos del aeropuerto.',
  'Dialogues sur les vols, les bagages, l’enregistrement, la porte d’embarquement et les procédures à l’aéroport.',
  'Diálogos sobre voos, bagagem, check-in, portão e processos no aeroporto.',
  '✈️',
  6,
  true
),
(
  'hotel-accommodation',
  'Otel ve Konaklama', 'Hotel & Accommodation', 'Hotell och boende', 'Hotel und Unterkunft', 'Hotel y alojamiento', 'Hôtel et hébergement', 'Hotel e hospedagem',
  'Rezervasyon, giriş, oda sorunları ve çıkış ile ilgili diyaloglar.',
  'Dialogs for reservations, check-in, room issues, and check-out.',
  'Dialoger för bokning, incheckning, problem med rummet och utcheckning.',
  'Dialoge zu Reservierung, Check-in, Zimmerproblemen und Check-out.',
  'Diálogos sobre reservas, entrada, problemas con la habitación y salida.',
  'Dialogues sur les réservations, l’arrivée, les problèmes de chambre et le départ.',
  'Diálogos sobre reserva, check-in, problemas no quarto e check-out.',
  '🏨',
  7,
  true
),
(
  'work-interview',
  'İş Görüşmesi ve Profesyonel Tanışma', 'Job Interview & Professional Introduction', 'Jobbintervju och professionell presentation', 'Bewerbungsgespräch und berufliche Vorstellung', 'Entrevista de trabajo y presentación profesional', 'Entretien d’embauche et présentation professionnelle', 'Entrevista de emprego e apresentação profissional',
  'Kendini tanıtma, deneyim anlatma ve iş görüşmesi diyalogları.',
  'Dialogs for introducing yourself professionally, describing experience, and handling interviews.',
  'Dialoger för att presentera sig professionellt, beskriva erfarenhet och hantera intervjuer.',
  'Dialoge zur beruflichen Vorstellung, Beschreibung von Erfahrung und Bewerbungsgesprächen.',
  'Diálogos para presentarse de forma profesional, hablar de experiencia y gestionar entrevistas.',
  'Dialogues pour se présenter professionnellement, décrire son expérience et gérer des entretiens.',
  'Diálogos para se apresentar profissionalmente, descrever experiência e lidar com entrevistas.',
  '💼',
  8,
  true
),
(
  'work-daily',
  'İş Yerinde Günlük İletişim', 'Workplace Daily Communication', 'Daglig kommunikation på jobbet', 'Tägliche Kommunikation am Arbeitsplatz', 'Comunicación diaria en el trabajo', 'Communication quotidienne au travail', 'Comunicação diária no trabalho',
  'Toplantı, yardım isteme, güncelleme verme ve iş içi kısa diyaloglar.',
  'Dialogs for meetings, asking for help, giving updates, and short workplace interactions.',
  'Dialoger om möten, att be om hjälp, ge uppdateringar och korta interaktioner på jobbet.',
  'Dialoge über Meetings, um Hilfe bitten, Updates geben und kurze Interaktionen am Arbeitsplatz.',
  'Diálogos sobre reuniones, pedir ayuda, dar actualizaciones e interacciones breves en el trabajo.',
  'Dialogues sur les réunions, demander de l’aide, donner des mises à jour et les interactions courtes au travail.',
  'Diálogos sobre reuniões, pedir ajuda, dar atualizações e interações curtas no trabalho.',
  '🧑‍💻',
  9,
  true
),
(
  'health-pharmacy',
  'Doktor, Eczane ve Sağlık', 'Doctor, Pharmacy & Health', 'Läkare, apotek och hälsa', 'Arzt, Apotheke und Gesundheit', 'Doctor, farmacia y salud', 'Médecin, pharmacie et santé', 'Médico, farmácia e saúde',
  'Belirti anlatma, ilaç sorma, randevu ve sağlıkla ilgili temel diyaloglar.',
  'Dialogs for describing symptoms, asking about medicine, making appointments, and basic health situations.',
  'Dialoger för att beskriva symptom, fråga om medicin, boka tider och vanliga hälsosituationer.',
  'Dialoge zum Beschreiben von Symptomen, nach Medikamenten fragen, Termine vereinbaren und grundlegende Gesundheitssituationen.',
  'Diálogos para describir síntomas, preguntar por medicinas, pedir citas y manejar situaciones básicas de salud.',
  'Dialogues pour décrire des symptômes, demander des médicaments, prendre rendez-vous et gérer des situations de santé courantes.',
  'Diálogos para descrever sintomas, perguntar sobre remédios, marcar consultas e lidar com situações básicas de saúde.',
  '🏥',
  10,
  true
),
(
  'school-course',
  'Okul ve Kurs', 'School & Course', 'Skola och kurs', 'Schule und Kurs', 'Escuela y curso', 'École et cours', 'Escola e curso',
  'Öğretmenle konuşma, soru sorma, ödev ve derse katılım diyalogları.',
  'Dialogs for speaking with teachers, asking questions, discussing homework, and participating in class.',
  'Dialoger för att prata med lärare, ställa frågor, prata om läxor och delta i lektioner.',
  'Dialoge zum Sprechen mit Lehrern, Fragen stellen, Hausaufgaben besprechen und am Unterricht teilnehmen.',
  'Diálogos para hablar con profesores, hacer preguntas, hablar de deberes y participar en clase.',
  'Dialogues pour parler avec les enseignants, poser des questions, discuter des devoirs et participer au cours.',
  'Diálogos para falar com professores, fazer perguntas, falar sobre tarefas e participar da aula.',
  '📚',
  11,
  true
),
(
  'friends-social-plans',
  'Arkadaşlarla Plan Yapma', 'Making Plans with Friends', 'Planer med vänner', 'Pläne mit Freunden machen', 'Hacer planes con amigos', 'Faire des plans avec des amis', 'Fazer planos com amigos',
  'Buluşma ayarlama, davet etme, erteleme ve sosyal plan diyalogları.',
  'Dialogs for making plans, inviting, postponing, and arranging social activities.',
  'Dialoger för att göra planer, bjuda in, skjuta upp och ordna sociala aktiviteter.',
  'Dialoge zum Planen, Einladen, Verschieben und Organisieren sozialer Aktivitäten.',
  'Diálogos para hacer planes, invitar, posponer y organizar actividades sociales.',
  'Dialogues pour faire des projets, inviter, reporter et organiser des activités sociales.',
  'Diálogos para fazer planos, convidar, adiar e organizar atividades sociais.',
  '🎉',
  12,
  true
),
(
  'phone-calls',
  'Telefon Görüşmeleri', 'Phone Calls', 'Telefonsamtal', 'Telefonate', 'Llamadas telefónicas', 'Appels téléphoniques', 'Chamadas telefônicas',
  'Arama başlatma, birini isteme, mesaj bırakma ve geri arama diyalogları.',
  'Dialogs for starting calls, asking for someone, leaving messages, and calling back.',
  'Dialoger för att starta samtal, fråga efter någon, lämna meddelanden och ringa tillbaka.',
  'Dialoge zum Telefonieren, nach jemandem fragen, Nachrichten hinterlassen und zurückrufen.',
  'Diálogos para iniciar llamadas, pedir hablar con alguien, dejar mensajes y devolver llamadas.',
  'Dialogues pour commencer un appel, demander quelqu’un, laisser un message et rappeler.',
  'Diálogos para iniciar chamadas, pedir por alguém, deixar recados e retornar ligações.',
  '📞',
  13,
  true
),
(
  'official-services',
  'Resmî İşlemler ve Kurumlar', 'Official Services & Institutions', 'Myndigheter och officiella tjänster', 'Behörden und offizielle Dienste', 'Servicios oficiales e instituciones', 'Services officiels et administrations', 'Serviços oficiais e instituições',
  'Belediye, banka, kurum, form ve belge ile ilgili diyaloglar.',
  'Dialogs for municipalities, banks, official institutions, forms, and documents.',
  'Dialoger om myndigheter, banker, officiella institutioner, blanketter och dokument.',
  'Dialoge über Behörden, Banken, offizielle Institutionen, Formulare und Dokumente.',
  'Diálogos sobre ayuntamientos, bancos, instituciones oficiales, formularios y documentos.',
  'Dialogues sur les administrations, les banques, les institutions officielles, les formulaires et les documents.',
  'Diálogos sobre prefeitura, banco, instituições oficiais, formulários e documentos.',
  '🏛️',
  14,
  true
),
(
  'problems-emergencies',
  'Sorunlar ve Acil Durumlar', 'Problems & Emergencies', 'Problem och nödsituationer', 'Probleme und Notfälle', 'Problemas y emergencias', 'Problèmes et urgences', 'Problemas e emergências',
  'Kayıp eşya, yanlışlık, yardım isteme ve acil ihtiyaç diyalogları.',
  'Dialogs for lost items, mistakes, asking for help, and urgent situations.',
  'Dialoger om borttappade saker, misstag, att be om hjälp och brådskande situationer.',
  'Dialoge über verlorene Gegenstände, Fehler, um Hilfe bitten und dringende Situationen.',
  'Diálogos sobre objetos perdidos, errores, pedir ayuda y situaciones urgentes.',
  'Dialogues sur les objets perdus, les erreurs, demander de l’aide et les situations urgentes.',
  'Diálogos sobre itens perdidos, erros, pedir ajuda e situações urgentes.',
  '🚨',
  15,
  true
)
on conflict (slug) do nothing;